const ENGLISH_WE_QUESTIONS_DB = {
  "english_we": {

    "Grammar: Relative Clauses": {
      mcq: [
        {q:"A relative clause gives more information about a ___.",opts:["verb","noun or pronoun","adverb","sentence"],ans:1},
        {q:"'The man WHO lives next door is a doctor.' The relative pronoun 'who' refers to:",opts:["A thing","An animal","A person","A place"],ans:2},
        {q:"Which relative pronoun is used for things and animals?",opts:["Who","Whom","Which","Whose"],ans:2},
        {q:"'The book THAT I borrowed is very interesting.' 'That' can be replaced by:",opts:["Who","Whose","Which","Whom"],ans:2},
        {q:"'The girl WHOSE bag was stolen went to the police.' 'Whose' shows:",opts:["The object","Possession/belonging","The subject","Time"],ans:1},
        {q:"In a DEFINING relative clause:",opts:["The information is extra — can be removed","The information is essential to identify the noun","It always uses 'which'","It is separated by commas"],ans:1},
        {q:"In a NON-DEFINING relative clause, commas are used:",opts:["Never","Before and after the clause (extra information)","Only before","Only after"],ans:1},
        {q:"'The Eiffel Tower, WHICH is in Paris, is very tall.' This is a:",opts:["Defining relative clause","Non-defining relative clause","Adverb clause","Noun clause"],ans:1},
        {q:"'The student WHO studies hard will succeed.' Can 'who' be omitted here?",opts:["Yes, always","No, it is the subject — cannot be omitted","Yes, when it's an object","Only in speech"],ans:1},
        {q:"'The film (THAT/WHICH) we watched yesterday was amazing.' The relative pronoun here is:",opts:["The subject of the clause","The object — can be omitted","Showing possession","Showing place"],ans:1},
        {q:"'The place WHERE I was born is a small village.' 'Where' is a relative pronoun for:",opts:["Time","Reason","Place","Person"],ans:2},
        {q:"'The day WHEN I met her was rainy.' 'When' refers to:",opts:["A person","A thing","A place","Time"],ans:3},
        {q:"'That is the reason WHY I left.' 'Why' is a relative pronoun for:",opts:["Person","Reason","Place","Time"],ans:1},
        {q:"Choose the correct sentence:",opts:["The boy which won the prize was happy","The boy who won the prize was happy","The boy whom won the prize was happy","The boy whose won the prize was happy"],ans:1},
        {q:"'This is the car WHOSE engine is the best.' Which type of relative clause is this?",opts:["Non-defining","Defining — essential information","Adverb clause","Reported speech"],ans:1}
      ],
      short: [
        {q:"What is a relative clause? Explain defining and non-defining relative clauses with examples.",a:"RELATIVE CLAUSE:\nA relative clause is a type of subordinate clause that gives more information about a noun. It begins with a relative pronoun (who, whom, whose, which, that) or relative adverb (where, when, why).\n\nDEFINING (RESTRICTIVE) RELATIVE CLAUSE:\n• Gives ESSENTIAL information that identifies the noun\n• Without it, the sentence is unclear or meaningless\n• No commas used\n• Example: 'The man WHO called you is my uncle.' (defines WHICH man)\n\nNON-DEFINING (NON-RESTRICTIVE) RELATIVE CLAUSE:\n• Gives EXTRA/ADDITIONAL information about a noun already identified\n• The sentence still makes sense without it\n• Commas used before and after\n• Cannot use 'that' in non-defining clauses\n• Example: 'My father, WHO is a doctor, works at the city hospital.' (extra info about father)\n\nKEY DIFFERENCE:\n• Defining: 'The student who works hard will pass.' (tells us WHICH student)\n• Non-defining: 'Ravi, who works hard, will pass.' (Ravi already identified — extra info)"},
        {q:"Fill in the blanks with appropriate relative pronouns: who, whom, which, whose, where, when, why.",a:"RELATIVE PRONOUNS AND THEIR USE:\n\n1. WHO — for people (subject)\n   'The woman WHO teaches us is kind.'\n\n2. WHOM — for people (object)\n   'The person WHOM I met yesterday is my cousin.'\n\n3. WHICH — for things and animals\n   'The book WHICH I read was interesting.'\n\n4. THAT — for people, things, animals (especially in defining clauses)\n   'The car THAT broke down was old.'\n\n5. WHOSE — possession (people, things, animals)\n   'The girl WHOSE phone rang was embarrassed.'\n\n6. WHERE — for places\n   'The school WHERE I studied is famous.'\n\n7. WHEN — for time\n   'The year WHEN I was born was 1990.'\n\n8. WHY — for reason\n   'I know the reason WHY she left.'\n\nPRACTICE:\n• The dog __ bit me is aggressive. (which/that)\n• She is the woman __ daughter won the prize. (whose)\n• This is the town __ I grew up. (where)"}
      ],
      long: [
        {q:"Combine the following sentences using relative clauses:\n(a) The boy is my friend. He won the race.\n(b) I bought a book. The book was very expensive.\n(c) She lives in a city. The city is very famous.\n(d) The man spoke well. His speech moved everyone.",a:"COMBINING WITH RELATIVE CLAUSES:\n\n(a) 'The boy who won the race is my friend.'\n(DEFINING: 'who won the race' identifies which boy)\n\n(b) 'The book which/that I bought was very expensive.'\n(DEFINING: 'which I bought' identifies which book)\nOR: 'I bought a book, which was very expensive.'\n(NON-DEFINING: extra information about the book)\n\n(c) 'She lives in a city which/that is very famous.'\n(DEFINING: identifies which city)\nOR: 'She lives in Delhi, which is a very famous city.'\n(NON-DEFINING: Delhi already named, extra info)\n\n(d) 'The man whose speech moved everyone spoke well.'\n(DEFINING: 'whose speech moved everyone' identifies which man)\n\nGRAMMAR RULES APPLIED:\n• 'Who' → for people as subject\n• 'Which/that' → for things\n• 'Whose' → for possession\n• Commas in non-defining clauses\n• 'That' cannot be used in non-defining clauses"}
      ],
      passage: [
        {q:"Read the following passage and answer the questions:\n\n'Mahatma Gandhi, who led India's independence movement, was born in Porbandar. He developed the concept of Satyagraha, which means truth-force. The Dandi March, which he led in 1930, was a key moment in the freedom struggle. People who followed him came from all walks of life.'\n\n(a) Identify all relative clauses in the passage.\n(b) Which are defining and which are non-defining?\n(c) What does each relative pronoun refer to?\n(d) Rewrite the second sentence by combining it with: 'Satyagraha was practised by millions.'",a:"(a) Relative clauses in the passage:\n1. 'who led India's independence movement' (about Mahatma Gandhi)\n2. 'which means truth-force' (about Satyagraha)\n3. 'which he led in 1930' (about the Dandi March)\n4. 'who followed him' (about people)\n\n(b) Defining vs Non-defining:\n• 'who led India's independence movement' — NON-DEFINING (Gandhi already named, commas used)\n• 'which means truth-force' — NON-DEFINING (Satyagraha already named, commas used)\n• 'which he led in 1930' — NON-DEFINING (Dandi March already named, commas used)\n• 'who followed him' — DEFINING (identifies WHICH people — those who followed him)\n\n(c) What each relative pronoun refers to:\n• First 'who' → Mahatma Gandhi (a person)\n• 'which' (first) → Satyagraha (a concept/thing)\n• 'which' (second) → The Dandi March (an event/thing)\n• Second 'who' → People\n\n(d) Rewritten sentence:\n'He developed the concept of Satyagraha, which means truth-force and was practised by millions.'\nOR: 'He developed the concept of Satyagraha, which means truth-force, and this concept was practised by millions.'"}
      ]
    },

    "Grammar: Articles and Determiners": {
      mcq: [
        {q:"Which article is used before a word beginning with a vowel sound?",opts:["a","an","the","no article"],ans:1},
        {q:"'___ Eiffel Tower is in Paris.' Which article fits?",opts:["A","An","The","No article"],ans:2},
        {q:"'He is ___ honest man.' The correct article is:",opts:["a","an","the","no article needed"],ans:1},
        {q:"'___ sun rises in the east.' The correct article is:",opts:["A","An","The","No article"],ans:2},
        {q:"'She is ___ engineer.' The correct article is:",opts:["a","an","the","No article"],ans:1},
        {q:"When do we use NO article?",opts:["Before singular nouns","Before plural nouns used in general sense and uncountable nouns in general","Before unique things","Before proper nouns always"],ans:1},
        {q:"'___ milk is good for health.' The blank needs:",opts:["A","An","The","No article"],ans:3},
        {q:"'___ Amazon is the longest river in South America.' Article needed:",opts:["A","An","The","No article"],ans:2},
        {q:"'She plays ___ piano very well.' Article needed:",opts:["a","an","the","no article"],ans:2},
        {q:"'___ gold is a precious metal.' Article needed (general statement):",opts:["A","An","The","No article"],ans:3},
        {q:"Determiners include:",opts:["Only articles (a, an, the)","Articles, demonstratives (this/that), possessives (my/your), quantifiers (some/any/many)","Only pronouns","Only adjectives"],ans:1},
        {q:"'___ of the students passed.' Which determiner fits?",opts:["All","Each of","Some","Most"],ans:3},
        {q:"'I have ___ idea.' The correct article is:",opts:["a","an","the","no article"],ans:1},
        {q:"'___ Mt. Everest is the highest peak.' Article needed:",opts:["A","An","The","No article"],ans:3},
        {q:"'He is ___ best student in the class.' Article needed:",opts:["a","an","the","no article"],ans:2}
      ],
      short: [
        {q:"Explain the use of 'a', 'an' and 'the' with rules and examples.",a:"USE OF ARTICLES:\n\n'A' — INDEFINITE ARTICLE:\n• Used before singular countable nouns beginning with a CONSONANT SOUND\n• Used when mentioning something for the first time / non-specific\n• Examples: a book, a university (u- has consonant /yoo/ sound), a one-way street\n\n'AN' — INDEFINITE ARTICLE:\n• Used before singular countable nouns beginning with a VOWEL SOUND\n• Examples: an apple, an hour (h is silent → vowel sound), an MBA, an honest man\n\n'THE' — DEFINITE ARTICLE:\n• Used when the noun is specific or already mentioned\n• Used for unique things: the sun, the moon, the earth\n• Used with superlatives: the best, the tallest\n• Used with names of rivers, seas, mountain ranges: the Ganga, the Himalayas\n• Used with musical instruments: play the guitar\n\nNO ARTICLE:\n• Before plural nouns in general: Dogs are loyal (general)\n• Before uncountable nouns in general: Water is essential\n• Before proper nouns (most): India, Delhi, Ravi\n• Before meals, days, months in general: I have breakfast at 8"},
        {q:"Correct the article errors in these sentences:\n(a) She is a honest person.\n(b) I saw a Taj Mahal.\n(c) He plays a piano.\n(d) An university is near my house.",a:"CORRECTED SENTENCES:\n\n(a) ✗ 'She is a honest person.'\n✓ 'She is AN honest person.'\nReason: 'honest' begins with a vowel SOUND (/ɒnɪst/) — 'h' is silent\n\n(b) ✗ 'I saw a Taj Mahal.'\n✓ 'I saw THE Taj Mahal.'\nReason: The Taj Mahal is a unique, specific, well-known monument — use 'the'\n\n(c) ✗ 'He plays a piano.'\n✓ 'He plays THE piano.'\nReason: Musical instruments take 'the' — 'play the guitar/piano/violin'\n\n(d) ✗ 'An university is near my house.'\n✓ 'A university is near my house.'\nReason: 'university' begins with a consonant SOUND (/juːnɪvɜːsɪti/) — 'u' sounds like 'yoo'"}
      ],
      long: [
        {q:"Fill in the blanks with appropriate articles (a/an/the/—) in the following paragraph and explain your choices:\n\n'___ Nile is ___ longest river in ___ world. It flows through ___ Africa. ___ ancient Egyptians built ___ great civilisations along its banks. ___ river has ___ enormous historical importance.'",a:"FILLED PARAGRAPH WITH EXPLANATIONS:\n\n'THE Nile is THE longest river in THE world. It flows through — Africa. THE ancient Egyptians built — great civilisations along its banks. THE river has AN enormous historical importance.'\n\nEXPLANATIONS:\n1. THE Nile → 'the' with names of rivers (the Ganga, the Thames, the Nile)\n2. THE longest → 'the' with superlatives (the longest, the best, the tallest)\n3. THE world → 'the' — unique entity\n4. — Africa → no article before continents (Africa, Asia, Europe)\n5. THE ancient Egyptians → 'the' — specific people (a particular civilisation)\n6. — great civilisations → no article — plural noun, general (OR 'great' = no specific reference)\n7. THE river → 'the' — already mentioned (the Nile, now referred to as 'the river')\n8. AN enormous → 'an' before vowel sound (e- in enormous = vowel sound)"}
      ],
      passage: [
        {q:"Read and find all articles in this passage, then answer questions:\n\n'A young student found an old book in the library. The book contained an interesting story about a great king who lived in an ancient city. The king was famous for his wisdom.'\n\n(a) List all articles used and the nouns they refer to.\n(b) Why is 'a young student' used instead of 'the young student'?\n(c) Why is 'the library' used with 'the'?\n(d) Why is 'an old book' used, not 'a old book'?",a:"(a) Articles and their nouns:\n• A young student — indefinite, first mention\n• an old book — indefinite, first mention\n• the library — definite (specific library)\n• The book — definite (already mentioned)\n• an interesting story — indefinite, first mention\n• a great king — indefinite, first mention\n• an ancient city — indefinite, first mention\n• The king — definite (already mentioned)\n\n(b) 'A young student' not 'the young student' because:\n• It is the FIRST mention — the reader doesn't know which student\n• It's not a specific, identified student known to the reader\n• 'The' would be used if we had already mentioned the student or both speaker and listener know which student\n\n(c) 'The library' uses 'the' because:\n• It refers to a SPECIFIC library — a particular one known in context\n• When there is one library in a school/town, everyone knows which library is meant\n• Specific, known places use 'the'\n\n(d) 'An old book' not 'a old book' because:\n• 'Old' begins with a VOWEL SOUND (/ɒld/)\n• 'An' is used before vowel sounds, regardless of spelling\n• The rule is about SOUND, not spelling"}
      ]
    },

    "Grammar: Tenses and Verb Forms": {
      mcq: [
        {q:"'She ___ (study) for three hours when I called.' Correct tense:",opts:["was studying","had been studying","studied","is studying"],ans:1},
        {q:"The Past Perfect Tense is used to show:",opts:["Ongoing action in present","An action completed BEFORE another past action","Future action","Habitual action"],ans:1},
        {q:"'By the time he arrived, we ___ (finish) dinner.' Correct form:",opts:["finished","were finishing","had finished","have finished"],ans:2},
        {q:"'I ___ (live) here since 2010.' Correct tense (action continuing to present):",opts:["lived","have been living","was living","am living"],ans:1},
        {q:"Which sentence uses the Present Perfect correctly?",opts:["I have went there yesterday","She has just finished her work","They have saw the movie last week","He has been born in 1990"],ans:1},
        {q:"'When I was young, I ___ (walk) to school every day.' Correct form (habitual past):",opts:["would walk / used to walk","had walked","was walking","have walked"],ans:0},
        {q:"The passive voice of 'Someone stole my bag.' is:",opts:["My bag has been stolen","My bag was stolen","My bag is stolen","My bag had been stolen"],ans:1},
        {q:"'The work ___ (complete) by tomorrow.' Correct future passive:",opts:["will complete","will be completed","would complete","is completed"],ans:1},
        {q:"Identify the error: 'She have been working here for ten years.'",opts:["No error","'have' should be 'has' — she = third person singular","'been' is wrong","'working' is wrong"],ans:1},
        {q:"'I wish I ___ taller.' Correct form (subjunctive/conditional wish):",opts:["am","was","were","will be"],ans:2},
        {q:"'If I ___ (be) you, I would apologise.' Correct conditional form:",opts:["am","was","were","will be"],ans:2},
        {q:"'He said he ___ (be) tired.' Correct reported speech tense:",opts:["is","was","were","had been"],ans:1},
        {q:"'She ___ (not/see) this film before.' Correct Present Perfect negative:",opts:["didn't see","hasn't seen","don't see","hadn't seen"],ans:1},
        {q:"The difference between Simple Past and Past Perfect: 'She had left BEFORE he arrived' — 'had left' shows:",opts:["Same time action","Later action","Earlier action (happened first)","Habitual action"],ans:2},
        {q:"'Look! The children ___ (play) in the garden.' Correct tense:",opts:["played","play","are playing","have played"],ans:2}
      ],
      short: [
        {q:"Explain the difference between Simple Past and Present Perfect tense with examples.",a:"SIMPLE PAST:\n• Used for a completed action at a SPECIFIC time in the past\n• Time is mentioned or implied\n• Examples:\n  - 'I visited Delhi last year.'\n  - 'She graduated in 2019.'\n  - 'He broke his leg yesterday.'\n• Keywords: yesterday, last week, in 2010, ago, when I was young\n\nPRESENT PERFECT:\n• Used for a past action with a CONNECTION to the present\n• Time not specified / action has present relevance\n• Formed: have/has + past participle\n• Uses:\n  - Recently completed: 'She has just finished the work.'\n  - Experience: 'I have visited Paris.' (at some time in life)\n  - With 'since/for': 'He has lived here for 10 years.' (still lives here)\n  - News: 'The Prime Minister has arrived.'\n\nKEY DIFFERENCE:\n• 'I saw that film' (Simple Past — specific time implied)\n• 'I have seen that film' (Present Perfect — experience, no specific time)\n• 'She studied yesterday' vs 'She has studied today'"},
        {q:"Rewrite these sentences in the passive voice:\n(a) The students wrote the exam.\n(b) Someone has broken the window.\n(c) The teacher will announce the results.\n(d) They were building a new school.",a:"PASSIVE VOICE:\n\n(a) Active: 'The students wrote the exam.'\nPassive: 'The exam was written by the students.'\n(Simple Past: was/were + past participle)\n\n(b) Active: 'Someone has broken the window.'\nPassive: 'The window has been broken (by someone).'\n(Present Perfect: has/have + been + past participle)\n\n(c) Active: 'The teacher will announce the results.'\nPassive: 'The results will be announced by the teacher.'\n(Future: will + be + past participle)\n\n(d) Active: 'They were building a new school.'\nPassive: 'A new school was being built by them.'\n(Past Continuous: was/were + being + past participle)\n\nRULE: Active = Subject + Verb + Object\nPassive = Object becomes Subject + be (appropriate form) + past participle + by + original subject"}
      ],
      long: [
        {q:"Fill in the blanks with the correct form of verbs in brackets. Identify the tense used:\n(a) She ___ (leave) before he ___ (arrive).\n(b) They ___ (play) cricket for two hours when it ___ (start) raining.\n(c) I ___ (not/meet) her since last year.\n(d) By next year, he ___ (complete) his degree.\n(e) Look! A bird ___ (sit) on your head!",a:"(a) She HAD LEFT before he ARRIVED.\nTenses: Past Perfect ('had left') + Simple Past ('arrived')\nReason: 'Leaving' happened BEFORE 'arriving' — Past Perfect for earlier action\n\n(b) They HAD BEEN PLAYING cricket for two hours when it STARTED raining.\nTenses: Past Perfect Continuous ('had been playing') + Simple Past ('started')\nReason: Ongoing action over a period before a past event\n\n(c) I HAVE NOT MET her since last year.\nTense: Present Perfect Negative\nReason: 'Since' connects past to present — use Present Perfect\n\n(d) By next year, he WILL HAVE COMPLETED his degree.\nTense: Future Perfect\nReason: Action completed at a point in the future ('by next year')\n\n(e) Look! A bird IS SITTING on your head!\nTense: Present Continuous\nReason: Action happening RIGHT NOW ('Look!') — use present continuous"}
      ],
      passage: [
        {q:"Read and answer:\n\n'Priya had been waiting for an hour when her friend finally arrived. She had already ordered tea and was reading a book. \"I am sorry I am late,\" said the friend. \"I have been stuck in traffic.\" Priya smiled. She had never been angry with her friend.'\n\n(a) Identify and explain the tense in: 'had been waiting'\n(b) Why is 'had already ordered' used?\n(c) Change 'I have been stuck in traffic' to Simple Past.\n(d) What does 'had never been angry' tell us about Priya's character?",a:"(a) 'had been waiting' — PAST PERFECT CONTINUOUS\n• Formation: had + been + verb-ing\n• Meaning: An action that was ONGOING over a period of time BEFORE another past event\n• 'She had been waiting for an hour' = she started waiting an hour before the friend arrived, and was still waiting when the friend arrived\n• It emphasises the DURATION of the waiting\n\n(b) 'had already ordered' — PAST PERFECT\n• The ordering happened BEFORE the friend arrived (another past event)\n• 'Already' reinforces that the action was completed prior to the friend's arrival\n• Past Perfect is used for the action that happened FIRST when two past actions are mentioned\n• Had + past participle (had ordered)\n\n(c) 'I have been stuck in traffic' (Present Perfect Continuous) → Simple Past:\n'I was stuck in traffic.'\n(Simple Past uses base form of 'to be' — 'was' for singular subject)\n\n(d) 'Had never been angry with her friend' tells us:\n• Priya was a very forgiving, patient and good-natured person\n• Despite waiting a whole hour, she felt no anger — showing remarkable patience\n• She valued the friendship over punctuality\n• 'Never' + Past Perfect suggests this was her consistent character over time"}
      ]
    },

    "Grammar: Reported Speech": {
      mcq: [
        {q:"In reported (indirect) speech, the reporting verb is usually in past tense, so 'is' changes to:",opts:["is","was","has been","will be"],ans:1},
        {q:"'She said, \"I am tired.\"' In reported speech:",opts:["She said she is tired","She said she was tired","She said she were tired","She told she was tired"],ans:1},
        {q:"'He said, \"I will come tomorrow.\"' In reported speech:",opts:["He said he will come the next day","He said he would come the next day","He said he came the next day","He said he comes the next day"],ans:1},
        {q:"'Today' in direct speech changes to ___ in reported speech:",opts:["today","that day","yesterday","this day"],ans:1},
        {q:"'Yesterday' changes to ___ in reported speech:",opts:["yesterday","the day before","that day","the previous week"],ans:1},
        {q:"'Here' changes to ___ in reported speech:",opts:["here","there","nearby","that place"],ans:1},
        {q:"For reporting QUESTIONS, we use:",opts:["'said that'","'asked if/whether' (yes/no) or 'asked + wh-word' (wh-questions)","'told that'","'spoke that'"],ans:1},
        {q:"'She asked, \"Are you hungry?\"' In reported speech:",opts:["She asked if I was hungry","She asked that I was hungry","She asked am I hungry","She asked whether am I hungry"],ans:0},
        {q:"For reporting COMMANDS, we use:",opts:["said that","told that","told + object + to + infinitive","asked that"],ans:2},
        {q:"'He said, \"Please sit down.\"' In reported speech:",opts:["He said to sit down","He requested me to sit down","He told to sit down","He said please to sit down"],ans:1},
        {q:"'She said, \"I have finished my work.\"' In reported speech:",opts:["She said she has finished her work","She said she had finished her work","She said she finished her work","She said she will finish her work"],ans:1},
        {q:"'Now' in direct speech changes to ___ in reported speech:",opts:["now","then","at that time","immediately"],ans:2},
        {q:"'This' in direct speech changes to ___ in reported speech:",opts:["this","that","it","there"],ans:1},
        {q:"Which tense change is correct in reported speech?",opts:["Simple Present → Simple Present","Simple Present → Simple Past","Present Perfect → Simple Present","Future → Present"],ans:1},
        {q:"'He asked, \"Where do you live?\"' In reported speech:",opts:["He asked where do I live","He asked where I lived","He asked where did I live","He asked where I live"],ans:1}
      ],
      short: [
        {q:"What are the tense changes in reported speech? Give examples of each.",a:"TENSE CHANGES IN REPORTED SPEECH:\n\nDIRECT → REPORTED:\n1. Simple Present → Simple Past\n   Direct: 'I love music.'\n   Reported: She said she loved music.\n\n2. Present Continuous → Past Continuous\n   Direct: 'I am studying.'\n   Reported: He said he was studying.\n\n3. Present Perfect → Past Perfect\n   Direct: 'I have finished.'\n   Reported: She said she had finished.\n\n4. Simple Past → Past Perfect\n   Direct: 'I saw the film.'\n   Reported: He said he had seen the film.\n\n5. Will → Would\n   Direct: 'I will come.'\n   Reported: She said she would come.\n\n6. Can → Could\n   Direct: 'I can swim.'\n   Reported: He said he could swim.\n\n7. May → Might\n   Direct: 'It may rain.'\n   Reported: She said it might rain.\n\nNO TENSE CHANGE when:\n• The reporting verb is present tense: 'She says she is busy.'\n• The statement is a universal truth: 'He said the sun rises in the east.'"},
        {q:"Change these sentences to reported speech:\n(a) 'I live in Mumbai,' said Ravi.\n(b) 'Are you ready?' she asked me.\n(c) 'Please open the window,' he said.\n(d) 'We have completed the project,' they told us.",a:"REPORTED SPEECH:\n\n(a) 'I live in Mumbai,' said Ravi.\n→ Ravi said that he lived in Mumbai.\n(Simple Present → Simple Past; I → he)\n\n(b) 'Are you ready?' she asked me.\n→ She asked me if/whether I was ready.\n(Yes/No question: use 'if/whether'; Simple Present → Simple Past; you → I)\n\n(c) 'Please open the window,' he said.\n→ He requested me to open the window.\n(Command/request with 'please': requested + object + to + infinitive)\nOR: He asked me to open the window.\n\n(d) 'We have completed the project,' they told us.\n→ They told us that they had completed the project.\n(Present Perfect → Past Perfect; we → they)"}
      ],
      long: [
        {q:"Read this dialogue and rewrite it in reported speech:\n\nTeacher: 'Have you done your homework?'\nStudent: 'No, I haven't. I was ill yesterday.'\nTeacher: 'Please submit it tomorrow.'\nStudent: 'I will definitely bring it tomorrow.'",a:"REPORTED SPEECH — DIALOGUE:\n\nThe teacher asked the student if he/she had done his/her homework.\n\nThe student replied that he/she had not. He/She said that he/she had been ill the previous day.\n\nThe teacher asked/requested the student to submit it the following day.\n\nThe student said that he/she would definitely bring it the next day.\n\nCHANGES MADE:\n• 'Have you done' (Present Perfect Question) → 'had done' (Past Perfect)\n• 'if/whether' added for yes/no question\n• 'No, I haven't' → 'that he/she had not'\n• 'was ill' (Simple Past) → 'had been ill' (Past Perfect)\n• 'yesterday' → 'the previous day'\n• 'Please submit' (command) → 'requested...to submit'\n• 'tomorrow' → 'the following day' / 'the next day'\n• 'I will bring' → 'he/she would bring'\n• Pronouns changed: I/you → he/she"}
      ],
      passage: [
        {q:"Read the conversation and answer questions:\n\nRaj: 'I am going to visit Agra tomorrow.'\nSita: 'Have you been to Agra before?'\nRaj: 'No, this is my first visit. I am very excited!'\nSita: 'Please bring me a souvenir.'\n\n(a) Report Raj's first statement.\n(b) Report Sita's question.\n(c) Report Raj's reply ('No, this is my first visit...')\n(d) Report Sita's request.",a:"(a) Report of Raj's first statement:\nRaj said (that) he was going to visit Agra the next day/the following day.\n\nChanges: 'I am going' → 'he was going'; 'tomorrow' → 'the next day/the following day'\n\n(b) Report of Sita's question:\nSita asked Raj if/whether he had been to Agra before.\n\nChanges: 'Have you been' (Present Perfect) → 'had been' (Past Perfect); Yes/No question → 'if/whether'; 'you' → 'he'\n\n(c) Report of Raj's reply:\nRaj said that it was his first visit (there) and that he was very excited.\n\nChanges: 'No' (dropped as it's answered by 'this is my first visit'); 'this is' → 'it was'; 'I am' → 'he was'; 'my' → 'his'\n\n(d) Report of Sita's request:\nSita requested/asked Raj to bring her a souvenir.\n\nChanges: 'Please bring me' (command/request with 'please') → 'requested/asked + object + to + infinitive'; 'me' → 'her'"}
      ]
    },

    "Grammar: Modals and Conditionals": {
      mcq: [
        {q:"'You ___ (must/should) wear a helmet while cycling.' Which modal expresses OBLIGATION?",opts:["should","must","can","might"],ans:1},
        {q:"'She ___ speak three languages.' Which modal expresses ABILITY?",opts:["must","should","can","ought to"],ans:2},
        {q:"'It ___ rain today — the sky is dark.' Which modal expresses POSSIBILITY?",opts:["must","will","might/may","shall"],ans:2},
        {q:"'You ___ not smoke here — it's prohibited.' Which modal expresses PROHIBITION?",opts:["should","may","must","would"],ans:2},
        {q:"In a FIRST CONDITIONAL sentence (real/possible):",opts:["If + Past → would + infinitive","If + Present Simple → will + infinitive","If + Past Perfect → would have + past participle","If + were → would + infinitive"],ans:1},
        {q:"In a SECOND CONDITIONAL (unreal/hypothetical present/future):",opts:["If + Present Simple → will + base verb","If + Simple Past → would + base verb","If + had + pp → would have + pp","If + Present → can + base verb"],ans:1},
        {q:"In a THIRD CONDITIONAL (impossible/hypothetical past):",opts:["If + Past → would + base verb","If + Past Perfect → would have + past participle","If + Present → will + base verb","If + were → would + base verb"],ans:1},
        {q:"'If it ___ (rain), we will cancel the match.' Correct first conditional:",opts:["rained","rains","would rain","has rained"],ans:1},
        {q:"'If I ___ (be) taller, I could be a basketball player.' Correct second conditional:",opts:["am","was","were","will be"],ans:2},
        {q:"'If she ___ (study) harder, she would have passed.' Correct third conditional:",opts:["studied","studies","had studied","would study"],ans:2},
        {q:"'___ you please help me?' This modal expresses:",opts:["Permission","Ability","Polite request","Obligation"],ans:2},
        {q:"'You ___ take rest — you look tired.' This expresses:",opts:["Permission","Prohibition","Advice/suggestion","Ability"],ans:2},
        {q:"'He ___ have taken the wrong bus.' This expresses:",opts:["Certainty about present","Possibility about past","Future plan","Permission"],ans:1},
        {q:"'When I was a child, I ___ climb trees easily.' Correct modal for past ability:",opts:["can","could","may","might"],ans:1},
        {q:"'You ___ (not/have to) come if you don't want to — it's optional.' This expresses:",opts:["Prohibition","Lack of obligation/necessity","Strong advice","Permission"],ans:1}
      ],
      short: [
        {q:"Explain the three types of conditional sentences with examples.",a:"THREE TYPES OF CONDITIONAL SENTENCES:\n\n1. FIRST CONDITIONAL (Real/Likely condition — present/future):\n• Structure: If + Simple Present, will + base verb\n• Use: Realistic possibilities\n• Examples:\n  - 'If it rains, we will stay home.'\n  - 'If you study hard, you will pass.'\n  - 'If she calls, I will answer.'\n\n2. SECOND CONDITIONAL (Unreal/Imaginary — present/future):\n• Structure: If + Simple Past (were for all persons), would + base verb\n• Use: Hypothetical, imaginary situations\n• Examples:\n  - 'If I were rich, I would travel the world.'\n  - 'If she had a car, she would drive to work.'\n  - 'If I were you, I would apologise.'\n\n3. THIRD CONDITIONAL (Impossible — past situation with past result):\n• Structure: If + Past Perfect (had + pp), would have + past participle\n• Use: Imagining a different outcome for a past situation\n• Examples:\n  - 'If I had studied more, I would have passed.'\n  - 'If she had left earlier, she wouldn't have missed the bus.'\n\nKEY: The type of conditional determines which tense to use in both clauses."},
        {q:"Choose the correct modal and explain the meaning:\n(a) You ___ (must/should) see a doctor — you look very ill.\n(b) Students ___ (must/may) use calculators in the exam — it's permitted.\n(c) He ___ (can/could) swim when he was five.\n(d) It ___ (might/must) be raining — I can hear thunder.",a:"MODAL ANSWERS WITH EXPLANATIONS:\n\n(a) You MUST see a doctor — you look very ill.\nMeaning: Strong necessity/obligation — 'must' expresses the speaker's strong recommendation based on evidence. 'Should' could also work but is slightly weaker.\n\n(b) Students MAY use calculators in the exam — it's permitted.\nMeaning: Permission — 'may' is used for formal permission. 'Can' is also acceptable but 'may' is more formal.\n\n(c) He COULD swim when he was five.\nMeaning: Past ability — 'could' is the past tense of 'can' expressing ability in the past. 'Can' would be wrong (it's past tense needed).\n\n(d) It MIGHT be raining — I can hear thunder.\nMeaning: Possibility — 'might' expresses uncertainty/probability. 'Must' would express certainty ('it must be raining'). Since we only hear thunder (indirect evidence), 'might' is appropriate."}
      ],
      long: [
        {q:"Write sentences using each modal (can, could, may, might, must, should, would, shall, ought to) and explain what meaning each expresses.",a:"MODALS WITH MEANINGS AND EXAMPLES:\n\n1. CAN — ability (present), informal permission\n   'She can speak French fluently.' (ability)\n   'You can leave early today.' (informal permission)\n\n2. COULD — past ability, polite request, possibility\n   'He could run fast when young.' (past ability)\n   'Could you help me please?' (polite request)\n\n3. MAY — formal permission, possibility\n   'You may enter.' (formal permission)\n   'It may rain today.' (possibility — fairly likely)\n\n4. MIGHT — weak possibility, past of may\n   'She might be at home.' (weaker possibility)\n   'It might work.' (uncertain possibility)\n\n5. MUST — strong obligation, certainty\n   'You must wear your seatbelt.' (obligation)\n   'She must be tired — she's been working all day.' (certainty)\n\n6. SHOULD — advice, recommendation, moral obligation\n   'You should exercise regularly.' (advice)\n   'Students should be respectful.' (moral duty)\n\n7. WOULD — conditional, past habit, polite request\n   'I would help if I could.' (conditional)\n   'Would you open the door?' (polite request)\n\n8. SHALL — formal future, offers/suggestions (British)\n   'Shall we begin?' (suggestion)\n   'I shall return.' (formal future)\n\n9. OUGHT TO — moral obligation (slightly weaker than must)\n   'You ought to apologise.' (moral duty)\n   'Children ought to respect elders.' (moral obligation)"}
      ],
      passage: [
        {q:"Read and rewrite using appropriate modals:\n\n'Ravi is able to play guitar. He has permission to perform at the school event. It is possible that he will perform tomorrow. He has an obligation to practise every day. I advise you to listen to his performance.'\n\nRewrite each sentence using an appropriate modal and answer:\n(a) What is the difference between 'must' and 'have to'?\n(b) Create a second conditional sentence about Ravi.",a:"REWRITTEN WITH MODALS:\n\n1. 'Ravi is able to play guitar.'\n→ Ravi CAN play guitar.\n(CAN = ability)\n\n2. 'He has permission to perform at the school event.'\n→ He MAY perform at the school event.\n(MAY = permission)\n\n3. 'It is possible that he will perform tomorrow.'\n→ He MIGHT/MAY perform tomorrow.\n(MIGHT/MAY = possibility)\n\n4. 'He has an obligation to practise every day.'\n→ He MUST practise every day.\n(MUST = strong obligation)\n\n5. 'I advise you to listen to his performance.'\n→ You SHOULD listen to his performance.\n(SHOULD = advice)\n\n(a) Difference between MUST and HAVE TO:\n• MUST: Internal obligation — the speaker imposes the obligation / personal decision\n  'I must finish this work.' (I'm deciding this myself)\n• HAVE TO: External obligation — rules, laws, or others require it\n  'I have to submit the project by Friday.' (deadline imposed by teacher)\n• Negative difference: MUST NOT = prohibition; DON'T HAVE TO = no obligation\n  'You must not smoke here.' (prohibited)\n  'You don't have to come.' (no obligation, optional)\n\n(b) Second conditional about Ravi:\n'If Ravi practised more, he would become a professional guitarist.'\n(Hypothetical: imagining what could happen if a different condition were true)"}
      ]
    },

    "Vocabulary and Word Skills": {
      mcq: [
        {q:"A word that means the SAME as another word is called a:",opts:["Antonym","Synonym","Homonym","Homophone"],ans:1},
        {q:"A word that means the OPPOSITE of another word is called an:",opts:["Synonym","Antonym","Acronym","Metaphor"],ans:1},
        {q:"Words that are spelled differently but sound the same are called:",opts:["Homonyms","Synonyms","Homophones","Antonyms"],ans:2},
        {q:"'To read between the lines' is an example of:",opts:["A simile","A metaphor","An idiom","A proverb"],ans:2},
        {q:"'As brave as a lion' is an example of:",opts:["Metaphor","Simile — uses 'as...as' comparison","Idiom","Personification"],ans:1},
        {q:"'Life is a journey' is an example of:",opts:["Simile","Metaphor — direct comparison without 'like' or 'as'","Idiom","Hyperbole"],ans:1},
        {q:"The prefix 'un-' means:",opts:["Again","Before","Not/opposite","After"],ans:2},
        {q:"The suffix '-ful' means:",opts:["Without","Full of","Able to","Like"],ans:1},
        {q:"'Immovable' — what does the prefix 'im-' mean?",opts:["Again","Very","Not","Before"],ans:2},
        {q:"A word formed from the first letters of other words (e.g., NASA) is called:",opts:["Acronym","Initialism","Compound word","Portmanteau"],ans:0},
        {q:"'Beautify', 'beautiful', 'beautifully', 'beauty' — these are examples of:",opts:["Synonyms","Word families","Compound words","Idioms"],ans:1},
        {q:"The word 'autobiography' means:",opts:["Writing about someone else's life","Self-written account of one's own life","Official government document","Scientific journal"],ans:1},
        {q:"'It's raining cats and dogs' means:",opts:["Cats and dogs are falling","It's raining very heavily — an idiom","The weather is unusual","Animals are afraid"],ans:1},
        {q:"A metaphor differs from a simile because:",opts:["A metaphor uses 'like' or 'as'","A metaphor makes a direct comparison without 'like' or 'as'","A metaphor is only used in poetry","A metaphor is always about nature"],ans:1},
        {q:"'The news was a bombshell.' The underlined word is used:",opts:["Literally","Figuratively/metaphorically — the news was shocking, like an explosion","As a synonym","As an antonym"],ans:1}
      ],
      short: [
        {q:"What is the difference between a simile, metaphor and idiom? Give two examples of each.",a:"SIMILE:\nA direct comparison using 'like' or 'as'\n• Examples:\n  1. 'She runs like the wind.' (speed compared to wind)\n  2. 'He is as stubborn as a mule.'\n  3. 'Her voice was like music.'\n\nMETAPHOR:\nA direct comparison WITHOUT 'like' or 'as' — says one thing IS another\n• Examples:\n  1. 'Life is a rollercoaster.'\n  2. 'Time is money.'\n  3. 'The world is a stage.'\n\nIDIOM:\nA phrase whose meaning CANNOT be understood from the individual words — has a figurative meaning\n• Examples:\n  1. 'Break a leg!' (= Good luck!) \n  2. 'It's raining cats and dogs.' (= raining heavily)\n  3. 'Bite the bullet.' (= endure something painful)\n  4. 'Hit the nail on the head.' (= exactly right)\n\nKEY DIFFERENCE:\n• Simile and metaphor are figures of speech that make comparisons\n• Simile is explicit ('like/as'), metaphor is implicit\n• Idiom's meaning is completely different from its literal words"},
        {q:"Use the correct prefixes (un-, in-, im-, dis-, mis-, re-, pre-) to form new words and use them in sentences.",a:"PREFIXES AND MEANINGS:\n\nUN- (not/opposite):\n• unhappy: 'She was unhappy with the result.'\n• unfair: 'The decision was unfair.'\n• unable: 'He was unable to attend.'\n\nIN-/IM- (not — 'im' before m, p, b):\n• incorrect: 'Your answer is incorrect.'\n• impossible: 'Nothing is impossible.'\n• impatient: 'Don't be impatient.'\n\nDIS- (opposite/not):\n• disagree: 'I disagree with your opinion.'\n• dishonest: 'Being dishonest is wrong.'\n• disappear: 'The magician made the rabbit disappear.'\n\nMIS- (wrongly):\n• misunderstand: 'I misunderstood the question.'\n• misspell: 'Be careful not to misspell words.'\n\nRE- (again):\n• rewrite: 'Please rewrite the answer.'\n• reconsider: 'I will reconsider my decision.'\n\nPRE- (before):\n• preview: 'We got a preview of the film.'\n• prepaid: 'He used a prepaid phone card.'"}
      ],
      long: [
        {q:"Read the passage and answer vocabulary questions:\n\n'The young scientist, undeterred by previous failures, embarked on a meticulous investigation. Her perseverance was remarkable. Despite the overwhelming odds, she remained optimistic that her hypothesis would be vindicated. The discovery, when it came, was nothing short of revolutionary.'\n\n(a) Find synonyms for: undeterred, meticulous, perseverance, vindicated.\n(b) Find antonyms for: optimistic, remarkable, revolutionary.\n(c) What does 'nothing short of revolutionary' mean?\n(d) Use 'perseverance' and 'meticulous' in sentences of your own.",a:"(a) SYNONYMS:\n• Undeterred = unhindered, undiscouraged, persistent, resolute, unfazed\n• Meticulous = careful, thorough, precise, painstaking, detailed, systematic\n• Perseverance = persistence, determination, tenacity, dedication, steadfastness\n• Vindicated = justified, proved right, confirmed, exonerated, validated\n\n(b) ANTONYMS:\n• Optimistic ↔ pessimistic, hopeless, despairing, negative\n• Remarkable ↔ ordinary, unremarkable, common, usual, typical\n• Revolutionary ↔ conventional, traditional, ordinary, conservative, commonplace\n\n(c) 'Nothing short of revolutionary' means:\n• 'Nothing short of' is an emphatic expression meaning 'not less than' / 'exactly'\n• So 'nothing short of revolutionary' = 'completely/absolutely revolutionary'\n• The discovery was SO significant that 'revolutionary' is the only adequate word\n• It was not just interesting or new — it was groundbreaking, transformative\n\n(d) Original sentences:\n• Perseverance: 'Mahatma Gandhi's perseverance in the face of colonial oppression inspired millions.'\n• Meticulous: 'The surgeon was meticulous in her preparations, checking every detail before the operation.'"}
      ],
      passage: [
        {q:"Read this extract and answer:\n\n'The sun was a ball of fire. The children ran like gazelles across the field. It was the kind of day that made your heart sing. Everyone was in high spirits, though the air was so thick you could cut it with a knife.'\n\n(a) Identify the figures of speech used.\n(b) What does 'made your heart sing' mean?\n(c) What does 'in high spirits' mean?\n(d) What does 'you could cut it with a knife' suggest about the weather?",a:"(a) Figures of speech:\n1. 'The sun was a ball of fire.' — METAPHOR (sun directly compared to a ball of fire — no 'like/as')\n2. 'ran like gazelles' — SIMILE (comparison using 'like' — emphasises speed and grace)\n3. 'made your heart sing' — METAPHOR/PERSONIFICATION (heart cannot literally sing — means felt great joy)\n4. 'you could cut it with a knife' — HYPERBOLE/IDIOM (exaggeration to describe thick, heavy air)\n\n(b) 'Made your heart sing' means:\n• It made you feel great joy and happiness\n• Your emotions were so positive, it felt like your heart was singing with delight\n• It is a metaphor for an intensely positive emotional experience\n• 'The kind of day' suggests perfect, joyful weather conditions\n\n(c) 'In high spirits' means:\n• In a cheerful, happy, enthusiastic mood\n• Feeling joyful and energetic\n• This is a common English idiom — 'high spirits' = elevated mood\n• Opposite: 'in low spirits' = sad, depressed\n\n(d) 'You could cut it with a knife' suggests:\n• The air was extremely hot, humid and heavy\n• The humidity was so dense it felt almost solid\n• It's a hyperbolic expression to emphasise how thick and uncomfortable the air felt\n• Despite the children's high spirits, the weather was intensely hot and humid\n• Creates a contrast: joyful children but oppressively heavy atmosphere"}
      ]
    },

    "Reading Comprehension Skills": {
      mcq: [
        {q:"When reading for the MAIN IDEA of a passage, you should look for:",opts:["Every single detail","The central message or most important point that all sentences support","Only the first sentence","Only the last sentence"],ans:1},
        {q:"INFERENCE in reading means:",opts:["Finding exact answers stated in the text","Drawing conclusions from clues in the text — not directly stated","Summarising the text","Finding vocabulary words"],ans:1},
        {q:"A TOPIC SENTENCE in a paragraph usually:",opts:["Comes only at the end","States the main idea of the paragraph — often the first sentence","Contains only examples","Is always very long"],ans:1},
        {q:"When answering comprehension questions, you should:",opts:["Only use your own knowledge","Find evidence in the passage and answer based on what is written","Guess from the question","Only use the first paragraph"],ans:1},
        {q:"'Skimming' a text means:",opts:["Reading every word carefully","Reading quickly to get the general idea","Reading only the headings","Reading word by word with a dictionary"],ans:1},
        {q:"'Scanning' a text means:",opts:["Reading the whole text slowly","Looking for specific information quickly without reading everything","Summarising the text","Reading aloud"],ans:1},
        {q:"A SUMMARY should:",opts:["Include all details","Contain only the main points in your own words, briefly","Be longer than the original","Include your opinions"],ans:1},
        {q:"CONTEXT CLUES help you understand:",opts:["Grammar rules","The meaning of an unfamiliar word from surrounding sentences","Spelling","Punctuation"],ans:1},
        {q:"The TONE of a passage refers to:",opts:["The topic","The length","The writer's attitude or feeling expressed through word choice","The vocabulary level"],ans:2},
        {q:"When a question asks you to 'explain in your own words', you should:",opts:["Copy exact phrases from the text","Paraphrase — restate the meaning using different words","Give your personal opinion","Write a long essay"],ans:1},
        {q:"A comprehension passage about 'Benefits of Exercise' would most likely be:",opts:["Narrative (tells a story)","Descriptive","Expository (gives information/explains)","Dramatic"],ans:2},
        {q:"The purpose of a conclusion in a passage is to:",opts:["Introduce new ideas","Summarise main points and give a final thought","Provide examples","Ask questions"],ans:1},
        {q:"When a text says 'On the other hand...', it signals:",opts:["Addition of more examples","A contrast or opposite viewpoint","A conclusion","A time sequence"],ans:1},
        {q:"'Furthermore', 'Moreover', 'In addition' are examples of:",opts:["Contrast connectors","Addition/addition connectors","Cause-effect connectors","Conclusion connectors"],ans:1},
        {q:"'Therefore', 'Thus', 'As a result' are examples of:",opts:["Addition connectors","Contrast connectors","Cause-effect/result connectors","Time connectors"],ans:2}
      ],
      short: [
        {q:"What are the key skills needed for reading comprehension? Explain with strategies.",a:"KEY READING COMPREHENSION SKILLS:\n\n1. IDENTIFYING MAIN IDEA:\n• Ask: What is the MOST IMPORTANT point of the whole passage?\n• Look for topic sentences (usually first sentence of paragraphs)\n• Strategy: After reading, ask 'What was this mainly about?'\n\n2. INFERENCE:\n• Reading 'between the lines' — what is implied but not stated\n• Use clues in the text + your own knowledge\n• Strategy: Ask 'What can I conclude from this information?'\n\n3. VOCABULARY IN CONTEXT:\n• Use surrounding words and sentences to guess meanings\n• Strategy: Read the sentence before and after the unfamiliar word\n\n4. SUMMARISING:\n• Identify main points without details\n• Strategy: Write one sentence per paragraph about its main idea\n\n5. IDENTIFYING TEXT TYPE AND PURPOSE:\n• Narrative (story), Expository (information), Persuasive (argument), Descriptive\n• Each type has different reading strategies\n\n6. ANSWERING PRECISELY:\n• Locate evidence in the text\n• Answer specifically — don't add unrelated information\n• Use the question's language in your answer when helpful\n\nSTRATEGIES:\n• Preview: Read title, headings, first/last sentences\n• Read actively: Ask questions while reading\n• Review: Check answers against the text"},
        {q:"How do you write a good summary of a passage? What should be included and excluded?",a:"WRITING A GOOD SUMMARY:\n\nWHAT TO INCLUDE:\n• The MAIN IDEA of the passage\n• KEY POINTS and arguments\n• IMPORTANT conclusions or findings\n• The topic and what the passage says about it\n\nWHAT TO EXCLUDE:\n• Minor details and examples\n• Repetition\n• Direct quotes (unless essential)\n• Your own opinions\n• Unimportant descriptive details\n\nSTEPS TO WRITE A SUMMARY:\n1. Read the passage carefully (at least twice)\n2. Identify the main idea of each paragraph (one sentence per para)\n3. Note key points only\n4. Write in YOUR OWN WORDS — don't copy directly\n5. Connect points logically\n6. Check: Is it much shorter than the original? Does it capture the main idea?\n\nFORMAT:\n• Length: Usually 1/3 or less of original\n• Tense: Present tense (usually)\n• Person: Third person\n• No quotation marks (own words)\n\nEXAMPLE:\nPassage about: Benefits of reading\nSummary: 'Reading regularly improves vocabulary, concentration and empathy. It reduces stress and enhances academic performance. Experts recommend reading at least 20 minutes daily for maximum benefit.'"}
      ],
      long: [
        {q:"Read this passage and answer all questions:\n\n'Plastic pollution has become one of the most pressing environmental challenges of our time. Every year, approximately 8 million tonnes of plastic enter our oceans, threatening marine life and ecosystems. Microplastics — tiny particles less than 5mm — have been found in the deepest ocean trenches and even in human blood. The consequences are devastating: marine animals mistake plastic for food, leading to starvation and death. Moreover, chemicals from plastics enter the food chain.\n\nHowever, solutions exist. Many countries have banned single-use plastics. Innovative scientists are developing biodegradable alternatives. Citizens can reduce, reuse and recycle. Collective action is our most powerful tool against this crisis.'\n\n(a) What is the main idea of the passage?\n(b) What are microplastics and why are they dangerous?\n(c) What solutions does the author suggest?\n(d) What is the tone of the passage?\n(e) Write a one-sentence summary of the whole passage.",a:"(a) MAIN IDEA:\nPlastic pollution is a serious environmental crisis that threatens marine life and human health, but solutions exist through government action, scientific innovation and individual responsibility.\n\n(b) MICROPLASTICS AND THEIR DANGER:\n• What: Microplastics are tiny plastic particles less than 5mm in size\n• Source: They come from the breakdown of larger plastic items\n• Danger: They have been found even in the deepest ocean trenches and in human blood, showing they have penetrated everywhere\n• They enter the food chain through marine animals that ingest them\n• Their presence in human blood suggests potential health risks\n• They carry chemicals that can be toxic to living organisms\n\n(c) SOLUTIONS SUGGESTED:\n1. Government action: Many countries have banned single-use plastics\n2. Scientific innovation: Scientists developing biodegradable alternatives to plastic\n3. Individual action: Citizens reducing, reusing and recycling plastic\n4. 'Collective action' — everyone working together is described as the most powerful tool\n\n(d) TONE OF THE PASSAGE:\n• The first paragraph has an ALARMING/CONCERNED tone — uses words like 'devastating', 'pressing', 'threatening'\n• The second paragraph shifts to a MORE HOPEFUL/OPTIMISTIC tone — 'solutions exist', 'powerful tool'\n• Overall: SERIOUS but CONSTRUCTIVE — acknowledges the crisis but ends on a positive, action-oriented note\n\n(e) ONE-SENTENCE SUMMARY:\n'Plastic pollution poses a devastating threat to oceans, marine life and human health, but through government bans, scientific innovation and individual action, it can be effectively addressed.'"}
      ],
      passage: [
        {q:"Read and practise comprehension strategies:\n\n'Anger is a normal human emotion. However, uncontrolled anger can harm both the person feeling it and those around them. When we feel angry, our heart rate increases and our body prepares for confrontation. Research shows that taking slow, deep breaths can calm this physical response within minutes. Other effective strategies include exercise, which releases endorphins, and talking to a trusted friend.'\n\n(a) What is the main idea? (Main idea question)\n(b) Why does our heart rate increase when angry? (Inference question)\n(c) What does 'uncontrolled anger' suggest about controlled anger? (Inference)\n(d) List three strategies mentioned for managing anger. (Specific detail)\n(e) Replace the underlined word with a synonym: 'effective strategies'.",a:"(a) MAIN IDEA (Main idea question):\nAlthough anger is a normal emotion, uncontrolled anger is harmful, but it can be managed through practical strategies like deep breathing, exercise and talking to someone.\n\nNote: The main idea includes BOTH the problem (uncontrolled anger is harmful) AND the solution (practical management strategies).\n\n(b) WHY HEART RATE INCREASES (Inference):\nThe text says 'our body prepares for confrontation' — the passage doesn't explicitly say why, but from this and general knowledge we can infer: The body's 'fight or flight' response is triggered by anger. The heart beats faster to pump more blood to muscles, preparing the body for physical action. This is a biological response to perceived threat or challenge.\n\n(c) WHAT 'UNCONTROLLED ANGER' SUGGESTS (Inference):\nIf uncontrolled anger is harmful, we can infer that CONTROLLED anger is acceptable or even normal. The word 'uncontrolled' implies that anger itself is not the problem — the lack of management is. Controlled anger (acknowledging and expressing it appropriately) would not cause harm. This also implies that anger CAN be controlled — it's not inevitable that anger will be destructive.\n\n(d) THREE STRATEGIES FOR MANAGING ANGER:\n1. Taking slow, deep breaths (calms physical response within minutes)\n2. Exercise (releases endorphins)\n3. Talking to a trusted friend\n\n(e) SYNONYM FOR 'effective strategies':\n• effective = useful, successful, powerful, productive, beneficial\n• strategies = methods, techniques, approaches, ways, solutions\n• Complete: 'useful methods' / 'successful techniques' / 'powerful approaches'"}
      ]
    },

    "Writing Skills": {
      mcq: [
        {q:"A formal letter begins with:",opts:["Dear Friend","Dear Sir/Madam or the recipient's name and designation","Hi there","Hello"],ans:1},
        {q:"The closing of a formal letter is:",opts:["With love","Yours truly / Yours faithfully / Yours sincerely","Bye","Best"],ans:1},
        {q:"In a formal letter, 'Yours faithfully' is used when:",opts:["You know the person's name","You don't know the person's name (Dear Sir/Madam)","Always","In informal letters"],ans:1},
        {q:"A paragraph should have:",opts:["Only one sentence","One main idea developed through several sentences","Multiple unrelated topics","No structure"],ans:1},
        {q:"A topic sentence in a paragraph:",opts:["Comes only at the end","States the main idea, usually at the beginning","Is always one word","Contains only examples"],ans:1},
        {q:"When writing a PERSUASIVE essay, you should:",opts:["Present only one side","Present and argue for a position using evidence and reasoning","Only describe","Tell a story"],ans:1},
        {q:"A NARRATIVE essay:",opts:["Gives information","Persuades the reader","Tells a story with characters, events and a sequence","Compares two things"],ans:2},
        {q:"In a DIARY ENTRY, the writing is:",opts:["Formal and impersonal","Personal, informal, from first person perspective","Academic and technical","Descriptive only"],ans:1},
        {q:"A NOTICE is written:",opts:["In paragraph form only","In a concise, clear format with heading, date and essential information","As a long essay","In poem form"],ans:1},
        {q:"When writing a STORY, the climax is:",opts:["The beginning","The end","The highest point of tension/conflict","The resolution"],ans:2},
        {q:"Active voice is generally preferred in writing because:",opts:["It is longer","It is clearer, more direct and more engaging","It is more formal","It uses fewer verbs"],ans:1},
        {q:"Cohesion in writing is achieved through:",opts:["Long sentences","Using connectors, pronouns and consistent tense — linking ideas smoothly","Short paragraphs","Repetition of words"],ans:1},
        {q:"A REPORT is different from an essay because:",opts:["Reports are shorter","Reports use headings, are factual, objective and structured for a specific purpose","Reports use more adjectives","Reports are always formal"],ans:1},
        {q:"When giving your OPINION in writing, you should:",opts:["State it as fact","Support it with reasons and evidence","Never give opinions","Only give opinions, no reasons"],ans:1},
        {q:"The purpose of an INTRODUCTION in an essay is to:",opts:["Summarise the essay","State the conclusion","Introduce the topic and the writer's approach/thesis","Provide all the evidence"],ans:2}
      ],
      short: [
        {q:"How do you write a formal letter? Describe the format and essential elements.",a:"FORMAT OF A FORMAL LETTER:\n\n1. SENDER'S ADDRESS (top right or left)\n   House No., Street\n   City, PIN Code\n   Date: DD/MM/YYYY\n\n2. RECEIVER'S ADDRESS (left side)\n   Name and Designation\n   Organisation\n   Address\n\n3. SUBJECT LINE (brief statement of purpose)\n   Subject: Complaint regarding ___\n\n4. SALUTATION\n   • Dear Sir/Madam (if you don't know the name)\n   • Dear Mr/Ms [Surname] (if you know the name)\n\n5. BODY\n   • Paragraph 1: Purpose of writing\n   • Paragraph 2: Main content/details\n   • Paragraph 3: Expected action/conclusion\n\n6. CLOSING\n   • 'Yours faithfully' (after Dear Sir/Madam)\n   • 'Yours sincerely' (after Dear Mr/Ms [Name])\n\n7. SIGNATURE\n   Name and designation (if applicable)\n\nKEY FEATURES:\n• Formal language — no slang or contractions\n• Clear, concise and polite\n• Factual and to the point\n• Properly structured paragraphs"},
        {q:"What is a paragraph? How do you write a well-structured paragraph?",a:"WHAT IS A PARAGRAPH:\nA paragraph is a group of related sentences that develop ONE main idea.\n\nSTRUCTURE OF A WELL-WRITTEN PARAGRAPH:\n\n1. TOPIC SENTENCE (usually first):\n• States the main idea of the paragraph\n• Tells the reader what the paragraph is about\n• Example: 'Regular exercise has numerous health benefits.'\n\n2. SUPPORTING SENTENCES:\n• Develop, explain, or give examples for the topic sentence\n• Each sentence adds information about the main idea\n• Use connectors: 'For example', 'Furthermore', 'In addition'\n• Example: 'For example, it strengthens the heart and improves circulation. Moreover, exercise releases endorphins which improve mood.'\n\n3. CONCLUDING SENTENCE (optional but recommended):\n• Summarises the paragraph or links to the next\n• Example: 'Clearly, incorporating exercise into daily life is essential for good health.'\n\nTIPS FOR GOOD PARAGRAPHS:\n• ONE idea per paragraph\n• 4-6 sentences usually\n• Use connectors for flow\n• All sentences must relate to the topic sentence\n• Avoid abrupt changes of topic within one paragraph"}
      ],
      long: [
        {q:"Write a formal letter to your school principal requesting permission to organise a Science Exhibition. Include: purpose, date, requirements, and expected benefits.",a:"SAMPLE FORMAL LETTER:\n\n[Your Name]\n[Class and Section]\n[School Name]\n[Date]\n\nThe Principal\n[School Name]\n[Address]\n\nSubject: Request for Permission to Organise a Science Exhibition\n\nRespected Sir/Madam,\n\nI, [Name], a student of Class X, respectfully write to seek your permission to organise an Inter-Class Science Exhibition on [proposed date], from 9:00 am to 1:00 pm, in the school hall.\n\nThe purpose of this exhibition is to encourage scientific thinking and practical application of concepts learned in class. Students from Classes IX and X will display working models, experiments and posters on topics such as renewable energy, environmental conservation and scientific inventions. Each class will contribute two to three projects.\n\nFor this purpose, we would require the use of the school hall, basic electrical connections, display tables and permission to use the science laboratory for preparation. We assure you that all safety precautions will be strictly observed.\n\nSuch an exhibition will benefit students by developing their research skills, creativity and confidence in public speaking. It will also provide a platform for students to explore science beyond the textbook.\n\nI request your kind permission and guidance to proceed with the arrangements. I shall be grateful for your support.\n\nYours sincerely,\n[Your Name]\nClass X, [Section]\n\nTEACHERS' NOTE: This letter demonstrates proper formal letter format, polite tone, clear purpose, practical details and a persuasive conclusion."}
      ],
      passage: [
        {q:"Read the following notice and answer the questions:\n\nNOTICE\nDATE: [Current Date]\n\nANNUAL SPORTS DAY\n\nAll students of Classes VI-X are hereby informed that the Annual Sports Day will be held on [Date] at the school ground. Events include: 100m race, relay race, long jump and tug of war.\n\nStudents interested in participating must register with their respective class teachers by [Date]. Proper sports kit is mandatory.\n\n[Principal's Name]\nPrincipal\n\n(a) What are the essential features of a notice?\n(b) Who is the notice addressed to?\n(c) What information is given in the notice?\n(d) How would a poster about the same event be different from a notice?",a:"(a) Essential features of a notice:\n1. HEADING: 'NOTICE' written clearly at the top\n2. DATE: When the notice is written\n3. TITLE: What the notice is about\n4. BODY: Essential information (who, what, when, where, how)\n5. CLOSING: Name and designation of the issuing authority\n6. FORMAT: Concise, clear, no unnecessary details\n7. Target audience clearly identified\n\n(b) The notice is addressed to:\nAll students of Classes VI to X of the school. The notice uses 'hereby informed' which is formal language for official announcements.\n\n(c) Information given in the notice:\n• Event: Annual Sports Day\n• Venue: School ground\n• Activities/Events: 100m race, relay race, long jump, tug of war\n• How to participate: Register with class teacher\n• Registration deadline: [Date]\n• Requirement: Proper sports kit is mandatory\n\n(d) Differences between a notice and a poster:\n\nNOTICE:\n• Purely informational — facts only\n• Formal language\n• No decorative elements\n• Brief and to the point\n• Official document format\n• Usually displayed on notice boards\n\nPOSTER:\n• Can include persuasive/exciting language ('Don't miss it!')\n• Visual design — colours, images, bold text, graphics\n• More creative and attractive\n• Aims to ATTRACT attention and generate interest\n• Can include slogans or motivational phrases\n• Displayed widely to reach maximum audience\n• Less formal, more engaging and eye-catching"}
      ]
    }
  }
};
