const ENGLISH_FF_QUESTIONS_DB = {
  "english_ff": {

    "A Letter to God": {
      mcq: [
        {q:"Where did Lencho and his family live?",opts:["In a town","In a valley on the crest of a low hill","Near a river bank","In a forest"],ans:1},
        {q:"What was Lencho expecting from the sky?",opts:["Snow","Wind","Rain — his fields needed water","Sunshine"],ans:2},
        {q:"How did Lencho describe the raindrops?",opts:["Like tears","Like silver arrows","Like new coins — big drops as ten cent pieces, small as fives","Like bullets"],ans:2},
        {q:"What happened to Lencho's crops in the hailstorm?",opts:["They were partially damaged","They were completely destroyed — not a leaf left on the trees","They survived","They improved after hail"],ans:1},
        {q:"To whom did Lencho write a letter?",opts:["The government","His neighbour","God","The post office"],ans:2},
        {q:"How much money did Lencho ask for in his letter?",opts:["50 pesos","100 pesos","200 pesos","75 pesos"],ans:1},
        {q:"Who found Lencho's letter at the post office?",opts:["A clerk","A postman","The postmaster","A mailman"],ans:2},
        {q:"Why did the postmaster not want to shake Lencho's faith in God?",opts:["He was afraid of God","He felt deeply moved — didn't want to break a man's faith","He was superstitious","He was ordered not to"],ans:1},
        {q:"How much money did the postmaster manage to collect to send to Lencho?",opts:["100 pesos","70 pesos","50 pesos","Exactly 100 pesos"],ans:1},
        {q:"What did Lencho do when he received only 70 pesos?",opts:["Thanked God","Wrote another angry letter to God saying the post office employees had stolen money","Accepted it quietly","Informed the police"],ans:1},
        {q:"What does Lencho's character show about his faith?",opts:["He was greedy","He had absolute, unshakeable faith in God","He was dishonest","He was practical"],ans:1},
        {q:"What is the irony in the story?",opts:["The hail destroyed crops","Lencho called God's helpers (post office workers who helped him) 'a bunch of crooks'","The money was lost","The letter reached God"],ans:1},
        {q:"What did Lencho compare the field to after the hailstorm?",opts:["A desert","A covered with salt (white hail)","A flood","A ruin"],ans:1},
        {q:"The theme of 'A Letter to God' is:",opts:["Dishonesty of government","Unshakeable faith and the irony of human nature","Love of nature","Importance of farming"],ans:1},
        {q:"What does the word 'solemn' mean as used in the story?",opts:["Joyful","Angry","Serious and dignified","Playful"],ans:2}
      ],
      short: [
        {q:"What kind of man was Lencho? What does his act of writing to God tell us?",a:"LENCHO'S CHARACTER:\n• A simple, hardworking farmer who toiled on his fields\n• Had unshakeable, childlike faith in God — absolute and innocent\n• Not educated or sophisticated\n• Honest in his own way — believed completely in divine justice\n\nWRITING TO GOD:\n• When his crops were completely destroyed by hail, Lencho was devastated\n• But instead of despairing, he sat down and wrote a letter to God asking for 100 pesos\n• This shows ABSOLUTE FAITH — he had no doubt that God would help him\n• It shows the simplicity and innocence of his belief\n• There was no question in his mind that God would NOT send the money\n\nHowever, the story has an irony — his faith was so strong that when he received only 70 pesos (postal workers had donated from their own pockets), he assumed the post office 'crooks' had stolen from God's letter, not suspecting that fellow humans had shown great kindness."},
        {q:"How did the postmaster react to Lencho's letter? What does this tell us about him?",a:"THE POSTMASTER'S REACTION:\n• When the postmaster read Lencho's letter addressed to God asking for 100 pesos, he was first amused\n• But then he became serious — he was deeply moved by Lencho's faith\n• He DID NOT want to shake Lencho's faith in God — felt it would be wrong to break such innocent belief\n\nACTION TAKEN:\n• Decided to answer the letter in God's name\n• Collected money from postal employees — giving part of his own salary\n• Also collected from friends\n• Could only gather 70 pesos — sent it to Lencho\n\nWHAT THIS TELLS US:\n• The postmaster was a compassionate, kind-hearted man\n• He had great respect for human faith\n• He went beyond his duty to protect a simple man's belief\n• He showed that humans can act as 'God's helpers'\n• There is a beautiful irony — the people Lencho called 'crooks' were actually the ones who helped him with great kindness"},
        {q:"What is the central irony in 'A Letter to God'?",a:"CENTRAL IRONY:\nThe greatest irony of the story is that Lencho, in his second letter to God, calls the very people who helped him — the post office employees — 'a bunch of crooks.'\n\nHOW THE IRONY WORKS:\n• Lencho needed 100 pesos to replant his crops\n• The postmaster, moved by his faith, collected money from his own salary and friends\n• They could only gather 70 pesos and sent it to Lencho\n• Lencho believed the money came directly from God\n• When he saw it was only 70 pesos, he DIDN'T doubt God — he assumed the post office workers had stolen 30 pesos\n• He wrote an angry second letter asking God to send the rest but NOT through the mail\n\nTHE IRONY:\n• The people Lencho called 'crooks' were actually people of great goodness\n• They sacrificed their own money to protect a stranger's faith\n• Lencho's faith in God was absolute but he had no faith in humans\n• The helpers became the villains in Lencho's eyes despite their selfless act"}
      ],
      long: [
        {q:"'A Letter to God' explores the themes of faith, irony and human goodness. Discuss.",a:"THEMES IN 'A LETTER TO GOD':\n\n1. FAITH:\n• Lencho's faith in God is the central theme — absolute, unquestioning, childlike\n• He believed with certainty that God would send money\n• His faith was so strong it protected him from despair after complete crop loss\n• His faith also blinded him to human goodness — he could only see God's hand, not human kindness\n\n2. IRONY:\n• IRONY 1: The people who helped Lencho are called 'crooks' by him\n• IRONY 2: The postal workers who showed genuine goodness receive insult for their kindness\n• IRONY 3: Lencho's faith in God was unshakeable but he had no faith in fellow humans\n• IRONY 4: The letter 'to God' was actually answered by ordinary humans\n\n3. HUMAN GOODNESS:\n• The postmaster and postal workers represent human compassion\n• They went beyond duty — donated their own money\n• They asked nothing in return — didn't even reveal who helped\n• They chose to be God's instruments on earth\n\n4. NATURE AND POVERTY:\n• The story shows the vulnerability of farmers dependent on weather\n• A single hailstorm can destroy a family's year of work and livelihood\n• The poor have no safety net except faith\n\nCONCLUSION: The story beautifully presents contrasting views of faith — Lencho's blind faith in God that misses human goodness, and the postmaster's practical compassion that becomes God-like in its selflessness."}
      ],
      passage: [
        {q:"Read the following extract:\n\n'Lencho showed not the slightest surprise on seeing the money; such was his confidence — but he became angry when he counted the money. God could not have made a mistake, nor could he have denied Lencho what he had requested. Immediately, Lencho went up to the window to ask for paper and ink. He went to the public table, and angrily wrote another letter.'\n\n(a) Why was Lencho not surprised to see the money?\n(b) Why did he become angry?\n(c) What did he write in his second letter?\n(d) What does this passage reveal about Lencho's character?",a:"(a) Lencho was not surprised because he had ABSOLUTE FAITH in God. He had written to God expecting help and he received it — to him, this was as natural and certain as the sun rising. His confidence in God was so complete that there was no room for surprise or doubt.\n\n(b) Lencho became angry when he counted the money and found only 70 pesos instead of the 100 he had asked for. He was NOT angry at God — he could not imagine God making a mistake. Instead, he concluded that someone had stolen 30 pesos from God's letter — which must have been the post office workers.\n\n(c) In his second letter to God, Lencho:\n• Mentioned he had received only 70 pesos\n• Said he needed the remaining 30 pesos urgently\n• Asked God to send the rest but NOT through the mail\n• Called the post office employees 'a bunch of crooks'\n\n(d) This passage reveals several things about Lencho's character:\n• His faith in God is absolute and unshakeable — cannot be challenged by facts\n• He is simple and unsophisticated — cannot imagine that humans could be kind without God's direct intervention\n• He has an ironic lack of faith in fellow human beings despite his complete faith in God\n• He is honest and direct — expresses his anger openly\n• He has a sense of justice — believes he deserves the full amount he requested"}
      ]
    },

    "Nelson Mandela: Long Walk to Freedom": {
      mcq: [
        {q:"The inauguration ceremony of Nelson Mandela took place at:",opts:["Cape Town","Johannesburg","Union Buildings amphitheatre in Pretoria","Durban"],ans:2},
        {q:"Nelson Mandela was the __ President of South Africa:",opts:["First","First black","Second","Third"],ans:1},
        {q:"The African National Congress (ANC) won how many seats in the first democratic elections?",opts:["200","252","300","400"],ans:1},
        {q:"Mandela describes the 10th of May 1994 as:",opts:["A sad day","An ordinary day","A day of deep pride and joy — the greatest of his life","A day of conflict"],ans:2},
        {q:"What did Mandela say would never happen again in South Africa?",opts:["Poverty","The oppression of one by another","War","Crime"],ans:1},
        {q:"According to Mandela, what is the 'greatest wealth' of South Africa?",opts:["Gold and diamonds","Its people — not its natural resources","Its land","Its climate"],ans:1},
        {q:"What is the 'twin obligations' Mandela mentions?",opts:["To family and country","To his family and to his people/country","To ANC and to government","To God and country"],ans:1},
        {q:"Apartheid is best described as:",opts:["A type of music","A policy of racial segregation and discrimination against non-whites in South Africa","A political party","A language"],ans:1},
        {q:"What did Mandela learn about courage from his father and the regent?",opts:["That courage is the absence of fear","That courage is not the absence of fear — it is to triumph over it","That courage is physical strength","That courage is always visible"],ans:1},
        {q:"According to Mandela, what produces both the freedom fighter AND the oppressor?",opts:["Education","Society","Apartheid","Same system — oppression dehumanises both"],ans:3},
        {q:"The word 'apartheid' means:",opts:["Unity","Equality","Separateness (Afrikaans)","Freedom"],ans:2},
        {q:"Mandela's heroes were initially the warriors of his tribe. Who were they?",opts:["Dingane and Bambatha","Shaka, Sechele, Moshoeshoe, Cetshwayo","Nelson and Washington","Mandela Sr. and King"],ans:1},
        {q:"What does Mandela say is the 'greatest glory' of humans?",opts:["Wealth","Power","Rising after falling — resilience","Education"],ans:2},
        {q:"The theme of 'Long Walk to Freedom' is:",opts:["War and violence","The struggle for freedom, dignity and equality","Cricket","Colonial rule"],ans:1},
        {q:"Mandela's autobiography is titled:",opts:["Freedom Walk","Long Road to Liberty","Long Walk to Freedom","Walk to Freedom"],ans:2}
      ],
      short: [
        {q:"Describe Mandela's feelings on the day of his inauguration as President.",a:"MANDELA'S FEELINGS ON INAUGURATION DAY:\n\n• The day (10th May 1994) dawned bright and clear\n• Mandela was besieged by dignitaries and world leaders — people from 140+ countries attended\n• He felt DEEP PRIDE — not just personal pride but pride for his people and nation\n• He felt a sense of history — understanding all the past suffering that had led to this moment\n• He described it as the greatest wealth of South Africa — not gold or diamonds but its PEOPLE\n• He stood at the place from where white supremacy was once proclaimed — now proclaiming a new democracy\n• He was proud that South Africa finally had a government that represented all its people\n• Military jets flew overhead — previously used for apartheid; now saluting the new President\n• He felt it was a common victory — for all South Africans regardless of colour\n• His speech said: 'Never, never again will this beautiful land experience the oppression of one by another'"},
        {q:"What does Mandela say about freedom? How did his understanding of freedom change?",a:"MANDELA'S EVOLVING UNDERSTANDING OF FREEDOM:\n\nCHILDHOOD FREEDOM:\n• As a boy, Mandela felt free — he ran in the fields, swam in streams\n• The freedom of a young man who had not yet discovered his identity was constrained\n• He did not understand the full nature of his freedom\n\nGROWING AWARENESS:\n• As a young man he became aware of his freedom being curtailed\n• He wanted freedom to stay out at night, read what he chose, go where he wished\n• These were the 'freedoms' of an individual\n\nFULL UNDERSTANDING:\n• Later he understood that his freedom was already taken — he was not free as a black man in apartheid South Africa\n• His hunger for freedom transformed: it was not just personal freedom but the freedom of ALL his people\n• He says: 'I was not born with a hunger to be free. I was born free...'\n• He realised that the oppressor is also not free — apartheid dehumanised whites too\n\nCONCLUSION:\nMandela's understanding expanded from personal freedom to collective freedom — the freedom of all South Africans, regardless of colour, to live with dignity and equality."},
        {q:"What twin obligations does Mandela talk about in this extract?",a:"MANDELA'S TWIN OBLIGATIONS:\n\nMandela says every man has twin obligations:\n\n1. OBLIGATION TO HIS FAMILY:\n• To his parents, to his wife and children\n• To support and care for family\n• This is a universal, personal obligation\n\n2. OBLIGATION TO HIS PEOPLE, HIS COMMUNITY AND HIS COUNTRY:\n• To work for the freedom and uplift of his community\n• To fight injustice\n• This is a civic/national obligation\n\nDILEMMA UNDER APARTHEID:\n• In a normal civil society, these two obligations can be fulfilled side by side\n• But under apartheid, fulfilling the SECOND obligation — fighting for his people's freedom — was ILLEGAL\n• A man who chose to fulfil his duty to his people was prevented from also fulfilling his duty to his family\n• This forced many ANC activists to choose between their family and their people's freedom\n• Mandela himself had to be away from his family, was imprisoned for 27 years — could not fulfil his family obligation while fighting for his people"}
      ],
      long: [
        {q:"What are the qualities that Mandela admires in the freedom fighters who inspired him? What does he learn about courage and freedom from them?",a:"MANDELA'S INSPIRATIONS AND LESSONS:\n\nEARLY HEROES:\n• Warriors and chiefs of his tribe — Dinuzulu, Bambatha, Moshoeshoe, Cetshwayo\n• He admired their bravery in fighting against colonial rule\n• As a boy, these were his heroes — men who had resisted white rule\n\nLESSO FROM HIS FATHER AND THE REGENT:\nCOURAGE:\n• 'The brave man is not he who does not feel afraid, but he who CONQUERS that fear'\n• Courage is not absence of fear — it is triumphing over it\n• This became fundamental to Mandela's approach to activism\n\nLESSON ON FREEDOM:\n• Mandela came to understand that oppression dehumanises BOTH the oppressed AND the oppressor\n• The system of apartheid made criminals of white men even as it victimised black men\n• True freedom requires freeing the oppressor too — not revenge but transformation\n• 'The oppressor must be liberated just as surely as the oppressed'\n\nKEY QUALITIES HE ADMIRED:\n1. Courage — to fight for justice despite fear\n2. Sacrifice — giving up personal comfort for the greater cause\n3. Resilience — the ability to rise after falling\n4. Dignity — maintaining self-respect under oppression\n5. Love for one's people — willing to die for their freedom\n\nMANDELA'S OWN APPLICATION:\n• These lessons sustained him through 27 years in prison\n• He emerged without bitterness — showing the transformation he believed in"}
      ],
      passage: [
        {q:"'I was not born with a hunger to be free. I was born free — free in every way that I could know. Free to run in the fields near my mother's hut, free to swim in the clear stream that ran through my village...It was only when I began to learn that my boyhood freedom was an illusion, when I discovered as a young man that my freedom had already been taken from me, that I began to hunger for it.'\n\n(a) What kinds of freedom did Mandela enjoy as a child?\n(b) What made him realize his freedom was an 'illusion'?\n(c) How did his hunger for freedom evolve?\n(d) What does Mandela mean when he says 'the oppressor must also be liberated'?",a:"(a) As a child, Mandela enjoyed:\n• Freedom to run in the fields near his mother's hut\n• Freedom to swim in clear streams of his village\n• Freedom to roast mealies under the stars\n• Freedom to ride on the broad backs of slow-moving bulls\n• The simple, physical freedom of a rural childhood — nature, movement, play, community\nThis was the freedom of innocence — not yet knowing what was being denied.\n\n(b) His freedom was an 'illusion' because:\n• As a young man he began to understand that apartheid laws denied him basic rights\n• He could not travel freely, could not vote, could not choose where to live\n• He could not read what he wished, stay out at night, or pursue his ambitions without restrictions\n• The 'freedom' of his childhood was real in a physical sense but the larger political and social freedom was absent\n• He realised that black South Africans were NOT free — they were systematically oppressed\n\n(c) His hunger for freedom evolved:\n• Initially he wanted personal freedom — to do what he wished\n• Then he understood his personal freedom was tied to the freedom of all black South Africans\n• His hunger broadened from personal desire to collective liberation\n• He came to understand that no one is truly free while others around them are oppressed\n\n(d) 'The oppressor must also be liberated' means:\n• Apartheid dehumanised white people too — it made them cruel, fearful and morally corrupt\n• A person who oppresses others loses their own humanity\n• True freedom means creating a society where ALL can live with dignity — black and white\n• Mandela's vision was NOT revenge but transformation of the entire society\n• Freeing the oppressed also means freeing the oppressor from the brutality of their own system"}
      ]
    },

    "Two Stories about Flying": {
      mcq: [
        {q:"In 'His First Flight', why was the young seagull afraid to fly?",opts:["His wings were injured","He was afraid of the vast expanse of sea below — felt certain wings wouldn't support him","His parents didn't teach him","The weather was bad"],ans:1},
        {q:"How did the seagull's mother tempt him to fly?",opts:["She pushed him off","She held a piece of fish just out of his reach — he dived for it and instinctively flew","She called him gently","She flew beside him"],ans:1},
        {q:"What happened when the young seagull finally flew?",opts:["He crashed into the sea","His wings spread and he soared — his fear vanished as he flew","He cried out in fear","He turned back"],ans:1},
        {q:"In 'Black Aeroplane', the pilot was flying to:",opts:["France","England (London)","India","USA"],ans:1},
        {q:"What was the narrator's dream as he flew over France?",opts:["Seeing Paris","A big breakfast — eggs, bacon and coffee","Meeting his family","Winning a prize"],ans:1},
        {q:"What did the pilot see when he entered the storm clouds?",opts:["Clear sky","Another black aeroplane with no lights flying alongside","Rescue helicopter","Birds"],ans:1},
        {q:"What was strange about the mysterious aeroplane?",opts:["It was very fast","It had no lights, no radio and the pilot's face was not visible","It was very large","It carried no passengers"],ans:1},
        {q:"The mysterious pilot guided the lost pilot to safety by:",opts:["Using radio","Signalling with lights","Flying ahead and leading him out of the clouds to safety","Dropping a map"],ans:2},
        {q:"When the narrator searched for information about the mysterious plane, what did he find?",opts:["It was a military plane","The control room had only seen one plane — his — in that area","It belonged to another airline","It was a training plane"],ans:1},
        {q:"The theme of 'His First Flight' is:",opts:["The beauty of nature","Overcoming fear through courage — conquering self-doubt","Adventure","Family love"],ans:1},
        {q:"What does the mysterious black aeroplane symbolise in the second story?",opts:["Danger","An unseen force of help — possibly divine or mysterious","Technology","The pilot's imagination"],ans:1},
        {q:"In the first story, what happened to the seagull after 24 hours of hunger?",opts:["He accepted food","He flew away","He grew weaker but still afraid","He jumped into sea"],ans:2},
        {q:"The seagull conquered his fear when:",opts:["His parents praised him","His hunger made him mad with temptation — he dived without thinking","He watched his siblings fly","Night fell"],ans:1},
        {q:"What was the narrator's feeling after being guided to safety?",opts:["Anger","Gratitude and mystery — he searched for the mysterious pilot","Relief only","Excitement"],ans:1},
        {q:"The first story 'His First Flight' was written by:",opts:["Gavin Maxwell","Liam O'Flaherty","Frederick Forsyth","Anne Frank"],ans:1}
      ],
      short: [
        {q:"How does the young seagull overcome his fear? What is the lesson for readers?",a:"HOW THE SEAGULL OVERCAME FEAR:\n\nTHE SITUATION:\n• The young seagull was alone on the ledge — all siblings had flown\n• He was starving — hadn't eaten for 24 hours\n• His family taunted him from across the cliff — calling him a coward\n\nTHE TEMPTATION:\n• His mother tore at a piece of fish and flew towards him\n• She stopped just short of the ledge — holding the morsel tantalizingly close\n• The seagull was maddened with hunger — he could not resist\n• Without thinking about fear, he DIVED at the fish\n\nTHE MIRACLE OF FLIGHT:\n• As soon as he dived, his wings spread instinctively\n• He felt the wind under him — lifting him\n• He soared, then landed on the green sea\n• His entire family joined him, calling out in joy\n\nLESSON FOR READERS:\n1. FEAR IS OVERCOME BY ACTION — thinking about fear makes it worse; doing overcomes it\n2. HUNGER (DESIRE) CAN OVERCOME FEAR — a strong enough motivation conquers paralysing fear\n3. ABILITIES WE DOUBT ARE OFTEN ALREADY WITHIN US — the seagull could always fly; he just needed to try\n4. FAMILY SUPPORT MATTERS — parents created situation that forced him past his fear\n5. THE FIRST STEP IS THE HARDEST — once he took that one dive, everything followed naturally"},
        {q:"Describe the strange experience of the pilot in 'Black Aeroplane'. What could be the explanation?",a:"THE PILOT'S STRANGE EXPERIENCE:\n\nSITUATION:\n• Pilot flying from France to England over the Channel\n• Entered storm clouds despite knowing he should have gone around\n• Lost visibility, compass spinning, couldn't see stars, running out of fuel (only enough for 5-10 minutes)\n• In despair, about to give up\n\nSTRANGE ENCOUNTER:\n• Suddenly saw a black aeroplane alongside — in the storm\n• The plane had NO LIGHTS\n• The pilot's face was not visible in the dark\n• No radio contact possible (radio dead in storm)\n• The mysterious pilot signalled: follow me\n\nRESCUE:\n• Pilot followed the black plane through dark clouds\n• It led him through safely — suddenly came out on clear runway with lights\n• The pilot landed safely\n\nAFTERMATH:\n• When pilot asked control room about the other plane — NO ONE had seen any plane in that area\n• Only ONE aircraft was on their radar — the narrator's\n\nPOSSIBLE EXPLANATIONS:\n1. SUPERNATURAL: A guardian angel or divine help — the plane was not real\n2. HALLUCINATION: The pilot was stressed and oxygen-deprived — imagined the plane\n3. MYSTERY: The story leaves it deliberately ambiguous — unexplained\n4. SYMBOLIC: The 'black aeroplane' represents the unknown forces that guide us when we are lost\n\nTHEME: The story explores faith, mystery, and the possibility of help from unknown sources in moments of crisis."}
      ],
      long: [
        {q:"Compare and contrast the two stories 'His First Flight' and 'Black Aeroplane'. What common theme do they share?",a:"COMPARISON OF THE TWO STORIES:\n\n'HIS FIRST FLIGHT' — STORY 1:\n• Character: A young seagull — not yet experienced flight\n• Problem: Fear of flying — psychological barrier\n• Setting: Sea cliffs, natural environment\n• Resolution: Natural instinct triggered by hunger — overcomes fear naturally\n• Helper: Mother seagull — uses strategy to tempt him\n• Tone: Warm, hopeful, coming-of-age\n• Realistic — this happens in nature\n\n'BLACK AEROPLANE' — STORY 2:\n• Character: An adult human pilot — experienced but in crisis\n• Problem: Lost in storm, running out of fuel, facing death\n• Setting: Storm clouds over English Channel\n• Resolution: Mysterious guidance by an unknown plane\n• Helper: Unknown, mysterious, possibly supernatural\n• Tone: Mysterious, suspenseful, thought-provoking\n• Ambiguous — could be real or imagined\n\nCOMMON THEMES:\n1. OVERCOMING FEAR: Both characters face a crisis of fear — the seagull afraid of flight, the pilot afraid of dying in the storm\n2. HELP FROM UNEXPECTED SOURCES: Seagull helped by mother's strategy; pilot helped by mysterious unknown plane\n3. COURAGE AND TRUST: Both must overcome doubt and trust — the seagull trusts instinct; pilot trusts the mysterious guide\n4. TRANSFORMATION: Both are changed by their experience — seagull becomes a flyer; pilot has a mysterious experience he cannot explain\n5. SURVIVAL AND TRIUMPH: Both survive their crises\n\nCONCLUSION: The two stories together suggest that life's challenges (fear, crisis) can be overcome — sometimes through finding courage within ourselves (seagull), sometimes through mysterious help from outside (pilot)."}
      ],
      passage: [
        {q:"Read the extract from 'His First Flight':\n\n'His mother was coming towards him with food in her beak... He leaned out eagerly. She was just opposite him now... he looked at the food in her beak and cried to her... She swooped past him, almost touching his beak with the fish and flew away from him again. Maddened by hunger, he jumped off the ledge.'\n\n(a) Why did the mother not give the food directly to the seagull?\n(b) What happened after he jumped off the ledge?\n(c) What lesson does this teach us about overcoming fear?\n(d) How does this incident reflect the relationship between parent and child?",a:"(a) The mother did not give food directly because she was DELIBERATELY TEMPTING him — using hunger as a strategy to force him to fly. She came close enough to tantalize him but not close enough for him to reach without moving. She swept the fish past his beak and flew away — frustrating and infuriating him with hunger until the temptation overcame his fear. She understood that direct help would keep him on the ledge forever — he needed to fly on his own.\n\n(b) After he jumped off the ledge:\n• He fell downward initially — his heart stood still with terror\n• Then his wings spread outward — instinctively, naturally\n• He felt the wind rushing against his breast, lifting him up\n• He soared — higher and higher into the blue sky\n• He floated on air, curved his wings, glided, and eventually landed on the green sea surface\n• His whole family screamed with joy and flew around him\n\n(c) Lessons about overcoming fear:\n• Sometimes the only way to overcome fear is to TAKE THE LEAP — thinking only makes fear worse\n• When we are forced into action, natural abilities emerge that we didn't know we had\n• Desire and motivation (hunger) can overcome paralysing fear\n• The ability was always there — he just needed to discover it through action\n• 'Just do it' is sometimes the only solution to fear\n\n(d) The parent-child relationship reflected:\n• The mother appears to be withholding food — seems cruel but is actually wise and loving\n• Great parenting sometimes means NOT giving direct help — but creating conditions for the child to discover their own abilities\n• The mother knew her child could fly — she just needed to make him realise it\n• This reflects the universal parenting challenge: when to help and when to step back and let the child find their own strength\n• The joy of the whole family at his success shows the love that was behind the apparently harsh strategy"}
      ]
    },

    "From the Diary of Anne Frank": {
      mcq: [
        {q:"Anne Frank was a:",opts:["German girl","Dutch Jewish girl who hid from Nazis","French politician","Dutch writer"],ans:1},
        {q:"Anne Frank's diary was given to her on her:",opts:["Twelfth birthday","Thirteenth birthday","Fourteenth birthday","Fifteenth birthday"],ans:1},
        {q:"For how long did Anne Frank write her diary?",opts:["1 year","About 2 years (June 1942 to August 1944)","6 months","3 years"],ans:1},
        {q:"Why was Anne Frank's father the only survivor of the group?",opts:["He escaped","He was not hiding with them","He was not Jewish","He survived the concentration camps while others didn't"],ans:3},
        {q:"Anne died of:",opts:["Starvation","Typhus (in Bergen-Belsen concentration camp)","Gas chamber","Gunshot"],ans:1},
        {q:"What did Anne say about the reasons for her writing the diary?",opts:["To publish it","She had no one to confide in — the diary was her friend Kitty","Her mother asked her to","School assignment"],ans:1},
        {q:"Anne's best friend in school was:",opts:["Lies Goosens","Jopie de Waal","Her sister Margot","Nobody"],ans:1},
        {q:"According to Anne, why did she not trust anyone her age?",opts:["They were not smart","She could never confide without risk of talk spreading","They were German","They didn't like her"],ans:1},
        {q:"What is the name Anne gave to her diary?",opts:["Diary","Kitty","Book of Memories","Secret Friend"],ans:1},
        {q:"Anne Frank's diary was originally written in:",opts:["German","English","Dutch","French"],ans:2},
        {q:"What does Anne say about the difference between inner self and outer self?",opts:["They are the same","They are completely different — outer self is cheerful; inner self is serious and sensitive","Only outer self matters","She had no inner self"],ans:1},
        {q:"The diary has been translated into how many languages approximately?",opts:["10","30","70+","5"],ans:2},
        {q:"Anne's family moved to Amsterdam because:",opts:["Business opportunity","Nazis had gained power in Germany — they fled","War ended","Family invitation"],ans:1},
        {q:"The family went into hiding in:",opts:["A bomb shelter","Hidden rooms in Otto Frank's office building","A neighbour's house","A church"],ans:1},
        {q:"What is the significance of Anne Frank's diary historically?",opts:["It is a novel","It provides intimate record of daily life under Nazi occupation — document of Holocaust","It describes WWII battles","It is a political manifesto"],ans:1}
      ],
      short: [
        {q:"Why did Anne Frank start writing a diary? What did the diary mean to her?",a:"WHY ANNE STARTED WRITING:\n• The diary was a gift for her 13th birthday (June 12, 1942)\n• Anne felt she had no real friends she could confide in\n• She wanted to write everything down — but needed a real friend, not just facts in a diary\n• She named the diary 'Kitty' and wrote to it as letters to a dear friend\n\nWHAT THE DIARY MEANT TO HER:\n• The diary was her CONFIDANT — she told it everything she couldn't tell anyone else\n• She says: 'Paper has more patience than people'\n• She could express her inner thoughts, fears, dreams and feelings freely in the diary\n• It was her only outlet for a serious, sensitive inner self that she hid from the world\n• She had a 'lighter, superficial' public self and a 'deeper, truer' inner self — only the diary knew both\n• The diary became her most trusted companion during the frightening years of hiding\n\nSIGNIFICANCE:\n• The diary became one of the most powerful documents of the Holocaust\n• Her father published it after the war — it has been read by millions worldwide\n• It gives a human, personal, intimate account of what it meant to be Jewish under Nazi persecution"},
        {q:"What do we learn about Anne Frank's character from the extract about her schooldays?",a:"ANNE FRANK'S CHARACTER:\n\nSEEMINGLY CONTRADICTORY NATURE:\n• Outer self: Cheerful, funny, light-hearted — making friends laugh\n• Inner self: Serious, sensitive, thoughtful — the real Anne\n\nSOCIAL LIFE:\n• Popular — had a large circle of friends and admirers\n• Not particularly close to anyone — friendly but not deeply bonded\n• Felt that despite many friends, she had no true confidant\n\nINTELLECTUAL QUALITIES:\n• Observant — notices details about people\n• Thoughtful — reflects on her own nature and behaviour\n• Mature beyond her years — understands the complexity of relationships\n\nLONELINESS BENEATH POPULARITY:\n• She had 'loving family, affectionate aunts, good friends' — apparently not alone\n• Yet she felt a deep loneliness — couldn't share her real inner self\n• Feared that if she confided, talk would spread — so kept inner thoughts private\n• This led her to the diary\n\nSELF-AWARENESS:\n• She clearly distinguishes between who she appears to be and who she truly is\n• This psychological insight is remarkable for a 13-year-old\n• Shows why her diary became so profoundly insightful and lasting"}
      ],
      long: [
        {q:"Anne Frank says: 'Paper has more patience than people.' Explain this statement in the context of the diary.",a:"'PAPER HAS MORE PATIENCE THAN PEOPLE':\n\nCONTEXT OF THE STATEMENT:\n• Anne made this observation when explaining why she started writing a diary\n• She felt she couldn't confide in people — not even those close to her\n• The diary offered something people couldn't: unconditional, non-judgmental listening\n\nMEANING:\n1. PAPER NEVER INTERRUPTS: When you write to paper, it doesn't cut you off, change the subject, or offer unsolicited advice\n2. PAPER NEVER JUDGES: Writing allows complete honesty — no fear of being misunderstood or judged\n3. PAPER NEVER GOSSIPS: Anne feared that if she confided in people, her secrets would spread — paper kept all secrets\n4. PAPER IS ALWAYS AVAILABLE: Human beings have moods, problems, busy times — paper is always there\n5. PAPER ALLOWS COMPLETE EXPRESSION: You can write all thoughts without social censorship\n\nWHY ANNE FELT THIS:\n• Despite having many friends, loving parents and siblings, she felt no one could be her true confidant\n• Teenage loneliness — even surrounded by people — is a universal experience\n• Under the extreme stress of hiding from Nazis, normal outlets were denied\n• The diary became her psychological survival tool\n\nBROADER SIGNIFICANCE:\n• This single observation resonated with millions of readers worldwide\n• Many people keep journals/diaries for exactly this reason\n• Writing is therapeutic — allows processing of emotions that cannot be shared verbally\n• Anne's diary, kept for herself, became a gift to the world — showing that 'paper' can indeed be more patient and lasting than any human conversation"}
      ],
      passage: [
        {q:"'I want to write, but more than that, I want to bring out all kinds of things that lie buried deep in my heart...I have a notion that paper is more patient than people. I can recapture everything when I write, my thoughts, my ideals and my fantasies.'\n\n(a) Why does Anne want to write?\n(b) What does 'bring out all kinds of things that lie buried deep in my heart' mean?\n(c) What is the significance of Anne's diary for the world?\n(d) Why is Anne's diary considered a document of Holocaust history?",a:"(a) Anne wants to write for several reasons:\n• She had a deep inner world — thoughts, feelings, dreams that she couldn't express to anyone\n• She had no real confidant — no one she could completely trust with her innermost feelings\n• She found that paper 'had more patience than people' — allowed unlimited, non-judgmental expression\n• Writing was her way of making sense of her experiences, fears and hopes\n• She wanted to express not just events but her deeper self — her ideals and fantasies\n\n(b) 'Bring out all kinds of things that lie buried deep in my heart' means:\n• Anne had a rich inner life that was hidden from others — her true feelings, fears, desires\n• Outer Anne was cheerful, popular, seemingly carefree — this was not the whole truth\n• Inner Anne was serious, sensitive, frightened, thoughtful, full of questions\n• Writing the diary was a way of excavating and expressing this hidden inner world\n• It was emotional and psychological release — like therapy\n\n(c) Significance of Anne's diary for the world:\n• Translated into 70+ languages, read by millions — one of world's most widely read books\n• Shows the Holocaust through the intimate, personal lens of a child victim\n• Made abstract history concrete and human — gave individual face to millions who suffered\n• Inspired discussions about tolerance, anti-Semitism, human rights and dignity\n• Showed remarkable psychological insight and literary quality for a 13-year-old\n• Became a symbol of resilience and the human spirit\n\n(d) Why it is a Holocaust document:\n• It chronicles life under Nazi occupation — daily life in hiding from 1942-1944\n• Describes the fear, restrictions, dangers of being Jewish under Nazis\n• Provides intimate record of how persecution affected ordinary families\n• Documents the systematic dehumanisation of Jews\n• The diary ends — and Anne's fate — IS the Holocaust story made personal\n• Combined with Otto Frank's account of what happened after, it shows the full horror"}
      ]
    },

    "Glimpses of India": {
      mcq: [
        {q:"'A Baker from Goa' is about:",opts:["A modern baker","The traditional Portuguese-era baker (pader) who still exists in Goa","A French baker","A bread factory"],ans:1},
        {q:"What is the Goan baker called?",opts:["Pader","Naan wala","Rotiwalah","Baker sahib"],ans:0},
        {q:"How was the baker's arrival announced?",opts:["A bell","A whistle","The thud and jingle of his bamboo staff — 'jhang, jhang' sound","A horn"],ans:2},
        {q:"What did children love from the baker?",opts:["Cakes","Bread-bangles and sweet bread","Chocolate","Biscuits"],ans:1},
        {q:"'Coorg' is set in which state of India?",opts:["Tamil Nadu","Goa","Karnataka","Kerala"],ans:2},
        {q:"Coorg is described as the land of:",opts:["Rice and coconut","Rolling hills and coffee plantations","Tea and spice","Gold and sandalwood"],ans:1},
        {q:"The Coorg people trace their descent from:",opts:["Portuguese soldiers","Arab or Alexander the Great's army (Greek origin suggested)","Mongols","British soldiers"],ans:1},
        {q:"What is the river that originates in Coorg?",opts:["Krishna","Cauvery (Kaveri)","Godavari","Tungabhadra"],ans:1},
        {q:"'Tea from Assam' is about:",opts:["Tea farming in Darjeeling","A train journey through Assam and the first flush tea harvest","A factory tour","Tea auction"],ans:1},
        {q:"What is 'first flush' tea?",opts:["Last harvest","The first spring leaves — best quality tea","Tea mixed with milk","Red tea"],ans:1},
        {q:"According to legend, who discovered tea?",opts:["A British officer","An Indian king","A Chinese emperor Shen Nong (dried leaves fell in boiling water)","A Japanese monk"],ans:2},
        {q:"The Coorg people are known for their:",opts:["Mathematics","Hospitality and martial tradition","Architecture","Music"],ans:1},
        {q:"Which river originates from the Brahmagiri hills of Coorg?",opts:["Krishna","Sharavathi","Kaveri","Tungabhadra"],ans:2},
        {q:"In 'A Baker from Goa', what happened to the father?",opts:["He moved abroad","The father may not be alive but the son carries on the family profession","He retired","He changed profession"],ans:1},
        {q:"Coorg is approximately located at what altitude?",opts:["Sea level","900-1600 metres above sea level","300 metres","3000 metres"],ans:1}
      ],
      short: [
        {q:"What picture of Goa's baking tradition is presented in 'A Baker from Goa'?",a:"GOA'S BAKING TRADITION:\n\nPORTUGUESE LEGACY:\n• The baking tradition is a remnant of Portuguese colonial rule in Goa\n• Elders nostalgically remember the Portuguese and their famous loaves\n• The Portuguese may have gone but the bakers (paders) remain\n\nTHE BAKER'S ROLE:\n• Called 'pader' in Goa\n• Used to come TWICE a day — morning selling round, afternoon return\n• Announced arrival with 'jhang, jhang' sound of bamboo staff\n• Children would wake up at the sound and run to meet him\n• Loaves for adults, bread-bangles for children\n\nCOMMUNITY IMPORTANCE:\n• He was 'friend, companion and guide' during childhood\n• The bread was essential for marriages, feasts and all celebrations\n• 'The baker's furnace is as useful as a priest or a goldsmith'\n• A family without bread was not a 'proper' family\n\nTRADITION CONTINUES:\n• Old furnaces still exist — fire not extinguished\n• If the father is not alive, the son carries on the tradition\n• Baker wears distinctive clothes — a kabai (long frock reaching knee)\n• The tradition represents cultural continuity — connecting present Goa to its Portuguese past"},
        {q:"Describe Coorg and its people as presented in 'Coorg'.",a:"COORG (KODAGU):\n\nLOCATION AND LANDSCAPE:\n• Southernmost district of Karnataka, between Mysore and the coast\n• 900-1600 metres altitude in the Western Ghats\n• Misty mountains, evergreen forests, exotic wildlife\n• Coffee plantations and rolling hills\n• Origin of River Kaveri (Cauvery) from Brahmagiri hills\n\nTHE PEOPLE (KODAVAS/COORGS):\n• Believed to be of Greek or Arab descent (Alexander's army)\n• Wear a distinctive long black coat with embroidered waist (kuppia)\n• Known for FIERCELY INDEPENDENT NATURE and MARTIAL TRADITION\n• The only community allowed to carry firearms without licence historically\n• Famous for their hospitality — legend says visitors are treated like gods\n• Many achieve high military ranks — notable Generals from Coorg\n\nPHYSICAL ATTRIBUTES:\n• Known for physical courage and strength\n• The Kodava people's 'martial tradition' — famous soldiers\n• Field Marshal K.M. Cariappa and General Thimayya were from Coorg\n\nNATURE AND WILDLIFE:\n• Wildlife — elephants, tigers, leopards, birds\n• Nisargadhama river island — popular eco-tourism spot\n• Nagarhole National Park nearby\n• Coffee and spice plantations create lush green landscape"},
        {q:"What does 'Tea from Assam' tell us about tea cultivation and the legend of tea's discovery?",a:"TEA FROM ASSAM:\n\nTEA CULTIVATION IN ASSAM:\n• Assam is India's largest tea-producing region\n• Brahmaputra valley provides perfect conditions — heavy rainfall, warm climate\n• Two main harvests: first flush (spring — best quality), second flush (richer, more popular)\n• Tea estates are vast — green fields stretching as far as eye can see\n\nTEA PICKING:\n• 'Only Two Leaves and a Bud' — pickers select only the finest young shoots\n• Mainly women pickers with baskets\n• Long hours of work in the fields\n• The two characters Pranjol and Rajvir observe this on their train journey\n\nLEGEND OF TEA'S DISCOVERY:\n• A Chinese emperor, Shen Nong, was boiling water under a tree\n• Dried leaves from the tree fell into the water\n• The resulting drink was refreshing — tea was discovered\n• Another legend: Buddhist monk Bodhidharma cut off his eyelids to stay awake during meditation; where they fell, tea plants grew\n\nINDIA'S TEA INDUSTRY:\n• India produces and exports vast amounts of tea\n• Assam tea is known worldwide\n• Second most consumed drink in world after water"}
      ],
      long: [
        {q:"How do the three pieces in 'Glimpses of India' present a rich picture of India's cultural diversity?",a:"GLIMPSES OF INDIA — CULTURAL TAPESTRY:\n\nA BAKER FROM GOA — WEST COAST:\n• Shows the Portuguese colonial legacy living on in a vibrant tradition\n• Demonstrates how colonialism left cultural imprints that became part of Indian identity\n• The baker (pader) is a social institution — not just a trader but a community member\n• Shows the rich Goan culture blending Indian and European elements\n• The nostalgia, the sensory details (smell of bread, jhang jhang sound) create a vivid local portrait\n\nCOORG — SOUTH:\n• Shows India's physical diversity — misty mountains, coffee plantations, wild rivers\n• Highlights a community with unique origins, customs and traditions\n• Demonstrates India's martial heritage — Kodava community's military traditions\n• Shows how communities maintain distinct identities within the Indian nation\n• The origin myths (Greek/Arab descent) show India's ancient connections to the wider world\n\nTEA FROM ASSAM — NORTHEAST:\n• Introduces a completely different India — vast tea estates, Brahmaputra valley\n• Shows an industry that transformed a region and connects India to global commerce\n• The legend of tea's discovery connects the local to the global\n• Shows the labour behind a product consumed worldwide — the pickers\n\nUNIFYING THEME:\n• Despite different regions, communities and histories — all show India's richness\n• All three celebrate local traditions and identities\n• Together they suggest that India's greatness lies in its diversity\n• Each 'glimpse' is a window into a whole world — showing how vast and varied India truly is"}
      ],
      passage: [
        {q:"'Our elders are often heard reminiscing nostalgically about those good old Portuguese days, the Portuguese and their famous loaves of bread. Those eaters of loaves might have vanished but the makers are still there. We still have amongst us the mixers, the moulders and those who bake the loaves.'\n\n(a) What is meant by 'those eaters of loaves might have vanished'?\n(b) What does it mean that 'the makers are still there'?\n(c) What does this paragraph tell us about cultural continuity?\n(d) What role does the baker play in Goan society beyond just selling bread?",a:"(a) 'Those eaters of loaves might have vanished' means the Portuguese colonisers who ruled Goa and who made bread-eating a part of Goan culture have gone — Goa is no longer a Portuguese colony (it became part of India in 1961). The Portuguese people and their direct colonial presence has ended.\n\n(b) 'The makers are still there' means the bakers (paders) — the Goan bread-making community — continue their tradition. Though the Portuguese who brought and popularised bread have gone, the local craftsmen who learned the art of bread-making have continued it, passing the skill from father to son. The tradition lives on through the local community.\n\n(c) This paragraph tells us about cultural continuity:\n• Culture can outlive the people who originally brought it\n• Local communities adopt, adapt and preserve foreign traditions — making them their own\n• The baking tradition became part of Goan identity even after the Portuguese left\n• Continuity is maintained through craft skills passed down families\n• Old furnaces, old tools, old sounds (the bamboo's jhang jhang) — all continue\n• This shows that culture is resilient — it survives political changes and transfers of power\n\n(d) The baker's role in Goan society beyond selling bread:\n• He was a 'friend, companion and guide' to children — a beloved daily visitor\n• His arrival was an event — children would run to meet him\n• He was essential for celebrations — no marriage or feast was complete without his bread\n• 'A baker's furnace was as important as a priest or a goldsmith'\n• He connected homes to each other through his daily rounds\n• He was a keeper of tradition — his presence was a link to the past\n• He was a community institution, not merely a commercial vendor"}
      ]
    },

    "Mijbil the Otter": {
      mcq: [
        {q:"Who is the author of 'Mijbil the Otter'?",opts:["Gerald Durrell","Gavin Maxwell","Liam O'Flaherty","R.K. Narayan"],ans:1},
        {q:"Where did the author get Mij the otter?",opts:["From a pet shop","In Basra, Iraq — given by a friend","From Tigris marshes (southern Iraq)","From Scotland"],ans:2},
        {q:"What was Mij's reaction to water when he was first introduced to the bathtub?",opts:["He was afraid of water","He went wild with joy — played for 20 minutes","He ignored it","He drank it"],ans:1},
        {q:"What was the name of the new species of otter discovered?",opts:["Lutrinae Maxwell","Lutrogale perspicillata maxwelli","Mij otterus","Gavin otter"],ans:1},
        {q:"How did the author transport Mij from Basra to London?",opts:["Ship","By train","By airplane — in a confined box","By car"],ans:2},
        {q:"What happened to Mij in the aircraft box during the journey?",opts:["He slept peacefully","He broke out of the box and caused chaos in the aircraft","He was quiet","He was sick"],ans:1},
        {q:"What did Mij invent as a game with a rubber ball?",opts:["Catch","He pushed the ball up the suitcase slope and caught it at the bottom","Football","Swimming with ball"],ans:1},
        {q:"How did Londoners react when they saw Mij?",opts:["With fear","With curiosity and interest — many thought he was a baby seal, squirrel or hippo","With indifference","They ran away"],ans:1},
        {q:"What does 'Mij' stand for?",opts:["The author's nickname","Short for Mijbil — the otter's name","A species name","An Arabic word"],ans:1},
        {q:"The author describes Mij's species as found in the marshes near:",opts:["London","Cairo","Basra, Iraq","Delhi"],ans:2},
        {q:"What do we learn about otters from this chapter?",opts:["They are dangerous","They are playful, intelligent animals that love water and can form bonds with humans","They are shy animals","They cannot be tamed"],ans:1},
        {q:"What was Mij's favourite 'toy' to play with?",opts:["Rubber mouse","A rubber ball and marbles","A rope","Sticks"],ans:1},
        {q:"The author had to keep Mij in the box during the flight because:",opts:["Airline rules required it","Mij was ill","Security concerns","Mij was dangerous"],ans:0},
        {q:"Where did the author live with Mij in London?",opts:["In the countryside","In a flat in London","In a zoo","In Scotland initially then London"],ans:1},
        {q:"What is the message of 'Mijbil the Otter'?",opts:["Wild animals should stay wild","Humans and wild animals can form meaningful bonds — bond between man and animal","Animals are dangerous","Never keep pets"],ans:1}
      ],
      short: [
        {q:"How did Mij the otter adapt to his new environment? Describe his personality.",a:"MIJ'S ADAPTATION AND PERSONALITY:\n\nINITIAL PERIOD:\n• Mij arrived in Basra — spent first 24 hours hiding behind suitcases\n• On the second day: began to investigate the room, then the author\n• Third day: completely at home — exploring everywhere with intense curiosity\n\nLOVE OF WATER:\n• First reaction to bathtub: 'went wild with joy' — 20 minutes of frantic play\n• Would demand access to the bath by tugging and whimpering\n• Later in London: Would turn on taps himself!\n\nPLAYFULNESS AND INTELLIGENCE:\n• Invented his own marble game — pushing marbles along the floorboards\n• Invented ball game — pushing rubber ball up suitcase slope, catching it at bottom\n• These games showed remarkable creative intelligence\n• He could discover how things worked and create his own entertainment\n\nINTELLIGENCE IN PUBLIC:\n• Londoners couldn't identify him — guesses ranged from 'baby seal' to 'hippo' to 'squirrel'\n• He walked on a lead — drawing crowds of curious people\n• He had his own route to the park — would insist on his preferred path\n\nBOND WITH AUTHOR:\n• Followed the author everywhere\n• Slept curled up by his side\n• His distinctive personality — playful, curious, demanding — was fully individual"},
        {q:"Describe the traumatic journey of Mij from Basra to London.",a:"THE JOURNEY (Basra to London):\n\nPREPARATION:\n• Airline rules required Mij to travel in a box\n• Author had a box made — with breathing holes and wire mesh floor\n• An hour before flight: put Mij in box\n\nTHE DISASTER:\n• When author opened the box before flight: Mij had demolished the lining\n• The box was full of blood, torn lining, and Mij was in terrible state\n• Had damaged himself trying to escape — bleeding from nose\n• Had to take him out, clean him up, reassemble box contents\n• Author was late for flight — rushed to airport\n\nDURING FLIGHT:\n• Put box at his feet in aircraft\n• Suddenly felt 'sharp claws' on his leg — Mij had escaped from box!\n• People screaming in the aircraft — chaos\n• Mij rampaging through the aircraft\n• Sympathetic woman offered to help — eventually caught Mij\n\nAFTER THE JOURNEY:\n• Mij spent rest of flight inside author's jacket — tucked away, finally calm\n• The entire ordeal showed Mij's determination not to be confined\n• Also showed the author's devotion — he endured everything\n\nLESSON: The challenges of bringing a wild animal into a human world — regulations, logistics and the animal's own needs all clash."}
      ],
      long: [
        {q:"What does 'Mijbil the Otter' tell us about the relationship between humans and animals? What qualities of Mij does the author admire?",a:"HUMAN-ANIMAL RELATIONSHIP IN 'MIJBIL THE OTTER':\n\nFORMATION OF BOND:\n• Initially Mij hid — shy and frightened\n• Gradually he explored and accepted the author\n• Over days, a genuine mutual affection developed\n• Neither forced — both gradually opened to each other\n\nQUALITIES OF MIJ THE AUTHOR ADMIRES:\n1. INTELLIGENCE: Mij invented his own games — marble game, ball game; could figure out how things worked (tap handles)\n2. PLAYFULNESS: Boundless energy and joy in play — bath time was ecstasy\n3. CURIOSITY: Explored everything in his environment with intense interest\n4. INDIVIDUALITY: He had his own preferences, routines, favourite routes — a distinct personality\n5. LOYALTY: Followed the author everywhere, slept beside him\n6. ADAPTABILITY: Moved from Iraqi marshes to London flat — adapted to both\n\nWHAT THE RELATIONSHIP SHOWS:\n1. ANIMALS HAVE RICH INNER LIVES: Mij showed play, creativity, preference, affection — not just instinct\n2. GENUINE BONDS ARE POSSIBLE: Not master-pet but genuine companionship\n3. WILD ANIMALS RETAIN THEIR NATURE: Even domesticated, Mij was always partly wild — the confinement in the box showed this\n4. RESPONSIBILITY: Keeping a wild animal requires enormous commitment and adaptation from the human\n5. ENRICHMENT: The relationship enriched both — Mij was safe and loved; author had unique companionship\n\nCONCLUSION: The story celebrates the possibility of cross-species friendship based on respect, patience and love — while also acknowledging the complexity of bringing wild animals into human worlds."}
      ],
      passage: [
        {q:"'Maxwell had found that otters belonging to this species were especially intelligent and playful. He observed Mij's behaviour carefully and came to believe that otter intelligence was not generally recognised by humans.'\n\n(a) What evidence does the author give of Mij's intelligence?\n(b) How did people in London react to Mij?\n(c) What does it mean when the author says otter intelligence is 'not generally recognised'?\n(d) What do we learn about wild animals from this chapter?",a:"(a) Evidence of Mij's intelligence:\n• He invented his OWN marble game — pushing marbles along groove between floorboards; different from playing with marbles as humans would\n• He invented a rubber ball game — pushing it to the top of a suitcase slope and catching it at the bottom, repeating endlessly\n• He learned to turn on bath taps — figured out the mechanism himself\n• He had his own preferred route to the park in London and would insist on it\n• He adapted from Iraqi marshes to a London flat — showing behavioural flexibility\n\n(b) London people's reaction to Mij:\n• Great curiosity — he was an unusual sight on London streets\n• Many people tried to identify him — with creative guesses\n• One person called him 'a baby seal'; another 'a squirrel'; another suggested 'a hippo'; another 'a bear cub'\n• Children were fascinated\n• People would stop and stare or ask questions\n• His unusual appearance and behaviour drew attention everywhere he went\n• People were curious but not frightened — showing urban tolerance\n\n(c) 'Otter intelligence not generally recognised' means:\n• Most people think of otters simply as water animals or 'cute' creatures\n• They don't appreciate that otters have complex cognitive abilities — creativity, problem-solving, invention\n• Science and popular knowledge underestimate otter mental capacity\n• Maxwell, through close observation, came to see Mij as highly intelligent — going beyond what is generally understood about the species\n\n(d) What we learn about wild animals:\n• Wild animals have rich inner lives with individual personalities, preferences and creative abilities\n• They can form genuine bonds with humans when treated with respect and patience\n• Wild animals retain their fundamental nature even in domesticated settings — Mij's desperate escape from the box showed this\n• Caring for wild animals requires understanding their specific needs (Mij needed water constantly)\n• Animals communicate through behaviour — if we observe carefully, we can understand them\n• Keeping wild animals is complex — raises ethical questions about confining creatures meant to be free"}
      ]
    },

    "Madam Rides the Bus": {
      mcq: [
        {q:"What was Valli's full name?",opts:["Valliammal","Valliammai","Vallikannu","Valliyammal"],ans:1},
        {q:"How old was Valli?",opts:["Six","Seven","Eight","Ten"],ans:2},
        {q:"What was Valli's favourite pastime?",opts:["Reading","Playing games","Standing in the doorway watching the street","Going to the market"],ans:2},
        {q:"How much was the one-way bus fare to the town?",opts:["25 paise","30 paise","50 paise","10 paise"],ans:1},
        {q:"How did Valli save money for the bus fare?",opts:["Borrowed from friend","Saved from snacks, toys and rides — through careful control of small temptations","Took from mother's purse","Earned by working"],ans:1},
        {q:"What was Valli's reaction when the conductor called her 'madam'?",opts:["She was offended","She was delighted and puffed up with pride","She was embarrassed","She ignored it"],ans:1},
        {q:"What sight on the way to town first excited Valli?",opts:["A mountain","A young cow running in front of the bus","The sea","Other vehicles"],ans:1},
        {q:"What happened to the young cow that Valli saw on the way to town?",opts:["It was still running","It had grown up","On the return journey, she saw it lying dead by the road","It got into a field"],ans:2},
        {q:"What emotion did Valli feel when she saw the dead cow?",opts:["Happiness","Indifference","Deep sadness and sadness about life's impermanence","Fear"],ans:2},
        {q:"Did Valli get off the bus and explore the town?",opts:["Yes, she explored for an hour","Yes, she had tea","No, she stayed in the bus and rode back","Yes, she met friends"],ans:2},
        {q:"Why didn't Valli get off the bus at the town?",opts:["She was afraid","She had no money left for the return journey and didn't want to spend on drinks","She wasn't interested","She had to return home early"],ans:1},
        {q:"What did Valli think of the conductor's offer of a cold drink?",opts:["She accepted gratefully","She refused politely","She refused with the dignity of not accepting charity","She wanted it but refused to spend money"],ans:2},
        {q:"What did Valli do when the conductor asked if her mother knew where she was?",opts:["Said yes","Said no honestly","Smiled mysteriously — keeping her secret","She cried"],ans:2},
        {q:"The story 'Madam Rides the Bus' is written by:",opts:["R.K. Laxman","Ruskin Bond","Vallikannan (Tamil author)","Premchand"],ans:2},
        {q:"What is the central theme of 'Madam Rides the Bus'?",opts:["The importance of buses","A child's desire for independence and the bittersweet lesson about life and death","Family conflict","Urban vs rural life"],ans:1}
      ],
      short: [
        {q:"How did Valli plan and execute her bus journey? What does this tell us about her character?",a:"VALLI'S PLANNING AND EXECUTION:\n\nHOW SHE FOUND OUT:\n• Valli overheard adults talking and asked careful questions\n• Found out: Bus fare = 30 paise one way; 45-minute journey; bus went at 11:30 am and returned at 2:45 pm\n• This gave her a complete plan — she could return before her mother woke from afternoon nap\n\nSAVING MONEY:\n• She resisted all her childish temptations — no snacks, no rides at the fair, no toys\n• Carefully saved every small coin\n• Took many months to save 60 paise (return fare)\n\nEXECUTION:\n• Waited for the right opportunity — mother's afternoon nap\n• Walked to the bus stop\n• Got on the bus confidently and paid her fare\n\nCHARACTER REVEALED:\n1. INDEPENDENCE AND DETERMINATION: She planned everything herself without help\n2. SELF-DISCIPLINE: Saved money by resisting temptations — remarkable for a child\n3. RESOURCEFULNESS: Used observation and questions to gather all needed information\n4. COURAGE: Got on the bus alone at age 8\n5. INTELLIGENCE: Thought through all logistics including return journey timing\n6. PRIDE: Would not accept charity (refused cool drink)"},
        {q:"What was the impact of seeing the dead cow on Valli? How does it change her mood?",a:"THE IMPACT OF THE DEAD COW:\n\nON THE WAY TO TOWN:\n• Valli had seen a young cow running ahead of the bus — playful, excited, energetic\n• She had laughed — found it funny and charming\n• It was a moment of pure childhood joy\n\nON THE RETURN JOURNEY:\n• The same road — but now a different sight\n• The cow was lying dead by the roadside — apparently struck by another vehicle\n• Its legs were in the air, blood on its mouth\n\nVALLI'S REACTION:\n• Felt a sudden sadness\n• The earlier happiness and excitement was completely gone\n• She did not want to look at the canal or palmyra trees anymore — all the earlier excitement had disappeared\n• She found life 'suddenly sad'\n\nSIGNIFICANCE:\n• The dead cow represents Valli's first encounter with death and mortality\n• The contrast between the living, playful cow and the dead one is stark\n• It teaches her (and us) that life is fragile — what was full of life can suddenly be gone\n• Her childhood innocence is touched by this knowledge\n• The story ends on this note — the bus journey of adventure becomes tinged with sadness\n• A coming-of-age moment — she gains wisdom about life's impermanence that she cannot share even with her mother"},
        {q:"How does Valli assert her independence throughout the story?",a:"VALLI'S ASSERTION OF INDEPENDENCE:\n\n1. SECRET PLANNING:\n• She planned the entire trip without telling anyone — complete independence from adults\n• She kept her secret through the whole conversation with her mother at the end\n\n2. REFUSING 'MADAM':\n• When called 'madam' she didn't deny it — she embraced it with dignity\n• But she also asserted she was NOT an old lady when the conductor joked\n\n3. REFUSING THE COOL DRINK:\n• When conductor offered a free drink — she refused\n• 'I don't have the money for that' — she was independent even in refusing charity\n• Her pride and self-respect would not allow her to accept something she hadn't paid for\n\n4. NOT GETTING OFF AT THE TOWN:\n• She didn't explore the town despite the excitement of arrival\n• She knew she had no money left and would not be a burden or ask for help\n• Made the mature decision to stay on the bus for the return journey\n\n5. KEEPING HER SECRET:\n• At the end, when mother and aunt discuss what children could possibly know — Valli's smile is her secret\n• She had done something amazing but kept it entirely to herself\n• Her independence was complete — she needed no acknowledgement from adults"}
      ],
      long: [
        {q:"'Madam Rides the Bus' is a story about a child's growth and the bittersweet nature of gaining experience. Discuss.",a:"GROWTH AND EXPERIENCE IN 'MADAM RIDES THE BUS':\n\nTHE CHILD AT THE START:\n• Valli is a curious, spirited 8-year-old with a limited world\n• Her 'window' is literally the doorway of her house\n• She longs for independence and adventure\n• Her greatest desire: to ride the bus to the town\n\nTHE JOURNEY AS SYMBOL:\n• The bus journey represents Valli's journey from childhood to greater awareness\n• She goes out into the world — sees new things, has new experiences\n• The journey is both literal and metaphorical\n\nWHAT SHE GAINS:\n1. ACHIEVEMENT: She planned and executed her dream independently — confidence\n2. EXPERIENCE OF THE WORLD: Saw things she had only imagined\n3. KNOWLEDGE: Learned about grown-up interactions (conductors, passengers)\n4. PRIDE: She was 'madam' — treated as a capable person\n\nTHE BITTERSWEET LESSON:\n• The dead cow changes everything\n• Life's fragility and impermanence enters her consciousness\n• The playful cow was alive and then dead — without warning\n• This knowledge cannot be unlearned — she has grown up a little\n\nTHE END — SECRETS AND MATURITY:\n• She keeps her adventure secret even from her mother\n• Her mysterious smile at the end shows new maturity\n• She has experienced something that has changed her — but she processes it privately\n\nCONCLUSION: The story captures the universal moment when childhood ends and a young person first truly understands that life includes death, and that the world is larger, more complicated and more beautiful than any doorway can show."}
      ],
      passage: [
        {q:"'On the way home, she was once again very excited. But suddenly the conductor called out, \"Look there!\" A young cow had wandered into the middle of the road... The bus slowed down, the cow moved finally, but then Valli saw the cow was not the same one she had seen before — it was lying dead.'\n\n(a) Why was Valli excited on the way home?\n(b) How did seeing the dead cow affect Valli?\n(c) What is the significance of the contrast between the two scenes involving the cow?\n(d) What does Valli's silence at the end of the journey suggest?",a:"(a) On the way home, Valli was excited because:\n• She had successfully completed her first bus journey and was returning home\n• She was anticipating the return trip along the same beautiful road\n• She had had a wonderful adventure — felt proud and happy\n• She was looking forward to seeing the sights she had enjoyed on the outward journey\n• The entire trip had been a great success in her eyes\n\n(b) Seeing the dead cow affected Valli deeply:\n• Her excitement and happiness completely vanished\n• She felt sudden, deep sadness\n• The sight of the blood on the dead cow's mouth was shocking\n• She no longer wanted to look out at the things she had enjoyed earlier\n• She found life 'suddenly, strangely sad'\n• She didn't respond when the conductor tried to cheer her up\n• Her mood shifted from joy to quiet melancholy for the rest of the journey\n\n(c) Significance of the contrast between the two scenes:\n• On the outward journey: the cow was young, playful, running freely — symbol of life, energy, joy\n• On the return: same cow (perhaps) was lying dead — stark symbol of death's suddenness\n• The contrast represents the most fundamental truth of existence: life and death\n• It mirrors Valli's own journey — she went out full of excitement (like the living cow) and returns with new, sobering knowledge\n• The contrast shows how quickly and unexpectedly life can end\n• It was Valli's first real encounter with mortality — a turning point in her young life\n\n(d) Valli's silence at the end suggests:\n• She is processing a profound experience that she cannot easily articulate\n• She has gained wisdom that separates her somewhat from her innocent self\n• She keeps her secret — both about the trip and about what she experienced\n• Her mysterious smile when her mother and aunt talk about 'what children know' suggests she knows something they don't — she has experienced something real and significant\n• She has grown up slightly — the silence is the silence of maturity, not childhood ignorance\n• She doesn't share because some experiences are private — this itself is a sign of growing up"}
      ]
    },

    "The Sermon at Benares": {
      mcq: [
        {q:"Gautama Buddha was born as a prince in:",opts:["600 BC","563 BC","500 BC","483 BC"],ans:1},
        {q:"What event changed Siddhartha Gautama's life at age 25?",opts:["Seeing a beautiful garden","Seeing an old man, a sick man, a corpse and a monk — confronting suffering","A dream","His father's death"],ans:1},
        {q:"Kisa Gotami came to Buddha because:",opts:["She wanted wisdom","Her only son had died and she sought medicine to revive him","She was ill","She wanted to become a monk"],ans:1},
        {q:"What did Buddha ask Kisa Gotami to bring him?",opts:["Flowers","Gold","A handful of mustard seeds from a house where NO one had died","Water from a river"],ans:2},
        {q:"Why could Kisa Gotami not find the mustard seeds?",opts:["No one had mustard seeds","Every house she visited had experienced death — the condition could not be fulfilled","She forgot where to look","People refused to give"],ans:1},
        {q:"What did Kisa Gotami finally understand?",opts:["Medicine could revive the dead","Death is universal — no family is untouched by it","Buddha had failed her","She should pray more"],ans:1},
        {q:"What did Kisa Gotami do after she understood the truth?",opts:["She cried forever","She became a Buddhist nun","She forgot her son","She blamed Buddha"],ans:1},
        {q:"Buddha's teaching about grief is:",opts:["Never grieve","Grief is a sign of weakness","Grief is natural but clinging to it is suffering — the wise find peace","Always express grief"],ans:2},
        {q:"The 'Sermon at Benares' was Buddha's:",opts:["First sermon","Last sermon","Most famous sermon on the truth of suffering","Sermon to kings"],ans:0},
        {q:"What does Buddha compare humans who are affected by grief to?",opts:["Leaves in wind","A mountain — unmoved","A sleepy man who won't wash himself to get clean","A drowning man"],ans:2},
        {q:"Buddha says those who have found peace are:",opts:["Those who have no grief","Those who have conquered grief — free from suffering","Those who have wealth","Those who are young"],ans:1},
        {q:"The story of Kisa Gotami teaches:",opts:["Death can be cured","Universal brotherhood","Acceptance of mortality — death is the common human experience","Medical science is limited"],ans:2},
        {q:"What is the central message of 'The Sermon at Benares'?",opts:["Death is punishment","Suffering is universal and impermanence is reality — seek peace not endless grief","Religion cures all","Mustard seeds are sacred"],ans:1},
        {q:"Buddha was first known as:",opts:["Buddha","Kisa Gotami","Prince Siddhartha Gautama","Devadatta"],ans:2},
        {q:"The 'Enlightened One' is another name for:",opts:["Mahavira","Kisa Gotami","Gautama Buddha","Brahma"],ans:2}
      ],
      short: [
        {q:"Summarise the story of Kisa Gotami and the mustard seeds. What lesson does it teach?",a:"KISA GOTAMI AND THE MUSTARD SEEDS:\n\nTHE GRIEF:\n• Kisa Gotami's only son died\n• In her grief, she refused to accept his death\n• Carried the dead child from house to house seeking medicine to revive him\n• People thought she had lost her mind\n\nTHE TASK GIVEN BY BUDDHA:\n• Someone directed her to Gautama Buddha\n• Buddha listened compassionately and said: 'Fetch me a handful of mustard seeds'\n• Condition: The seeds must come from a house where NO ONE has ever died\n\nTHE SEARCH:\n• Kisa Gotami went from house to house with hope\n• Every house said: 'Yes, we have mustard seeds' — but then: 'Many have died in our house'\n• She could not find a single house untouched by death\n• Gradually she realised — death had visited every family\n\nTHE REALISATION:\n• She understood that she was not alone in her grief\n• Death is universal — it spares no one\n• She left her son in the forest and returned to Buddha\n• She became a Buddhist nun — devoted to the path of understanding suffering\n\nLESSON:\n1. IMPERMANENCE: Death is universal and inevitable — no one is spared\n2. ACCEPTANCE: Grief is natural but clinging to the dead brings only more suffering\n3. UNIVERSALITY OF SUFFERING: Recognising that all humans suffer loss brings compassion and perspective\n4. PATH TO PEACE: Understanding reality — not fighting it — leads to peace"},
        {q:"What are Buddha's teachings about grief and suffering in 'The Sermon at Benares'?",a:"BUDDHA'S TEACHINGS ON GRIEF AND SUFFERING:\n\n1. SUFFERING IS UNIVERSAL:\n• 'The life of mortals in this world is troubled and brief and combined with pain'\n• All humans experience old age, disease and death\n• No one lives forever\n\n2. GRIEF IS INEVITABLE BUT CLINGING IS SUFFERING:\n• Grief when we lose loved ones is natural\n• But clinging to grief — refusing to accept loss — only adds to suffering\n• 'He who seeks peace should draw out the arrow of lamentation'\n\n3. THE WISE ACCEPT IMPERMANENCE:\n• Those who understand that death is natural find peace\n• The unwise are 'like a sleeping village' overcome by floods they didn't see coming\n\n4. COMPASSIONATE PERSPECTIVE:\n• Recognising that ALL humans suffer makes our own grief more bearable\n• We are not alone — community of suffering creates compassion\n\n5. PEACE IS POSSIBLE:\n• Those who have 'drawn out the lamentation' — accepted loss — find peace\n• They are 'free from pain' and 'blessed'\n\n6. PATH TO WISDOM:\n• The Kisa Gotami story shows the method — not argument but EXPERIENCE\n• Going through the search herself, she learned what no lecture could teach\n• True wisdom comes from lived understanding, not just intellectual knowledge"}
      ],
      long: [
        {q:"How does Buddha teach Kisa Gotami? What is unique about his teaching method?",a:"BUDDHA'S UNIQUE TEACHING METHOD:\n\nTRADITIONAL TEACHING vs BUDDHA'S APPROACH:\nTraditional: Tell the truth directly — 'Your son is dead. Death is universal. Accept it.'\nBuddha's: Give a task that leads to the DISCOVERY of truth through experience.\n\nTHE METHOD — SOCRATIC/EXPERIENTIAL:\n1. He listened to Kisa Gotami with compassion — didn't dismiss her grief\n2. He gave hope: 'I can help you — bring mustard seeds'\n3. The condition was impossible (seeds from death-free house) but she had to DISCOVER this herself\n4. Through her own search, she encountered grief in every household\n5. She arrived at the truth through EXPERIENCE not through being told\n\nWHY THIS METHOD WORKS:\n1. SHE WAS READY ONLY AFTER HER OWN DISCOVERY: Telling her directly would have been rejected — she was too deep in grief to hear reason\n2. EXPERIENCE TEACHES DEEPLY: What we discover ourselves stays with us; what we're told is forgotten\n3. COMPASSION NOT REJECTION: By engaging with her grief rather than dismissing it, Buddha showed respect\n4. COMMUNITY HEALING: She met other grieving families — this itself was healing — realising she was not alone\n5. UNIVERSAL TRUTH PERSONALISED: She didn't learn an abstract truth — she FELT it in her own heart\n\nRESULT:\n• Kisa Gotami achieved what no lecture could give — genuine understanding and acceptance\n• She became a Buddhist nun — the grief transformed into wisdom\n• She taught others the same truth she had learned\n\nLESSON FOR EDUCATORS:\nThe best teaching creates conditions for students to discover truth themselves — not simply delivering information."}
      ],
      passage: [
        {q:"'She went to him and cried, \"Lord and master, give me the medicine that will cure my boy.\" So Buddha said, \"Fetch me a handful of mustard seed.\" And when the girl in her joy promised to procure it, Buddha added, \"The mustard seed must be taken from a house where no son, husband, parent, or slave has died.\"'\n\n(a) Why did Buddha add the condition about the mustard seeds?\n(b) What does Kisa Gotami discover during her search?\n(c) What is the significance of the phrase 'in her joy'?\n(d) How does this story show Buddha's compassion and wisdom?",a:"(a) Buddha added the condition because:\n• He knew that an impossible condition would lead Kisa Gotami to the truth through her own experience\n• A house where NO ONE had died does not exist — she would find this out herself\n• Telling her directly that 'death is universal' would not reach her grief-stricken mind\n• The search itself would be the teaching — she would encounter grieving families everywhere\n• By going through each house, she would feel the universality of suffering in her own heart\n• This experiential method is far more powerful than direct instruction\n\n(b) During her search, Kisa Gotami discovers:\n• Every house she visits has experienced death — parents, children, servants, spouses\n• Not a single house has been untouched by loss\n• Death is universal — it spares no family, no community\n• She was not uniquely cursed — her suffering was the common human experience\n• Through this discovery, she gradually shifts from denial and desperate hope to understanding and acceptance\n• She leaves her son in the forest (accepting he is truly dead) and returns to Buddha for wisdom\n\n(c) Significance of 'in her joy':\n• Kisa Gotami was joyful because she believed Buddha had given her HOPE — a remedy for her son\n• She thought mustard seeds could cure death — showing how deep her denial was\n• This phrase highlights the contrast between her beginning (desperate hope, denial of death) and her end (acceptance, wisdom)\n• It also shows her pitiful state — she was so grief-stricken that she clung to any hope, however impossible\n• The joy was misplaced but understandable — this makes her character deeply sympathetic\n\n(d) Buddha's compassion and wisdom shown:\n• COMPASSION: He did not say 'Your son is dead, accept it' — he received her kindly\n• He gave her hope and a task rather than crushing her grief with logic\n• He understood she needed to come to truth in her own time and way\n• WISDOM: He knew that experience teaches what words cannot\n• He crafted a task that would lead her to universal truth through personal discovery\n• He transformed her grief into a path to wisdom — her suffering became her teacher\n• The result: not just a healed Kisa Gotami but one who could help others — she became a teacher of this truth"}
      ]
    },

    "The Proposal": {
      mcq: [
        {q:"'The Proposal' is a play by:",opts:["William Shakespeare","Anton Chekhov","George Bernard Shaw","Oscar Wilde"],ans:1},
        {q:"Who are the main characters in 'The Proposal'?",opts:["Romeo and Juliet","Lomov, Natalya and Chubukov","Hamlet and Ophelia","Valli and conductor"],ans:1},
        {q:"What is Ivan Vassilevitch Lomov's purpose in visiting Chubukov?",opts:["To buy land","To propose marriage to Natalya","To discuss farming","To return borrowed money"],ans:1},
        {q:"What starts the first quarrel between Lomov and Natalya?",opts:["Money","Natalya's cooking","Ownership of Oxen Meadows","Lomov's age"],ans:2},
        {q:"Both sides claim Oxen Meadows belong to them for how long?",opts:["10 years","50 years","About 300 years (Lomov) vs generations (Chubukov)","100 years"],ans:2},
        {q:"What starts the second quarrel?",opts:["Marriage proposal","Whose dog is better — Guess (Lomov's) vs Squeezer (Chubukov's)","Land dispute again","Money matters"],ans:1},
        {q:"Why does Lomov keep visiting despite the quarrels?",opts:["He loves fighting","He loves Natalya and wants to marry her","He wants the land","He is bored"],ans:1},
        {q:"What is Lomov's physical condition throughout the play?",opts:["He is perfectly healthy","He is ill — heart palpitations, goes numb, twitches, is hypochondriac","He is old and tired","He is injured"],ans:1},
        {q:"What does Natalya do when she finds out Lomov came to propose?",opts:["She was happy already","She demands her father bring him back immediately","She refuses to meet him","She locks herself in room"],ans:1},
        {q:"How does the play end?",opts:["They break off forever","Lomov and Natalya get engaged despite ongoing quarrel about dogs","Marriage is cancelled","Chubukov throws Lomov out"],ans:1},
        {q:"'The Proposal' is best described as:",opts:["A tragedy","A comedy about human foolishness in quarrelling over trivial things while missing what matters","A romantic drama","A historical play"],ans:1},
        {q:"Chekhov uses this play to satirise:",opts:["The Russian government","Human tendency to quarrel over trivialities while neglecting important matters (love, marriage)","Upper class wealth","Theatre itself"],ans:1},
        {q:"How old is Lomov?",opts:["25","30","35 (he mentions his age)","40"],ans:2},
        {q:"What does Chubukov call Lomov during their quarrel?",opts:["Foolish young man","Intriguer, milksop, stuffed sausage, blind hen","Thief and liar","Sir"],ans:1},
        {q:"The play is a one-act play. One-act play means:",opts:["It has one actor","It takes place in one location and has one continuous action (no act breaks)","It lasts one hour","It has one scene"],ans:1}
      ],
      short: [
        {q:"What are the two quarrels in 'The Proposal'? How do they arise?",a:"FIRST QUARREL — OXEN MEADOWS:\n• Lomov came to propose to Natalya\n• But somehow the conversation moved to Oxen Meadows — a piece of land\n• Lomov says it belongs to him — borders his Birchwoods\n• Natalya insists it belongs to her family — they have used it for 300 years\n• Chubukov joins and takes his daughter's side\n• The quarrel escalates — insults fly, Lomov has heart attack symptoms and leaves\n• Purpose forgotten entirely — proposal never delivered\n\nSECOND QUARREL — DOGS:\n• After Chubukov tells Natalya that Lomov came to propose, she frantically calls him back\n• The proposal finally begins — but conversation somehow moves to Lomov's dog Guess\n• Natalya says her dog Squeezer is better\n• Lomov says Guess is pedigree and better\n• Both argue: 'Mine is younger, faster, better bred, better hunter'\n• Chubukov again takes daughter's side\n• More insults, Lomov faints\n• Second quarrel: petty, trivial, ridiculous\n\nIRONY:\nBoth quarrels are over completely trivial matters. Meanwhile, the very serious matter of marriage — Natalya's future, Lomov's loneliness — is completely forgotten in the heat of petty argument."},
        {q:"What do we learn about the character of Lomov, Natalya and Chubukov from the play?",a:"CHARACTER ANALYSIS:\n\nLOMOV:\n• Hypochondriac — constantly complaining about heart palpitations, numb legs, twitching\n• Indecisive — needed great effort to finally come to propose\n• Quarrelsome — gets drawn into arguments despite coming with peaceful purpose\n• Proud — won't back down on petty matters\n• Genuine need for marriage — lonely, approaching 35, recognises he needs a partner\n• Comical — his symptoms appear and disappear conveniently during arguments\n\nNATALYA:\n• Practical — focused on land and her dog's qualities\n• Dramatic — immediately wants Lomov back when she learns he came to propose\n• Equally quarrelsome — gets drawn into trivial arguments\n• Unsentimental — not romantic but pragmatic about marriage\n• Fiercely competitive — will not concede on Squeezer vs Guess debate\n• Somewhat comical in her sudden change when she learns of the proposal\n\nCHUBUKOV:\n• Takes his daughter's side in all arguments (even when she's wrong)\n• Calls Lomov names — 'stuffed sausage', 'milksop', 'intriguer'\n• But desperately wants the marriage to happen — Lomov is good catch\n• Hypocritical — insults Lomov and then immediately embraces him\n• Comical — blesses the couple even as they start arguing about the dogs again"},
        {q:"What is the theme and purpose of 'The Proposal'? How does Chekhov use humour?",a:"THEME:\n1. HUMAN FOLLY: People quarrel over trivial matters (land, dogs) while ignoring what truly matters (love, companionship, life's goals)\n2. SOCIAL SATIRE: Chekhov satirises the Russian landowning class — preoccupied with property, status and petty pride\n3. IRONY: The play is full of irony — a marriage proposal that never gets properly made because of fights about trivialities\n4. HUMAN NATURE: We are all capable of losing sight of important things when pride is involved\n\nHOW CHEKHOV USES HUMOUR:\n1. SITUATION COMEDY: The gap between intention (marriage proposal) and outcome (constant quarrelling) creates sustained comedy\n2. CHARACTER COMEDY: Lomov's hypochondria is funny — symptoms appear and disappear\n3. ESCALATION: Each argument escalates beyond reason — small dispute becomes full war\n4. REVERSAL: Natalya's instant change when she learns of the proposal is comically abrupt\n5. INSULTS: The creative insults (stuffed sausage, milksop) are funny in their excess\n6. ENDING: Even as the couple is 'officially' engaged, they immediately resume arguing about the dogs — suggesting nothing will change\n\nPURPOSE:\nChekhov shows us that human beings often create their own difficulties — missing what is important because of pettiness and pride. The comedy makes the message gentle but pointed."}
      ],
      long: [
        {q:"'The Proposal' is a farce that uses comedy to make a serious point about human nature. Discuss.",a:"'THE PROPOSAL' — COMEDY AND SERIOUS MEANING:\n\nWHAT IS A FARCE?\nA farce is a comic play that uses exaggerated situations, misunderstandings, and absurd behaviour for laughter. It is not realistic but highlights absurdity in human behaviour.\n\nFARCICAL ELEMENTS:\n1. LOMOV'S HYPOCHONDRIA: His symptoms are wildly exaggerated — perfect heart in normal moments, catastrophic during any argument\n2. TWO POINTLESS QUARRELS: First about land both sides have used 'forever', second about whose dog is better — completely unresolvable and irrelevant to the proposal\n3. NATALYA'S INSTANT REVERSAL: From insulting Lomov to desperately wanting him back — purely because she heard 'proposal'\n4. CHUBUKOV'S POSITIONS: Takes daughter's side vigorously, insults Lomov, then immediately blesses the match\n5. THE ENDING: Couple finally 'engaged' — but immediately start quarrelling about dogs again\n\nSERIOUS POINTS MADE THROUGH COMEDY:\n1. PETTINESS OVER PRIORITIES: Humans routinely let small matters (land boundaries, dog pedigrees) overshadow what truly matters (relationships, happiness)\n2. PRIDE AS OBSTACLE: Pride prevents people from backing down — even when they know they should\n3. CLASS SATIRE: Russian landowning class more concerned with property and status than real human values\n4. MARRIAGE AS INSTITUTION: The mechanical, transactional nature of marriage negotiations is satirised — love is barely mentioned\n5. HUMAN IRRATIONALITY: People behave irrationally when emotions (pride) override reason\n\nCHEKHOV'S SKILL:\n• He makes us laugh at the characters while also recognising ourselves\n• We see our own pettiness reflected in magnified form\n• The comedy is gentle but the critique is sharp\n\nCONCLUSION: The farce is not just entertainment — it is a mirror that shows us how foolishly we can behave, how we sabotage our own happiness through pettiness, and how pride can make enemies of potential friends and lovers."}
      ],
      passage: [
        {q:"Read the exchange:\n\nLOMOV: 'Natalia Stepanovna, I hope you will not be offended... My left cheek is twitching.'\nNATALYA: 'You're never ill — no, never! As long as you are alive you are in good health, but as soon as we touch on something serious you start twitching!'\n\n(a) What is happening in this scene?\n(b) Why does Lomov's cheek twitch?\n(c) What does Natalya's reply suggest about her view of Lomov?\n(d) What is the comic effect of this exchange?",a:"(a) What is happening in this scene:\nLomov has come to propose marriage to Natalya. He is trying to make the proposal but is nervous and anxious. His physical symptoms (twitching cheek) are interfering with his ability to speak. He is apologising in advance for any offence — showing his nervousness. Natalya is reacting with some exasperation to his constant health complaints. The scene captures Lomov's inability to deliver a simple message because of his anxiety.\n\n(b) Why Lomov's cheek twitches:\n• Lomov is a chronic hypochondriac — he constantly suffers from imagined or exaggerated physical symptoms\n• When nervous or stressed, his symptoms appear — heart palpitations, numb legs, twitching\n• The proposal is an emotionally charged moment — his anxiety triggers his symptoms\n• His physical weakness is partly real (he is nervous) and partly exaggerated by his hypochondria\n• The twitching represents his general inability to be direct and confident in important matters\n• There may also be a satirical point — some people's 'illnesses' conveniently appear when facing responsibility\n\n(c) Natalya's reply suggests:\n• She is somewhat impatient with Lomov's constant health complaints — has heard them before\n• She is perceptive — she notices that his symptoms appear specifically when something serious comes up\n• She may be a bit cynical about his condition — sees it as psychosomatic or exaggerated\n• She is direct and unsentimental — does not coddle him or sympathise\n• Despite her impatience, she doesn't dismiss him — she is engaged in the conversation\n• She shows some understanding of the pattern — 'whenever we touch on something serious'\n\n(d) Comic effect:\n• The contrast between the serious purpose (marriage proposal) and the trivial complaint (twitching cheek) is funny\n• Lomov's inability to propose because of his anxiety-driven symptoms creates situational comedy\n• Natalya's blunt, slightly exasperated response to what should be a romantic moment is comically deflating\n• The audience can see clearly what the characters cannot — that he is trying to propose and failing repeatedly\n• The gap between what Lomov wants to say and what he actually manages to say creates comic tension\n• Chekhov uses this to show that in real life, important moments are rarely romantic and smooth — they are messy and awkward"}
      ]
    }
  }
};
