const SOCIAL_HIST_QUESTIONS_DB = {
  "social_hist": {

    "The Rise of Nationalism in Europe": {
      mcq: [
        {q:"In 1848, Frédéric Sorrieu, a French artist, visualised a world made up of:",opts:["Monarchies","Democratic and Social Republics","Military states","Colonial empires"],ans:1},
        {q:"'Absolutist' government means:",opts:["Democratic government","A government with no restraints on power — centralised, militarised and repressive","Federal government","Government with limited power"],ans:1},
        {q:"The French Revolution began in:",opts:["1789","1848","1815","1830"],ans:0},
        {q:"'La Patrie' and 'Le Citoyen' were new French terms that meant:",opts:["The King and The Church","The fatherland and the citizen","The army and the state","The revolution and the people"],ans:1},
        {q:"The French army carried the idea of nationalism to:",opts:["Only France","Other European regions through Napoleon's wars","Only Germany","Only Italy"],ans:1},
        {q:"Napoleon's Civil Code of 1804 (Napoleonic Code) established:",opts:["Feudalism","Equality before law, abolished privileges of birth, secured right to property","Military rule","Church supremacy"],ans:1},
        {q:"After Napoleon's defeat, the major European powers met at:",opts:["Paris","Berlin","Vienna (Congress of Vienna, 1815)","London"],ans:2},
        {q:"The Congress of Vienna (1815) was hosted by:",opts:["Napoleon Bonaparte","Duke of Wellington","Duke Metternich of Austria","Tsar Alexander of Russia"],ans:2},
        {q:"Romanticism in Europe was a cultural movement that sought to:",opts:["Promote science and reason","Revive folk culture, local languages and emotional bonds to nation","Spread industrialisation","Promote democracy"],ans:1},
        {q:"The Greek War of Independence (1821) generated support across Europe because:",opts:["Greece was economically important","Europeans felt connected to ancient Greek civilisation — 'cradle of European culture'","Greece was militarily powerful","Greeks were Christian"],ans:1},
        {q:"Who was Giuseppe Mazzini?",opts:["Italian king","Austrian Chancellor","Italian nationalist who founded 'Young Italy' and 'Young Europe'","French revolutionary"],ans:2},
        {q:"Germany was unified under the leadership of:",opts:["Kaiser Wilhelm II","Otto von Bismarck (Prussian Chief Minister)","Giuseppe Garibaldi","Napoleon III"],ans:1},
        {q:"Italy was unified by 1871 under:",opts:["Mazzini","Bismarck","King Victor Emmanuel II with Cavour and Garibaldi","Napoleon"],ans:2},
        {q:"'Blood and Iron' policy was associated with:",opts:["Garibaldi","Mazzini","Otto von Bismarck","Napoleon"],ans:2},
        {q:"The Zollverein (1834) was a:",opts:["Military alliance","Customs union that removed tariff barriers between German states","Political union of Germany","Cultural movement"],ans:1},
        {q:"Marianne was a female allegory representing:",opts:["Germany","Italy","France","Poland"],ans:2},
        {q:"Germania was the female allegory for:",opts:["Italy","France","Austria","Germany"],ans:3},
        {q:"In 1848, the liberal nationalists in Frankfurt Parliament demanded:",opts:["Military rule","Abolition of monarchy","Unification of German nation with a constitution and democratic principles","Feudal restoration"],ans:2},
        {q:"The 'Spring of Nations' refers to:",opts:["Agricultural revolution","Revolutions of 1848 across Europe","Discovery of America","Industrial Revolution"],ans:1},
        {q:"Which of these did NOT contribute to the rise of nationalism in Europe?",opts:["French Revolution","Romantic movement","Feudalism","Napoleon's wars"],ans:2}
      ],
      short: [
        {q:"What was the significance of the French Revolution for the rise of nationalism?",a:"THE FRENCH REVOLUTION AND NATIONALISM:\n\nThe French Revolution (1789) was the first clear expression of nationalism in Europe.\n\nKEY CONTRIBUTIONS:\n1. SOVEREIGNTY SHIFTED: From monarchy to the 'nation' — the people became sovereign\n2. NEW POLITICAL IDEAS: 'La Patrie' (fatherland), 'Le Citoyen' (citizen) became new concepts\n3. NEW SYMBOLS: Tricolour flag replaced royal standard; new hymns, oaths, Revolutionary calendar\n4. NATIONHOOD: French people saw themselves as a 'national community' for first time\n5. SPREAD BY NAPOLEON: French armies carried revolutionary ideas (equality, liberty, fraternity) across Europe\n6. NAPOLEON'S CODE: Abolished feudal privileges, equality before law, administrative reforms in conquered territories\n\nPARADOX: While spreading ideas of nationhood, Napoleon also aroused nationalist feelings AGAINST French rule in conquered territories — showing that nationalism could unite AND resist.\n\nLEGACY: The French Revolution demonstrated that people could determine their own political fate — inspiring nationalists across Europe."},
        {q:"What was the Congress of Vienna (1815)? What were its main decisions?",a:"CONGRESS OF VIENNA (1815):\nAfter Napoleon's defeat, the conservative powers of Europe — Austria, Britain, Prussia and Russia — met in Vienna hosted by Austrian Chancellor Duke Metternich.\n\nGOAL: Restore the old conservative order (before French Revolution and Napoleon) and prevent future revolutions.\n\nMAIN DECISIONS:\n1. FRANCE CONTAINED: France's boundaries reduced to 1792 limits\n2. BUFFER STATES CREATED: To prevent future French expansion — Belgium added to Holland; Switzerland made independent; German states reformed into 39 states (German Confederation)\n3. MONARCHY RESTORED: Bourbon dynasty restored in France and Spain; other legitimate rulers restored\n4. BALANCE OF POWER: Between Britain, Austria, Prussia and Russia to prevent dominance by any one\n5. CONSERVATIVE PRINCIPLE: Liberty and nationalism were seen as threats — governments could suppress revolutionary movements\n\nLEGACY: Despite its conservative goals, the Vienna settlement could not suppress the growing forces of liberalism and nationalism. Revolutions continued throughout the 19th century."},
        {q:"How did Romanticism contribute to the growth of nationalism in Europe?",a:"ROMANTICISM AND NATIONALISM:\nRomanticism was a cultural movement that emerged as a reaction against the emphasis on reason and science. It sought to revive emotion, intuition and connection to nature and heritage.\n\nCONTRIBUTIONS TO NATIONALISM:\n1. FOLK CULTURE REVIVAL: Romantics collected and celebrated folk songs, folk tales, dances — showing that each nation had a unique culture\n2. LOCAL LANGUAGES: Johann Gottfried Herder (German) argued that true German culture lay in common people's culture — Volksgeist (spirit of the people)\n3. VERNACULAR LANGUAGES: Poets and writers used local languages to reach the masses and promote national feeling\n4. NATIONAL TRADITIONS: Romantics invented or revived national traditions, heroes and history\n5. HISTORY AND MYTH: Stories of past glory inspired national pride\n\nEXAMPLE:\n• Grimm Brothers collected German folk tales\n• Karol Kurpinski in Poland composed operas on national themes\n• Jan Sibelius in Finland composed music celebrating Finnish landscapes\n\nROLE OF WOMEN: Romantic literature and imagery often used female figures to represent the nation (Marianne in France, Germania in Germany)."},
        {q:"Explain the role of Bismarck in the unification of Germany.",a:"BISMARCK AND GERMAN UNIFICATION:\n\nOtto von Bismarck was the Chief Minister (Junker) of Prussia who unified Germany through his 'Blood and Iron' policy.\n\nSTRATEGY:\n• Bismarck believed Germany could not be unified through 'speeches and majority decisions' (as liberals wanted in 1848)\n• Required war and strong army — 'blood and iron'\n\nTHREE WARS LEADING TO UNIFICATION:\n1. WAR AGAINST DENMARK (1864): Prussia + Austria defeated Denmark, gained Schleswig and Holstein\n2. AUSTRO-PRUSSIAN WAR (1866): Prussia defeated Austria; Austria excluded from German affairs; North German Confederation formed\n3. FRANCO-PRUSSIAN WAR (1870-71): Prussia defeated France; southern German states joined Prussia\n\nUNIFICATION (1871):\n• German Empire proclaimed in the Palace of Versailles (symbolic humiliation for France)\n• Prussian King Wilhelm I became Kaiser (Emperor) of Germany\n• Bismarck became Chancellor\n\nLEGACY: German unification through military means set the template for aggressive nationalism, eventually contributing to World War I."}
      ],
      long: [
        {q:"Trace the process of unification of Italy. What were the roles of Mazzini, Cavour and Garibaldi?",a:"ITALIAN UNIFICATION:\nItaly before 1871 was divided into multiple states — Kingdom of Sardinia-Piedmont, Papal States, Austrian-controlled regions, Kingdom of Naples etc.\n\nTHREE HEROES OF ITALIAN UNIFICATION:\n\n1. GIUSEPPE MAZZINI (Revolutionary phase):\n• Founded 'Young Italy' (1831) — a secret society to spread republican nationalism\n• Founded 'Young Europe' — pan-European movement\n• Believed Italy should be unified as a democratic republic\n• Organised unsuccessful revolutions in 1834 and 1848\n• Called 'the prophet of Italian nationalism' — inspired generations\n• Limitation: His revolutionary approach failed militarily\n\n2. COUNT CAMILLO DI CAVOUR (Diplomatic phase):\n• Chief Minister of Sardinia-Piedmont (1852-61)\n• Not a mass nationalist but a shrewd diplomat\n• Modernised Piedmont's economy\n• Formed diplomatic alliance with France against Austria (1858)\n• Won Franco-Austrian War (1859) — gained Lombardy\n• Used diplomacy to bring most of north-central Italy under Piedmont\n\n3. GIUSEPPE GARIBALDI (Military phase):\n• Military leader who led 'Red Shirts' (thousand volunteers)\n• Conquered Kingdom of the Two Sicilies (southern Italy) in 1860\n• Handed control to King Victor Emmanuel II\n\nUNIFICATION COMPLETE (1861-1871):\n• 1861: Kingdom of Italy proclaimed with Victor Emmanuel II as king\n• 1866: Venetia joined after war with Austria\n• 1871: Rome included after French troops withdrew (Franco-Prussian War)\n\nItaly finally unified but with significant tensions between north and south that persist today."}
      ],
      passage: [
        {q:"Read the following:\n\n'In 1848, Frédéric Sorrieu, a French artist, prepared a series of four prints visualising his dream of a world made up of democratic and social Republics. The peoples of Europe are grouped as distinct nations, identified through their flags and national costume. Leading the procession are the United States and Switzerland, which by this time were already nation-states.'\n\n(a) What does Sorrieu's vision tell us about ideas prevalent in 1848?\n(b) What is a 'nation-state'? How is it different from a dynastic empire?\n(c) Why were USA and Switzerland leading the procession?\n(d) What is meant by 'utopian'?",a:"(a) Sorrieu's vision tells us that in 1848, there was widespread belief in: 1) Democratic governance (democratic republics), 2) The right of peoples to form their own nation-states, 3) International fraternity among nations, 4) Liberty as a universal value, 5) The idea that nations are natural, eternal entities with distinct identities represented by flags and costumes. It reflects the liberal nationalist spirit of the 1848 revolutions.\n\n(b) A nation-state is a state in which the majority of citizens develop a sense of common identity, shared history, language and culture — and this commonness gives legitimacy to the state's authority.\n\nDifference from dynastic empire: Dynastic empires were ruled by monarchies whose legitimacy came from royal lineage/divine right, not from the 'nation.' They often contained many different ethnic groups, languages and religions under one ruler (e.g., Austro-Hungarian Empire). A nation-state's legitimacy comes from the PEOPLE — citizens who share a national identity.\n\n(c) USA and Switzerland led because they were already established NATION-STATES with democratic constitutions by 1848. USA had been a democratic republic since 1776; Switzerland was a federation of democratic cantons. They represented the ideal that Sorrieu dreamed other nations would achieve.\n\n(d) 'Utopian' means a vision of an ideal society that is so perfect it is unlikely to actually exist. From 'Utopia' (Greek for 'no place' — meaning an ideal that doesn't exist). Sorrieu's vision was utopian because he imagined all peoples of the world peacefully marching together as free democratic nations — a beautiful but unrealistic ideal, especially given the conflicts and inequalities of the real world."}
      ]
    },

    "Nationalism in India": {
      mcq: [
        {q:"Mahatma Gandhi returned to India from South Africa in:",opts:["1907","1910","1915","1920"],ans:2},
        {q:"'Satyagraha' literally means:",opts:["Civil disobedience","Truth-force or soul-force — insisting on truth","Non-cooperation","Passive resistance"],ans:1},
        {q:"The Rowlatt Act (1919) allowed the government to:",opts:["Give Indians more rights","Imprison people without trial for up to 2 years","Conduct elections","Allow press freedom"],ans:1},
        {q:"The Jallianwala Bagh massacre occurred in:",opts:["1915","1917","1919","1921"],ans:2},
        {q:"Who ordered the firing at Jallianwala Bagh?",opts:["Lord Irwin","Lord Curzon","General Dyer","Lord Chelmsford"],ans:2},
        {q:"The Non-Cooperation Movement was launched in:",opts:["1919","1920","1922","1930"],ans:1},
        {q:"The Non-Cooperation Movement was called off because of:",opts:["Gandhi's illness","Chauri Chaura incident (1922) where a mob burned a police station","British concessions","Muslim withdrawal"],ans:1},
        {q:"The Khilafat Movement was started to protest:",opts:["Rowlatt Act","Dismemberment of the Ottoman Empire (Khalifa) after WWI","Jallianwala Bagh","Salt tax"],ans:1},
        {q:"The Civil Disobedience Movement began with:",opts:["Non-cooperation","Salt March (Dandi March, March 1930)","Quit India Movement","Swaraj resolution"],ans:1},
        {q:"The Dandi March began on:",opts:["February 12, 1930","March 12, 1930","April 6, 1930","January 26, 1930"],ans:1},
        {q:"The Gandhi-Irwin Pact (1931) led to:",opts:["Indian independence","Civil Disobedience Movement being called off and Gandhi attending Round Table Conference","Partition of India","Formation of INA"],ans:1},
        {q:"'Vande Mataram', the national song of India, was composed by:",opts:["Rabindranath Tagore","Bankim Chandra Chattopadhyay","Gandhi","Nehru"],ans:1},
        {q:"The Indian National Congress adopted the goal of 'Purna Swaraj' (complete independence) at:",opts:["Surat 1907","Lahore 1929","Calcutta 1920","Lucknow 1916"],ans:1},
        {q:"The Quit India Movement was launched in:",opts:["1940","1942","1945","1943"],ans:1},
        {q:"Bharat Mata (Mother India) image was first created by:",opts:["Gandhi","Abanindranath Tagore","Bankim Chandra","Nehru"],ans:1},
        {q:"Dalits preferred the term __ coined by B.R. Ambedkar:",opts:["Harijans","Untouchables","Depressed Classes","Dalits"],ans:3},
        {q:"Simon Commission (1927) was boycotted because:",opts:["It was anti-Indian","It had no Indian members — all British","It proposed partition","It increased taxes"],ans:1},
        {q:"The Poona Pact (1932) was between:",opts:["Gandhi and British","Gandhi and Ambedkar — regarding separate electorate for Dalits","Congress and Muslim League","India and Pakistan"],ans:1},
        {q:"Alluri Sitarama Raju was associated with:",opts:["Indigo revolt","Gudem Hills (Andhra Pradesh) tribal revolt against forest laws","Non-cooperation Movement","Civil Disobedience"],ans:1},
        {q:"Women participated in the Civil Disobedience Movement by:",opts:["Only voting","Making salt, picketing liquor shops and foreign cloth shops","Only marching","Not participating"],ans:1}
      ],
      short: [
        {q:"What was the Rowlatt Act? Why did it create widespread anger in India?",a:"ROWLATT ACT (1919):\nAlso called the 'Black Act' — officially the Anarchical and Revolutionary Crimes Act.\n\nPROVISIONS:\n• Allowed government to imprison political prisoners WITHOUT TRIAL for up to 2 years\n• Gave police power to arrest suspected revolutionaries without warrant\n• No appeal allowed — hence called 'no appeal, no vakil, no dalil' (no appeal, no lawyer, no argument)\n\nWHY IT CAUSED ANGER:\n1. CONTRADICTED PROMISES: British had promised Indians reforms and self-rule as reward for WWI support\n2. BETRAYAL: After Indians had sacrificed in WWI, Britain imposed repressive law\n3. UNDERMINED RIGHTS: Basic civil liberties and right to fair trial denied\n4. ARBITRARY POWER: Government could arrest anyone on suspicion — dangerous for political activists\n5. INSULTING: Indians felt they were being treated as criminals without proof\n\nRESPONSE:\n• Gandhi launched a nationwide satyagraha against the Act (April 6, 1919)\n• Hartals (strikes) across India\n• Mass protests in many cities\n• Led to JALLIANWALA BAGH MASSACRE (April 13, 1919)"},
        {q:"What was Satyagraha? How was it different from ordinary resistance?",a:"SATYAGRAHA (developed by Gandhi in South Africa):\nThe word means 'insistence on truth' (Satya = truth, Agraha = insistence).\n\nCORE IDEAS:\n• If the cause is just, physical force is NOT necessary\n• Truth alone has power — a satyagrahi wins through moral power\n• Must be willing to suffer rather than inflict suffering\n• Non-violence is essential — the opponent must be converted, not defeated\n• Respect for opponent's humanity — no hatred\n\nHOW DIFFERENT FROM ORDINARY RESISTANCE:\n1. NON-VIOLENCE: Traditional resistance might involve violence; Satyagraha never\n2. MORAL FORCE: Instead of physical coercion, uses moral persuasion\n3. SUFFERING WILLINGLY: Satyagrahis courted arrest and suffering — strengthened the moral argument\n4. CHANGE OF HEART: Aim was to win over the oppressor through truth, not to crush them\n5. NO HATRED: 'Hate the sin, love the sinner' — no personal animosity\n\nEFFECT ON BRITISH:\nBy courting imprisonment peacefully, Indians exposed the injustice of British rule to the world, making British rule increasingly difficult to justify morally."},
        {q:"Why did Gandhi launch the Civil Disobedience Movement with the Salt March? What was its significance?",a:"BACKGROUND:\n• In 1929, Congress declared 'Purna Swaraj' (complete independence) as goal\n• January 26, 1930 declared as Independence Day\n• Gandhi announced Civil Disobedience Movement\n\nWHY SALT:\n1. SALT TAX — SYMBOL OF BRITISH INJUSTICE: British had monopoly on salt production and charged tax — everyone (rich and poor) needed salt\n2. UNIVERSAL RELEVANCE: Salt affected all classes, castes and religions — a unifying issue\n3. EVERYDAY NECESSITY: Making salt was making common people disobey a law they found unjust\n4. DRAMATIC POTENTIAL: Simple act of picking up salt from the sea shore was visually powerful\n\nTHE MARCH (March 12 – April 6, 1930):\n• Gandhi walked 240 miles from Sabarmati Ashram to Dandi (coastal village) with 78 followers\n• Thousands joined along the way\n• On April 6, Gandhi picked up a handful of salt — breaking the law\n• Nationwide salt-making began\n\nSIGNIFICANCE:\n1. MASS MOVEMENT: Millions participated across India — farmers, workers, women\n2. WOMEN'S PARTICIPATION: Women picketed liquor and foreign cloth shops in large numbers — major change\n3. INTERNATIONAL ATTENTION: World media covered the march\n4. SHOWED UNITY: Hindus, Muslims, all classes participated\n5. WEAKENED BRITISH AUTHORITY: British jailed 60,000 people — but couldn't suppress the movement\n6. GANDHI-IRWIN PACT (1931): British conceded some demands"},
        {q:"How did different social groups participate in the Non-Cooperation Movement?",a:"PARTICIPATION IN NON-COOPERATION MOVEMENT (1920-22):\n\n1. MIDDLE CLASS — URBAN AREAS:\n• Lawyers like Motilal Nehru, C.R. Das gave up law practice\n• Students left government schools and colleges\n• Teachers resigned from government schools\n• Merchants boycotted foreign cloth and liquor shops\n\n2. PEASANTS — RURAL AREAS:\n• Peasants in Awadh (UP) under Baba Ramchandra refused to pay rent to landlords\n• Connected to Gandhi's movement though Gandhiji wanted non-violent non-cooperation\n• Peasant movement sometimes became violent (raiding landlords' homes)\n\n3. TRIBAL PEOPLE:\n• Alluri Sitarama Raju led Gudem Hills rebellion in Andhra Pradesh\n• Protested against forest laws that denied them access to forests\n• Used Gandhian methods and also violent methods — complex relationship with Gandhi's movement\n\n4. PLANTATION WORKERS (Assam):\n• Thousands of workers left tea plantations and tried to return home\n• Believed Gandhi's Swaraj meant they could return to their villages freely\n\n5. LIMITATIONS:\n• Muslim participation declined after Khilafat Movement faded\n• Dalit participation was limited — separate issues of untouchability\n• Called off after Chauri Chaura violence (February 1922)"}
      ],
      long: [
        {q:"Describe the Civil Disobedience Movement. How was it different from the Non-Cooperation Movement?",a:"CIVIL DISOBEDIENCE MOVEMENT (1930-34):\n\nBACKGROUND:\n• 1929 Lahore Congress: Purna Swaraj declared goal\n• Irwin rejected Nehru's demand for Dominion Status\n• Gandhi prepared 11 demands; Irwin ignored most\n• Gandhi chose salt as focus\n\nKEY EVENTS:\n1. SALT MARCH (March 12-April 6, 1930): Gandhi's 240-mile march to Dandi — mass civil disobedience began\n2. NATIONWIDE DISOBEDIENCE: Salt made across India; foreign cloth boycotted; forest laws broken; rent and revenue refused in some areas\n3. PARTICIPATION: Thousands arrested including Gandhi; women took leadership\n4. GANDHI-IRWIN PACT (1931): Gandhi suspended movement; went to Second Round Table Conference\n5. RESUMED (1932): After British communal award; second phase, less effective\n\nDIFFERENCES FROM NON-COOPERATION MOVEMENT:\n\nNON-COOPERATION (1920-22):\n• Focus: Refusing to cooperate — not going to schools, courts, returning honours\n• Phase 1 approach: Withdrawal, non-participation\n• Ended: When Chauri Chaura violence occurred (Gandhi called it off)\n• Participants: More urban initially\n\nCIVIL DISOBEDIENCE (1930-34):\n• Focus: ACTIVELY BREAKING unjust laws (making salt, entering forests)\n• More radical — deliberate law-breaking not just non-cooperation\n• Massive women's participation — new development\n• Wide geographic spread\n• International attention through Salt March\n\nSIMILARITY: Both used non-violent methods; both organised by Gandhi and Congress; both anti-British."}
      ],
      passage: [
        {q:"'The Jallianwala Bagh massacre: On 13 April 1919, General Dyer entered Amritsar with his troops. He marched them to a public garden called Jallianwala Bagh. Dyer's troops opened fire on the crowd. This continued for 10 to 15 minutes till the ammunition was exhausted. Hundreds were killed.'\n\n(a) What was the context that led to the Jallianwala Bagh massacre?\n(b) What was the significance of this event for the Indian nationalist movement?\n(c) Who wrote about this as 'an monstrous event'?\n(d) What was Rabindranath Tagore's response to this event?",a:"(a) Context leading to Jallianwala Bagh:\n• British had passed the Rowlatt Act (1919) allowing imprisonment without trial\n• Gandhi had called for a nationwide satyagraha on April 6, 1919\n• In Amritsar and Punjab, there were widespread protests and hartals\n• Two local leaders — Dr. Saifuddin Kitchlew and Dr. Satyapal — had been deported\n• Amritsar was placed under martial law\n• On April 13 (Baisakhi day), thousands had gathered in Jallianwala Bagh for a peaceful protest meeting unaware of the ban on gatherings\n\n(b) Significance for nationalist movement:\n• Turned millions against British rule — the outrage was universal\n• Demonstrated the true nature of British 'civilising mission' — brutal violence against peaceful protesters\n• Inspired new generation of revolutionaries (Bhagat Singh witnessed it as a child)\n• Hunter Commission inquiry revealed British had no regret — further alienated Indians\n• Gandhi described it as 'satanic' — became more committed to non-cooperation\n• United Hindus and Muslims in condemning the massacre\n• Became a defining moment in India's independence movement\n\n(c) Rabindranath Tagore described this as a monstrous event and renounced his knighthood in protest.\n\n(d) Rabindranath Tagore's response:\n• He renounced (gave back) his KNIGHTHOOD that the British had awarded him\n• He wrote to the Viceroy saying he could not accept honours from a government that committed such acts\n• This was a powerful symbolic protest by India's most internationally respected figure"}
      ]
    },

    "The Making of a Global World": {
      mcq: [
        {q:"The Silk Routes were important because they:",opts:["Only carried silk","Were examples of vibrant pre-modern trade and cultural exchange linking Asia, Europe and Africa","Only served military purposes","Connected only China and Rome"],ans:1},
        {q:"Food items like potatoes, tomatoes, chillies were introduced to the rest of the world after:",opts:["Ancient times","The Silk Route trade","Columbus discovered America (late 15th century)","Industrial Revolution"],ans:2},
        {q:"The 'Corn Laws' in Britain controlled:",opts:["Corn production","Import of cheap agricultural products — when repealed, cheap food could be imported","Corn prices","Corn storage"],ans:1},
        {q:"The Great Depression of 1929 began with:",opts:["Bank failures in Europe","Wall Street Crash (US stock market crash)","World War I","Agricultural failure"],ans:1},
        {q:"'Indentured labour' was used by British to:",opts:["Educate Indians","Provide cheap labour for colonies like Caribbean, Fiji, South Africa after abolition of slavery","Build British factories","Conduct war"],ans:1},
        {q:"The disease that devastated native American populations after European contact was:",opts:["Malaria","Smallpox (to which natives had no immunity)","Cholera","Plague"],ans:1},
        {q:"The first country to industrialise was:",opts:["Germany","France","United States","Britain"],ans:3},
        {q:"Bretton Woods Conference (1944) established:",opts:["United Nations","IMF and World Bank — to manage post-war international economy","WTO","G7"],ans:1},
        {q:"The Bretton Woods system was based on:",opts:["Gold standard","Dollar pegged to gold — fixed exchange rates","Free floating exchange rates","Euro system"],ans:1},
        {q:"The 'Second World War' began with Germany's invasion of:",opts:["France","Britain","Poland (1939)","Russia"],ans:2},
        {q:"The Marshall Plan was the US plan to:",opts:["Build US military","Rebuild war-devastated Europe through financial aid","Colonise Europe","Control oil supply"],ans:1},
        {q:"Post-WW2 prosperity in Western economies lasted until approximately:",opts:["1950s","1960s","Early 1970s (end of Bretton Woods system)","1980s"],ans:2},
        {q:"The Great Depression caused mass unemployment because:",opts:["Inflation was high","Banks failed, businesses closed, trade collapsed — economic collapse","War started","Natural disasters occurred"],ans:1},
        {q:"By the mid-19th century, the world was connected by a network of:",opts:["Roads only","Railways, steamships, telegraph cables","Air travel","Internet"],ans:1},
        {q:"The term G-77 refers to:",opts:["7 richest countries","77 developing countries who demanded a New International Economic Order","77 OPEC members","77 UN Security Council members"],ans:1}
      ],
      short: [
        {q:"What were the Silk Routes? How did they promote trade and cultural exchange?",a:"SILK ROUTES:\nAncient network of overland and sea routes connecting Asia with Europe and North Africa. Named after West-bound Chinese silk trade.\n\nEXISTED: Since before Christian Era to about 15th century.\n\nPROMOTED TRADE:\n• Chinese silk, pottery travelled westward\n• Indian and Southeast Asian textiles and spices\n• Gold and silver flowed from Europe to Asia\n• Created entire trading civilisations along the routes\n\nPROMOTED CULTURAL EXCHANGE:\n• Religious missionaries used these routes — Buddhism spread from India to East Asia\n• Early Christian missionaries to Asia\n• Muslim preachers spread Islam to Central Asia and China\n• Ideas, inventions, technologies travelled with traders\n• Food plants: Spaghetti may have come from Chinese noodles via Arab traders\n• Cowrie shells from Maldives found in China and East Africa — common currency\n\nSIGNIFICANCE:\nDemonstrates that globalisation did not begin with modern capitalism — ancient human societies were already interconnected through trade, religion and culture."},
        {q:"What was indentured labour? How was it used in British colonies?",a:"INDENTURED LABOUR:\nA system where labourers signed a contract (indenture) to work for a plantation owner for a fixed period (usually 5 years) in a distant colony in exchange for passage, food and accommodation.\n\nCONTEXT:\n• After abolition of slavery (1833), British plantation owners needed cheap labour\n• They turned to India, China, Sri Lanka, and Africa\n• Workers from Bihar, UP, Tamil Nadu, etc. recruited under false promises\n\nCONDITIONS:\n• Workers told they would return after 5 years (often couldn't afford to)\n• Conditions on ships and plantations were harsh — like slavery\n• Could not leave employer during contract — breach was criminal offence\n• Low wages, long hours, poor living conditions\n\nDESTINATIONS:\n• Caribbean (Trinidad, Guiana), Fiji, South Africa, Mauritius, Malaya, Ceylon\n\nRESISTANCE:\n• Workers resisted — slow work, sabotage, running away, suicide\n• Some strikes\n• Abolition campaigns — system abolished 1921\n\nLEGACY:\n• Significant Indian diaspora in Caribbean, Fiji, Mauritius\n• Cultural mixing — bhojpuri music in Caribbean, Hindi religions in Fiji\n• Created social inequalities and racial tensions that persist"},
        {q:"Describe the Great Depression (1929). What were its causes and effects on colonies like India?",a:"GREAT DEPRESSION (1929-1930s):\n\nCAUSES:\n1. WALL STREET CRASH (October 1929): US stock market collapsed — billions wiped out\n2. BANK FAILURES: Banks called in loans, businesses couldn't repay, banks collapsed\n3. OVERPRODUCTION: Factories and farms had produced more than people could buy\n4. AGRICULTURAL CRISIS: Farm prices had been falling through 1920s\n5. TRADE COLLAPSE: Countries raised tariffs to protect domestic industries — global trade fell\n\nEFFECTS ON USA/EUROPE:\n• 25% unemployment in USA\n• Businesses closed, wages fell\n• Poverty and hunger widespread\n• Political consequences — rise of fascism in Europe\n\nEFFECTS ON COLONIES (India):\n1. AGRICULTURAL PRICES COLLAPSED: Wheat prices fell 50% — farmers' incomes devastated\n2. COLONIAL EXPLOITATION CONTINUED: India was forced to export more to earn foreign exchange\n3. EXPORTS FELL BUT IMPORTS CONTINUED: India had trade surplus but living standards fell\n4. RURAL DISTRESS: Peasants borrowed to pay taxes — debt increased\n5. URBAN WORKERS: Some industries reduced production — unemployment increased\n6. POLITICAL EFFECT: Economic distress increased support for independence movement — fuelled Civil Disobedience Movement (1930)"}
      ],
      long: [
        {q:"How did the post-World War II Bretton Woods system shape the global economy? Why did it eventually collapse?",a:"BRETTON WOODS SYSTEM (1944-1971):\n\nESTABLISHMENT:\nIn July 1944, Allied nations met at Bretton Woods, New Hampshire, USA to plan post-war international economic order.\n\nINSTITUTIONS CREATED:\n1. IMF (International Monetary Fund): For dealing with external surpluses and deficits of member nations\n2. World Bank: For financing post-war reconstruction and development\n\nFEATURES:\n1. FIXED EXCHANGE RATES: All currencies pegged to US Dollar; Dollar pegged to gold ($35 per ounce)\n2. US DOMINANCE: USA held most of world's gold — dollar was international reserve currency\n3. CAPITAL CONTROLS: Countries could control flows of money in and out\n4. RECONSTRUCTION: Marshall Plan ($13 billion from USA) rebuilt Western Europe\n\nAGE OF PROSPERITY (1950s-60s):\n• Rapid economic growth in Western countries\n• Low unemployment\n• Rising living standards\n• Global trade expanded enormously\n• Post-war industrial reconstruction\n\nWHY IT COLLAPSED (1971):\n1. USA SPENT TOO MUCH: Vietnam War and domestic programmes drained US gold reserves\n2. DOLLAR WEAKENED: USA printed too many dollars; confidence in dollar-gold link weakened\n3. US TRADE DEFICITS: Europe and Japan became competitive — USA lost trade surplus\n4. CAPITAL FLOWS: Multinational corporations moving money made fixed rates untenable\n5. 1971: President Nixon ended dollar's convertibility to gold — Bretton Woods system collapsed\n6. FLOATING EXCHANGE RATES: Currencies now 'float' against each other — determined by market\n\nLEGACY: IMF and World Bank continue but with different roles — key institutions of globalisation."}
      ],
      passage: [
        {q:"'Many of our common foods such as potatoes, soya, groundnuts, maize, tomatoes, chillies, sweet potatoes were not known to our ancestors until about five centuries ago. These foods were only introduced in Europe and Asia after Christopher Columbus accidentally discovered the Americas.'\n\n(a) How did these food plants spread globally?\n(b) What other things spread along with trade and exploration?\n(c) How did the discovery of America affect indigenous peoples?\n(d) Give an example of how food spread represents cultural exchange.",a:"(a) How food plants spread globally:\n• European colonisers brought plants from the Americas back to Europe, Asia and Africa\n• Traders, missionaries and explorers carried seeds and plants as they travelled\n• Colonial agriculture introduced American plants to colonial territories\n• Portuguese and Spanish sailors spread plants through their global trade routes\n• Over centuries, plants naturalised in new environments — today Bangladesh grows potatoes everywhere though potato is American!\n\n(b) Other things that spread with trade and exploration:\n• Germs and diseases: Smallpox, measles devastated native American populations\n• Animals: Horses reintroduced to Americas (had been extinct there)\n• Technologies: Printing, navigation techniques, manufacturing\n• Religion: Christianity spread by missionaries following colonisers\n• Culture: Music, dress, language\n• Ideas: Enlightenment ideas spread to colonies\n• Labour systems: Slavery, indentured labour moved people around the globe\n\n(c) Impact on indigenous peoples of Americas:\n• DEVASTATING: An estimated 90% of indigenous population died within a century of European contact\n• MAIN CAUSE: Diseases (smallpox, measles) to which natives had NO immunity — not guns\n• CONQUEST: Weakened populations easily conquered\n• FORCED LABOUR: Survivors enslaved in mines and plantations\n• CULTURAL DESTRUCTION: Languages, religions, traditions suppressed\n• LAND SEIZURE: Vast territories taken over\n\n(d) Example of food as cultural exchange:\n• Spaghetti (Italian) likely originated from Chinese noodles brought by Arab traders to Sicily in 5th century\n• The same food — in different forms — exists in China (noodles), India, Japan, Italy\n• This shows that even centuries ago, cultures were connected through trade routes and exchange"}
      ]
    },

    "The Age of Industrialisation": {
      mcq: [
        {q:"Britain was the first country to industrialise. Which industry led this process?",opts:["Steel","Cotton textile — particularly spinning and weaving","Coal mining","Railways"],ans:1},
        {q:"James Watt improved the steam engine in:",opts:["1689","1736","1781","1820"],ans:2},
        {q:"The 'Spinning Jenny' was invented by:",opts:["James Watt","Edmund Cartwright","James Hargreaves","Richard Arkwright"],ans:2},
        {q:"Why did industrialists initially prefer to use 'hand labour' over machines?",opts:["Machines were not available","Hand labour was sometimes cheaper than machines in seasons of plenty","Machines broke down","Workers preferred hand labour"],ans:1},
        {q:"'Proto-industrialisation' refers to:",opts:["Very early factories","Industrial production in the countryside BEFORE factory system — for international markets","Modern industries","Large-scale manufacturing"],ans:1},
        {q:"The term 'Orient' in 19th century European usage referred to:",opts:["Eastern Europe","Asia — seen as pre-modern, traditional, mysterious","Africa","Americas"],ans:1},
        {q:"The first cotton mill in India was established in:",opts:["1851 in Bombay","1854 in Bombay","1860 in Calcutta","1870 in Ahmedabad"],ans:1},
        {q:"Who was the first to set up a cotton mill in India?",opts:["Tata","Birla","Dwarkanath Tagore","Kawasji Davar (in Bombay, 1854)"],ans:3},
        {q:"Jute mills in India were mainly located in:",opts:["Bombay","Ahmedabad","Bengal","Punjab"],ans:2},
        {q:"Manchester and Leeds were important centres of __ in Britain:",opts:["Iron and steel","Cotton textile industry","Coal mining","Shipbuilding"],ans:1},
        {q:"The East India Company tried to prevent Indian weavers from:",opts:["Using machines","Weaving for Indian customers by forcing them to supply Company only","Selling in Europe","Learning English"],ans:1},
        {q:"'Gomasthas' were:",opts:["Indian merchants","Company agents who supervised weavers and collected goods","Village headmen","Tax collectors"],ans:1},
        {q:"Which of the following is TRUE about Indian exports before industrialisation?",opts:["India mainly imported finished goods","India exported large quantities of cotton textiles to Europe and Southeast Asia","India had no trade with Europe","India only exported spices"],ans:1},
        {q:"The Manchester textile industry's competition with Indian handloom weavers led to:",opts:["Indian weavers becoming richer","Decline of many Indian handloom weaving centres","Indian weavers modernising","No impact on India"],ans:1},
        {q:"The Calcutta jute mills were mainly owned by:",opts:["Indians","Marwari businessmen","British","Americans"],ans:2}
      ],
      short: [
        {q:"What was proto-industrialisation? How did it differ from the factory system?",a:"PROTO-INDUSTRIALISATION:\nIndustrial production that existed in the countryside BEFORE factory system emerged — producing for regional and international markets.\n\nFEATURES:\n• Production happened in rural homes and cottages, not factories\n• Merchants supplied raw materials to rural producers\n• Workers produced goods at home using own tools (cottage industries)\n• Merchants collected finished goods and sold in distant markets\n• Existed across Europe and other parts of world before Industrial Revolution\n• Helped families supplement farm income — seasonal work\n\nEXAMPLE:\n• In 17th-18th century England, merchants gave wool to rural families who spun and wove cloth at home\n• Merchant supplied raw material, collected finished cloth, sold internationally\n\nDIFFERENCES FROM FACTORY SYSTEM:\n• LOCATION: Proto-industry was in homes; factories were centralised buildings\n• CONTROL: Worker had more control; factory owner had total control\n• TECHNOLOGY: Proto-industry used simple tools; factories had power machinery\n• WORK RHYTHM: Proto-industry followed seasons; factories had fixed hours\n• SCALE: Factories produced more, faster\n• RELATIONSHIP: Proto-industry was family-based; factory was wage labour"},
        {q:"Why did Indian weavers and artisans decline in the 19th century?",a:"DECLINE OF INDIAN WEAVERS AND ARTISANS:\n\n1. MACHINE-MADE IMPORTS:\n• British machine-made cotton and silk textiles flooded Indian markets after 1820s\n• Machine goods were CHEAPER than handloom goods\n• Indian weavers could not compete on price\n\n2. COLONIAL POLICIES:\n• British imposed IMPORT DUTIES on Indian goods exported to Britain (protecting British industry)\n• Simultaneously REMOVED protection for Indian industries\n• Unequal trade — Indian markets open to British goods; Indian goods restricted in Britain\n\n3. LOSS OF PATRONAGE:\n• Nawabs, kings and nobles who patronised weavers lost power\n• Colonial officers preferred European goods\n• Local courts disappeared — major customers gone\n\n4. RAW MATERIAL DIVERSION:\n• Raw cotton increasingly exported to Britain rather than used by Indian weavers\n\n5. COMPETITION IN EXPORT MARKETS:\n• Indian textiles lost traditional export markets in Africa and Southeast Asia to cheaper British goods\n\nRESULT:\n• Traditional weaving centres like Dacca (muslin), Surat and Murshidabad declined sharply\n• Weavers became agricultural labourers or migrated to cities\n• 'De-industrialisation' — reverse of industrial progress in India\n\nEXCEPTION: Some weavers survived by producing cheaper, coarser cloth or by finding niches like silk weaving"},
        {q:"Why did the growth of factory industries in India happen slowly? What were the obstacles?",a:"SLOW GROWTH OF FACTORY INDUSTRIES IN INDIA:\n\nOBSTACLES:\n1. COLONIAL POLICY:\n• British discouraged Indian industrialisation to protect British industries\n• Free trade policy forced on India — British goods competed without restrictions\n• Government contracts and railways mainly benefited British companies\n\n2. CAPITAL AND TECHNOLOGY:\n• Limited access to capital for Indian entrepreneurs\n• Technology had to be imported — costly\n• Technical skills were concentrated in Britain\n\n3. COMPETITION:\n• Cheaper British machine-made goods dominated markets — difficult to compete\n• British companies had advantages of established reputation and connections\n\n4. INFRASTRUCTURE:\n• Railways initially built to transport raw materials OUT of India, not to promote industrialisation\n• Ports and communication served British needs\n\nDESPITE OBSTACLES — INDIAN INDUSTRIALISATION:\n• First cotton mill: Bombay 1854 (Kawasji Davar)\n• Tata Iron and Steel Company: Jamshedpur 1912 (J.N. Tata)\n• Jute mills in Bengal\n• Cotton mills in Bombay and Ahmedabad\n• Mainly Indian capital in cotton; mainly British in jute\n\nWWI BOOST:\n• When British goods could not reach India during WWI, Indian factories grew — showed potential of Indian industry"}
      ],
      long: [
        {q:"Describe the features of early industrial society in Britain. What were the conditions for workers?",a:"EARLY INDUSTRIAL BRITAIN:\n\nFEATURES OF INDUSTRIAL SOCIETY:\n1. URBANISATION: Rural population moved to industrial cities — Manchester, Birmingham, Leeds\n2. FACTORIES: Large buildings housing hundreds of workers with machines\n3. CHILD AND WOMEN LABOUR: Factory owners used cheaper labour extensively\n4. LONG WORKING HOURS: 14-16 hours daily were common\n5. POOR CONDITIONS: Dangerous machinery, dust, chemicals, no safety measures\n6. SEASONAL UNEMPLOYMENT: Even in factories, some work was seasonal — idle periods\n7. LOW WAGES: Workers poorly paid; had to work constantly or face destitution\n\nCONDITIONS FOR WORKERS:\nBAD:\n• No job security — could be dismissed any time\n• No minimum wage or unions initially\n• Child labour — children as young as 5 worked in mines and factories\n• Dangerous conditions — accidents, respiratory diseases, injuries common\n• Poor housing in industrial slums — overcrowded, no sanitation\n• Long hours with no breaks\n• Women paid less than men for same work\n\nIMPROVEMENTS OVER TIME:\n• Labour laws gradually introduced (Factory Acts restricting child labour)\n• Trade unions formed — bargained for better conditions\n• Working hours reduced\n• Safety regulations introduced\n• Universal education eventually provided\n\nCONTRADICTION:\nIndustrialisation created enormous wealth but also created new forms of poverty and exploitation — challenging the simple narrative of 'progress'."}
      ],
      passage: [
        {q:"Read the following:\n\n'In 1900, a popular music publisher produced a music book with a picture of the angel of progress bearing the flag of the new century. She is gently perched on a wheel with wings, symbolising time. Floating about, behind her, are the signs of progress: railway, camera, machines, printing press and factory.'\n\n(a) What does this image tell us about the attitude towards industrialisation in 1900?\n(b) Is this a complete or one-sided view of industrialisation? Explain.\n(c) What were the negative effects of industrialisation that this image ignores?\n(d) What is the historian's task when studying such sources?",a:"(a) The image reflects the TRIUMPHANT, OPTIMISTIC attitude towards industrialisation in 1900. Society at that time viewed:\n• Technology and machines as symbols of human progress and achievement\n• Railways, factories, cameras as markers of civilisation and modernity\n• Industrial progress as something god-given (the angel) and inevitable (wheel of time)\n• The West's industrial power as natural and beneficial\nThis reflected the dominant ideology of the age — that modernisation and industrialisation meant progress for all humanity.\n\n(b) This is a ONE-SIDED and incomplete view of industrialisation because it shows only the positive aspects. It represents the perspective of industrialists, manufacturers and the ruling class who benefited most from industrialisation. It ignores the experiences of workers, colonised peoples, and those displaced by machines.\n\n(c) Negative effects ignored by this image:\n• WORKER EXPLOITATION: Long hours, dangerous conditions, child labour, low wages\n• URBANISATION PROBLEMS: Overcrowded industrial slums, disease, pollution\n• ENVIRONMENTAL DAMAGE: Coal smoke, river pollution, destruction of landscapes\n• COLONIAL IMPACT: Industrialisation in Europe meant de-industrialisation in colonies like India — weavers lost livelihoods\n• SOCIAL DISRUPTION: Traditional communities broken up; skilled artisans lost status\n• CLASS INEQUALITY: Massive wealth created for few owners; poverty for many workers\n\n(d) The historian's task when studying such sources:\n• Recognise the source's PERSPECTIVE and BIAS — who created it? For what purpose?\n• Consider WHOSE experience is represented and whose is left out\n• Use multiple sources — including workers' memoirs, official records, newspaper reports — to get a complete picture\n• Critically question the dominant narrative — 'progress for whom?'\n• Understand the historical context — why did people see industrialisation this way?\n• Provide a balanced history that includes experiences of all groups"}
      ]
    },

    "Print Culture and the Modern World": {
      mcq: [
        {q:"The earliest kind of print technology was developed in:",opts:["Europe","Egypt","China, Japan and Korea","India"],ans:2},
        {q:"The oldest Japanese book printed in AD 868 was:",opts:["A political document","The Buddhist Diamond Sutra","A folk tale collection","A history"],ans:1},
        {q:"Gutenberg developed the first __ in Europe around 1448:",opts:["Paper mill","Movable type printing press","Woodblock print","Steam press"],ans:1},
        {q:"The Gutenberg Bible (1448) was:",opts:["A handwritten Bible","First book printed in Europe using movable type","A German translation only","A print of just the New Testament"],ans:1},
        {q:"The print revolution in Europe first made religious texts more:",opts:["Expensive","Rare","Accessible and affordable — could be printed in large numbers","Secret"],ans:2},
        {q:"Martin Luther's '95 Theses' spread rapidly due to:",opts:["Television","Internet","Print technology — thousands of copies printed","Handwritten copies"],ans:2},
        {q:"The Protestant Reformation was AIDED by:",opts:["The Catholic Church","Print technology spreading Luther's ideas","Handwritten manuscripts","Royal patronage"],ans:1},
        {q:"'Chapbooks' were:",opts:["Expensive books for scholars","Pocket-sized books sold cheaply by peddlers — for common people","Church publications","Government documents"],ans:1},
        {q:"The first printing press in India was brought by:",opts:["East India Company","Portuguese missionaries (Goa, 16th century)","British missionaries","French traders"],ans:1},
        {q:"The first newspaper in India was published by:",opts:["James Augustus Hickey (Bengal Gazette, 1780)","East India Company","Ram Mohan Roy","British government"],ans:0},
        {q:"Ram Mohan Roy published which newspaper?",opts:["Bengal Gazette","Sambad Kaumudi","The Hindu","Kesari"],ans:1},
        {q:"Bal Gangadhar Tilak published which newspaper?",opts:["Young India","Kesari (Marathi) — used to spread nationalist ideas","India Gazette","Tribune"],ans:1},
        {q:"The Vernacular Press Act (1878) was passed to:",opts:["Promote Indian languages","Control/censor Indian language newspapers that criticised British rule","Support vernacular literature","Tax newspapers"],ans:1},
        {q:"Which of the following was a POSITIVE effect of print culture for women in India?",opts:["Women were discouraged from reading","Educated women could read, write and publish — reformers supported women's education","Print had no effect on women","Women used print for gossip only"],ans:1},
        {q:"'Ulgulan' (the Great Tumult) was associated with:",opts:["Gandhi's movement","Birsa Munda's uprising in Jharkhand (1895-1900)","Champaran Satyagraha","Dandi March"],ans:1}
      ],
      short: [
        {q:"How did Gutenberg's printing press change Europe? What was its impact?",a:"GUTENBERG'S PRINTING PRESS (c. 1448):\nJohannes Gutenberg of Mainz, Germany, developed the first movable type printing press in Europe, adapting wine and olive press technology.\n\nCHANGES IT BROUGHT:\n\n1. BOOK PRODUCTION REVOLUTIONISED:\n• Before: Each book hand-copied — took months, very expensive\n• After: 150-200 copies per day, much cheaper\n• First book printed: Bible (1448) — 180 copies in 3 years\n• By 1500: 20 million books printed in Europe\n\n2. SPREAD OF IDEAS:\n• Ideas could now spread quickly and widely\n• Martin Luther's 95 Theses (1517) — spread across Europe in weeks through print\n• Protestant Reformation powered by print\n• Scientific ideas of Copernicus, Galileo spread widely\n\n3. LITERACY EXPANSION:\n• Books became affordable for middle classes\n• Chapbooks (cheap pocket books) sold to lower classes\n• Demand for literacy increased — reading became important\n\n4. NEW READERS:\n• Women began reading more\n• Working classes accessed books\n• Diverse literature: Novels, political pamphlets, science books\n\n5. QUESTIONING AUTHORITY:\n• Ideas could challenge Church and monarchy\n• People could read Bible themselves — didn't depend on priest\n• Led to political revolutions (pamphlets in French Revolution)\n\nFEAR:\nChurch and rulers recognised the danger — tried to control print through censorship and index of banned books."},
        {q:"How did print culture contribute to the development of nationalism in India?",a:"PRINT AND NATIONALISM IN INDIA:\n\n1. SPREADING IDEAS:\n• Nationalist ideas could be printed and distributed widely\n• Newspapers reached literate people across vast distances\n• Pamphlets and books in vernacular languages reached non-English speakers\n\n2. KEY NEWSPAPERS:\n• Bengal Gazette (Hickey, 1780) — first Indian newspaper\n• Sambad Kaumudi (Ram Mohan Roy) — promoted social reform and nationalism\n• Kesari (Tilak, Marathi) — 'Swaraj is my birthright'\n• Al Hilal (Maulana Azad) — for Muslim nationalists\n• Young India (Gandhi)\n\n3. SOCIAL REFORM MOVEMENTS:\n• Print debate on Sati, child marriage, widow remarriage\n• Ram Mohan Roy used print to campaign against Sati\n• Jyotiba Phule used print to challenge caste discrimination\n\n4. VERNACULAR LANGUAGES:\n• Literature in Bengali, Marathi, Tamil, Hindi connected people culturally\n• Shared language through print created sense of common identity\n• Songs, poems, stories of national pride spread through print\n\n5. COLONIAL CONCERNS:\n• Vernacular Press Act (1878) — British tried to curb vernacular press\n• Shows that British recognised print's power for nationalism\n\n6. GANDHI'S USE:\n• Gandhi's Hind Swaraj and writings spread through newspapers\n• Congress pamphlets printed in millions for mass campaigns"},
        {q:"What impact did print culture have on women and lower castes in colonial India?",a:"IMPACT ON WOMEN:\n\nPOSITIVE:\n1. REFORMERS USED PRINT: Social reformers (Ram Mohan Roy, Ishwarchandra Vidyasagar) used print to campaign for women's rights — widow remarriage, education\n2. WOMEN'S LITERATURE: Educated women began writing — Tarabai Shinde's Stri Purush Tulana (1882) criticised male dominance\n3. WOMEN'S MAGAZINES: Published in 1880s-90s for women — addressed their issues\n4. EDUCATION DEBATE: Print debates on women's education led to establishment of girls' schools\n5. NATIONALIST WOMEN: Women's participation in nationalism spread through printed words\n\nNEGATIVE:\n• Conservative men worried print would give women too much independence\n• Some men controlled what women read\n• Some prints reinforced traditional gender roles\n\nIMPACT ON LOWER CASTES:\n1. JYOTIBA PHULE (Maharashtra): Used print to challenge Brahmin dominance and advocate rights for lower castes\n2. DALIT LITERATURE: Writings of Dalit intellectuals spread through print\n3. AMBEDKAR'S MOOKNAYAK (1920): Newspaper for Dalit rights\n4. AWARENESS: Lower caste people could read about their rights\n5. BIRSA MUNDA: Tribal leader whose ideas spread partly through printed reports\n6. REGIONAL LANGUAGES: Print in local languages helped marginalised groups access information\n\nCONCLUSION: Print democratised access to knowledge and debate, though its benefits were unequal — those already literate and educated gained most."}
      ],
      long: [
        {q:"'The print revolution transformed the lives of people in Europe.' Discuss.",a:"PRINT REVOLUTION — TRANSFORMATION OF EUROPEAN LIFE:\n\nBEFORE PRINT (Manuscript culture):\n• Books were handwritten by monks — took months, very expensive\n• Only clergy and wealthy could afford books\n• Knowledge confined to monasteries, courts and universities\n• Church controlled information\n\nAFTER GUTENBERG (1448 onwards):\n\n1. DEMOCRATISATION OF KNOWLEDGE:\n• Books affordable for middle class\n• Chapbooks (cheap pamphlets) reached working class\n• By 1500: 20 million books; by 1600: 200 million\n• Literacy rates increased gradually\n\n2. RELIGIOUS TRANSFORMATION:\n• Martin Luther's 95 Theses (1517) spread in weeks — Protestant Reformation\n• People could read Bible in their own languages — didn't need priests to interpret\n• Church lost monopoly on religious knowledge\n• Religious wars followed — print spread conflicting views rapidly\n\n3. SCIENTIFIC REVOLUTION:\n• Copernicus, Galileo, Newton — ideas spread beyond their immediate circle\n• Scientists could build on each other's work — cumulative knowledge\n• Questioning received wisdom became possible\n\n4. POLITICAL CHANGE:\n• French Revolution pamphlets spread radical ideas\n• American Revolution — Common Sense (Thomas Paine) sold 100,000+ copies\n• Monarchies and aristocracy questioned\n\n5. CULTURAL CHANGE:\n• Novel as new literary form emerged — private reading\n• Women began reading and writing\n• Print created shared cultural references — national literature\n\n6. NEW ANXIETIES:\n• Church tried to control print — Index of Forbidden Books (1558)\n• Rulers feared seditious literature\n• Print spread both truth and falsehood\n\nCONCLUSION: Print was arguably the most revolutionary technology before the internet — transforming religious, scientific, political and cultural life in Europe."}
      ],
      passage: [
        {q:"'By the seventeenth century, as urban culture bloomed in China, the uses of print diversified. Print was no longer used just by scholar-officials. Merchants used print in their everyday life, as they collected trade information. Reading increasingly became a leisure activity. New readership preferred fictional narratives, poetry, autobiographies, romantic plays. Rich women began to read, and many began publishing their poetry and plays.'\n\n(a) What does this passage tell us about print culture in 17th century China?\n(b) How did print change the role of women in China?\n(c) Compare this with the role of print for women in 19th century India.\n(d) What does the phrase 'uses of print diversified' mean?",a:"(a) The passage tells us that in 17th century China:\n• Print had moved beyond its original purpose (civil service examination texts) to serve diverse needs\n• Urban middle class — merchants — used print for practical purposes (trade information)\n• A new leisure reading culture had emerged among the educated urban population\n• Literature diversified — fiction, poetry, autobiography, drama became popular genres\n• Print had become accessible enough for wealthy women to participate as readers AND writers\n• It shows that print's social impact was significant — changing leisure, gender roles, and class in Chinese society\n\n(b) Print changed women's role in China by:\n• Giving wealthy women access to literature and education outside the home\n• Creating opportunities for women to WRITE and PUBLISH their own works\n• Women's poetry and plays circulated in print — giving them public voice\n• Challenging the traditionally private, domestic role of women\n• Creating a community of women readers and writers\nHowever, this was limited to rich, educated women — poor women had no access to print culture\n\n(c) Comparison with 19th century India:\nSIMILARITIES:\n• In both: Educated upper-class women benefited from print culture\n• Both: Women began writing and publishing (though later in India)\n• Both: Print expanded women's mental world\n\nDIFFERENCES:\n• In India: Print was also used to DEBATE women's social conditions (Sati, child marriage, widow remarriage)\n• India: Social reformers (mostly men) used print to advocate women's rights\n• India: Women's own writing was more political (Tarabai Shinde) — directly challenging patriarchy\n• India: Colonial context added dimensions — nationalist women used print for independence movement too\n\n(d) 'Uses of print diversified' means that print was no longer used for just one purpose (government/religious texts) but served multiple functions:\n• Entertainment (novels, plays, poetry)\n• Business (trade information, contracts)\n• Education (beyond official examinations)\n• News and current affairs\n• Personal expression (autobiography, memoirs)\nThis shows print becoming integrated into everyday life, not just official/scholarly use."}
      ]
    }
  }
};
