const SOCIAL_CI_QUESTIONS_DB = {
  "social_ci": {

    "Resources and Development": {
      mcq: [
        {q:"Everything available in our environment which can be used to satisfy our needs is called a:",opts:["Natural gift","Resource","Commodity","Wealth"],ans:1},
        {q:"Resources on the basis of origin are classified as:",opts:["Renewable and non-renewable","Potential and developed","Biotic and abiotic","Individual and community"],ans:2},
        {q:"Which is an example of an abiotic resource?",opts:["Fish","Forest","Minerals","Livestock"],ans:2},
        {q:"Resources on the basis of exhaustibility are classified as:",opts:["Biotic and abiotic","Renewable and non-renewable","Individual and national","Potential and reserve"],ans:1},
        {q:"Solar energy is a __ resource:",opts:["Non-renewable","Biotic","Renewable","Potential"],ans:2},
        {q:"The Rio Earth Summit was held in:",opts:["1990","1992","1995","2000"],ans:1},
        {q:"'Development should take place without damaging the environment' defines:",opts:["Economic development","Sustainable development","Resource planning","Social development"],ans:1},
        {q:"Land degradation in India is mainly caused by:",opts:["Afforestation","Deforestation and overgrazing","Conservation","Crop rotation"],ans:1},
        {q:"The black soil of Deccan Plateau is also called:",opts:["Laterite soil","Regur soil","Alluvial soil","Red soil"],ans:1},
        {q:"Which soil is most suitable for growing cotton?",opts:["Red soil","Laterite soil","Black soil","Alluvial soil"],ans:2},
        {q:"Alluvial soil is most extensively found in:",opts:["Deccan Plateau","Northern Plains","Western Ghats","Rajasthan Desert"],ans:1},
        {q:"'Agenda 21' was adopted at which conference?",opts:["Kyoto Protocol","Rio Earth Summit 1992","Montreal Protocol","Paris Agreement"],ans:1},
        {q:"Laterite soil develops in areas with:",opts:["Low rainfall","High temperature and heavy seasonal rainfall","Cold climate","Semi-arid conditions"],ans:1},
        {q:"Resources owned by a community for collective use are called:",opts:["Individual resources","Community resources","National resources","International resources"],ans:1},
        {q:"The Brundtland Commission Report (1987) was titled:",opts:["Our Common Future","Agenda 21","Earth Summit","Limits to Growth"],ans:0},
        {q:"Which type of soil is found in the north-eastern states and hilly regions?",opts:["Alluvial soil","Black soil","Forest and mountain soil","Red and yellow soil"],ans:2},
        {q:"Soil erosion can be prevented by:",opts:["Deforestation","Overgrazing","Contour ploughing and terracing","Mining"],ans:2},
        {q:"'Slash and burn' agriculture leads to which problem?",opts:["Waterlogging","Soil erosion and land degradation","Salinisation","Urban sprawl"],ans:1},
        {q:"Resources which are surveyed and their quality and quantity have been determined are called:",opts:["Potential resources","Developed resources","Reserves","Stock"],ans:1},
        {q:"The process of transformation of material available in environment into resources involves:",opts:["Only nature","Only technology","Nature, technology and institutions","Only human labour"],ans:2}
      ],
      short: [
        {q:"What is a resource? How are resources classified on the basis of origin and exhaustibility?",a:"RESOURCE: Everything available in our environment which can be used to satisfy our needs, provided it is technologically accessible, economically feasible and culturally acceptable.\n\nON THE BASIS OF ORIGIN:\n• Biotic resources: Obtained from the biosphere and have life. Examples: forests, fish, livestock, human beings\n• Abiotic resources: Composed of non-living things. Examples: rocks, metals, minerals, water, air\n\nON THE BASIS OF EXHAUSTIBILITY:\n• Renewable resources: Can be renewed or reproduced by physical, chemical or mechanical processes. Examples: solar energy, wind energy, water, forests (if properly managed)\n• Non-renewable resources: Take millions of years to form and cannot be renewed quickly. Examples: coal, petroleum, minerals"},
        {q:"What is sustainable development? What happened at the Rio Earth Summit 1992?",a:"SUSTAINABLE DEVELOPMENT: Development that meets the needs of the present without compromising the ability of future generations to meet their own needs. It means 'development should take place without damaging the environment, and development in the present should not compromise with the needs of future generations.'\n\nRIO EARTH SUMMIT 1992:\n• Held in Rio de Janeiro, Brazil in June 1992\n• More than 100 heads of states attended\n• Addressed urgent problems of environmental protection and socio-economic development\n• Leaders signed the Declaration on Global Climatic Change and Biological Diversity\n• Agreed upon the concept of Sustainable Development\n• Adopted 'Agenda 21' — a global agenda for sustainable development in the 21st century"},
        {q:"Describe four types of soil found in India and their characteristics.",a:"1. ALLUVIAL SOIL:\n• Found in: Northern plains, river valleys\n• Characteristics: Very fertile, deposited by rivers (Indus, Ganga, Brahmaputra)\n• Crops: Rice, wheat, sugarcane, cotton, jute\n\n2. BLACK SOIL (Regur):\n• Found in: Deccan Plateau (Maharashtra, MP, Gujarat)\n• Characteristics: Fine texture, high moisture retention, rich in calcium, magnesium\n• Crops: Cotton (best), wheat, jowar, linseed\n\n3. RED AND YELLOW SOIL:\n• Found in: Odisha, Chhattisgarh, eastern MP, parts of AP\n• Characteristics: Red due to iron content, develops on crystalline rocks\n• Crops: Rice, wheat, pulses (less fertile)\n\n4. LATERITE SOIL:\n• Found in: Kerala, Karnataka, Tamil Nadu, Meghalaya, Odisha\n• Characteristics: Develops in high temperature + heavy rainfall areas, not very fertile, acidic\n• Crops: Tea, coffee, cashew, rubber (after adding manures)"},
        {q:"What is land degradation? What are its causes and how can it be conserved?",a:"LAND DEGRADATION: The reduction in the quality and productivity of land due to various activities.\n\nCAUSES:\n1. Deforestation — loss of tree cover leads to soil erosion\n2. Overgrazing — exposes soil to wind/water erosion\n3. Mining — creates pits, dumps waste, damages land\n4. Over-irrigation — leads to waterlogging and salinisation\n5. Industrialisation — effluents deposited on land\n6. Shifting cultivation (slash and burn)\n\nCONSERVATION MEASURES:\n1. Afforestation and shelter belts\n2. Control of overgrazing\n3. Proper management of mining activities\n4. Contour bunding and terracing on slopes\n5. Strip cropping and crop rotation\n6. Proper drainage to prevent waterlogging\n7. Treating effluents before disposal"}
      ],
      long: [
        {q:"Explain the importance of resource planning in India. What are the problems of indiscriminate resource use?",a:"RESOURCE PLANNING IN INDIA:\nIndia is rich in resources but their distribution is unequal. Resource planning is essential because:\n1. Some states are rich in certain resources but deficient in others\n2. Resources need to be used in a balanced, sustainable manner\n3. Planning ensures equitable distribution\n\nTHREE STAGES OF RESOURCE PLANNING:\n1. Identification and inventory of resources through surveys\n2. Evolving a planning structure with appropriate technology, skill and institutional framework\n3. Matching resource development plans with national development plans\n\nPROBLEMS OF INDISCRIMINATE RESOURCE USE:\n1. DEPLETION: Resources being consumed faster than they can be replenished\n2. INEQUALITY: Accumulation in few hands — divided society into 'haves' and 'have nots'\n3. ECOLOGICAL CRISIS: Global warming, ozone depletion, environmental pollution, land degradation\n4. LOSS FOR FUTURE GENERATIONS: Non-renewable resources once used cannot be recovered\n\nIMPORTANCE:\n• Ensures resources are available for current AND future generations\n• Prevents environmental damage\n• Promotes equitable access\n• Vital for national security and development\n• India needs to balance economic growth with conservation"}
      ],
      passage: [
        {q:"Read the following:\n\n'Sustainable economic development means development should take place without damaging the environment, and development in the present should not compromise with the needs of the future generations.' (Brundtland Commission, 1987)\n\n(a) What is the core principle of sustainable development?\n(b) Why is resource planning essential for sustainable development?\n(c) Give two examples of unsustainable resource use in India.\n(d) What was Agenda 21?",a:"(a) Core principle: Current development must meet present needs WITHOUT compromising the ability of future generations to meet their own needs. It means balancing economic growth with environmental protection.\n\n(b) Resource planning is essential because:\n• Resources are unevenly distributed\n• Without planning, resources are overexploited\n• It ensures resources are available for future generations\n• It prevents ecological imbalance\n\n(c) Examples of unsustainable resource use:\n1. Over-extraction of groundwater for irrigation — falling water table across India\n2. Deforestation for agriculture and industry — loss of forest cover and biodiversity\n\n(d) Agenda 21 was adopted at the Rio Earth Summit (1992). It is a global action plan for sustainable development in the 21st century. It addresses global problems like poverty, health, housing, pollution, managing fragile ecosystems. Each local government is supposed to create its own Local Agenda 21."}
      ]
    },

    "Forest and Wildlife Resources": {
      mcq: [
        {q:"India is one of the world's richest countries in terms of:",opts:["Mineral resources","Biological diversity","Water resources","Agricultural land"],ans:1},
        {q:"The Indian Wildlife Protection Act was implemented in:",opts:["1960","1965","1972","1980"],ans:2},
        {q:"Project Tiger was launched in:",opts:["1970","1973","1975","1980"],ans:1},
        {q:"Biosphere reserves are established to:",opts:["Allow hunting of some animals","Conserve biodiversity and promote research","Develop tourism only","Exploit forest resources"],ans:1},
        {q:"Which of the following is a critically endangered species in India?",opts:["Tiger","Elephant","Cheetah (already extinct)","Lion"],ans:2},
        {q:"Sacred groves are:",opts:["Government protected forests","Forest patches protected by local communities for religious reasons","Reserved forests","Plantation forests"],ans:1},
        {q:"The Chipko Movement was related to:",opts:["Water conservation","Protection of forests","Wildlife conservation","Soil conservation"],ans:1},
        {q:"Reserved forests are:",opts:["Open to all for any use","Most protected — no grazing or felling allowed without permission","Available for local use","Private forests"],ans:1},
        {q:"Which of the following is a Biosphere Reserve in India?",opts:["Corbett National Park","Sundarbans","Kaziranga","All of these"],ans:1},
        {q:"The Beej Bachao Andolan in Tehri region was about:",opts:["Saving seeds and traditional crop varieties","Saving forests","Saving water","Saving wildlife"],ans:0},
        {q:"Biodiversity is important because:",opts:["It provides food for humans only","It maintains ecological diversity and our life support systems","It has only aesthetic value","It is only important for research"],ans:1},
        {q:"India has approximately __ of world's biodiversity:",opts:["2%","8%","15%","20%"],ans:1},
        {q:"Community forests (Van Panchayats) for forest protection are common in:",opts:["Rajasthan","Uttarakhand (Himalayas)","Tamil Nadu","Kerala"],ans:1},
        {q:"The Bhoomi Sena movement for protection of nature is from:",opts:["Gujarat","Maharashtra","Rajasthan","Kerala"],ans:1},
        {q:"'Joint Forest Management' (JFM) programme involves:",opts:["Only government agencies","Only local communities","Both government and local communities","International agencies"],ans:2}
      ],
      short: [
        {q:"Why is conservation of forests and wildlife important?",a:"Conservation of forests and wildlife is important because:\n\n1. ECOLOGICAL BALANCE: Forests and wildlife maintain the ecological diversity and our life support systems — water, air and soil.\n\n2. GENETIC DIVERSITY: Preserves genetic diversity of plants and animals for better growth of species and breeding. Agriculture depends on traditional crop varieties; fisheries depend on aquatic biodiversity.\n\n3. OXYGEN AND CARBON: Forests absorb CO₂ and release O₂; regulate climate change.\n\n4. WATER CYCLE: Trees help maintain the water cycle, prevent floods, maintain groundwater.\n\n5. LIVELIHOODS: Millions of people (especially tribal communities) depend on forests for food, medicine, shelter and livelihood.\n\n6. HERITAGE AND CULTURE: Many species have cultural, religious and aesthetic value.\n\n7. MEDICINES: Many important medicines come from forest plants."},
        {q:"What are the different categories of forests in India based on protection?",a:"1. RESERVED FORESTS:\n• Most valuable and most protected category\n• More than half of total forest land is reserved\n• No grazing, felling or any other activities allowed without government permission\n\n2. PROTECTED FORESTS:\n• Forest land protected from further depletion\n• About one-third of total forest area\n• Government allows some activities with restrictions\n\n3. UNCLASSED FORESTS:\n• Other forests and wastelands\n• Owned by government, private individuals or communities\n• Least protected category\n\nNational Parks, Sanctuaries and Biosphere Reserves are established within reserved and protected forests for conservation of biodiversity."},
        {q:"What is the role of local communities in forest conservation? Give two examples.",a:"Local communities play a crucial role in forest conservation through traditional knowledge and collective action.\n\nEXAMPLES:\n1. SACRED GROVES: In many parts of India (Meghalaya, Rajasthan, Chhattisgarh, Uttarakhand), local communities protect patches of forest for religious reasons. No one is allowed to cut trees or harm wildlife here. These sacred groves are patches of forest dedicated to gods or spirits.\n\n2. BISHNOI COMMUNITY: The Bishnois of Rajasthan have been protecting forests and wildlife for centuries. Amrita Devi Bishnoi sacrificed her life in 1731 to protect Khejri trees. The community still actively conserves the blackbuck and other wildlife.\n\n3. CHIPKO MOVEMENT: Local people (especially women) in Uttarakhand hugged trees to prevent felling in the 1970s.\n\n4. JOINT FOREST MANAGEMENT (JFM): Involves local communities and government jointly protecting and benefiting from forests."}
      ],
      long: [
        {q:"Discuss the factors that have led to depletion of forests and wildlife in India. What conservation measures have been taken?",a:"FACTORS LEADING TO DEPLETION:\n\n1. EXPANSION OF AGRICULTURE: Forest land converted to farmland, especially during colonial period\n2. LARGE-SCALE DEVELOPMENT PROJECTS: Dams, industries, mining, roads destroy forest habitats\n3. COLONIAL EXPLOITATION: British cleared vast forests for timber, agriculture and railways\n4. POPULATION GROWTH: Increased demand for agricultural land, fuel wood, fodder\n5. OVERGRAZING: Destroys vegetation and prevents regeneration\n6. UNEQUAL ACCESS: Commercial interests of industry often override conservation needs\n7. FOREST FIRES: Both natural and man-made\n8. POACHING: Illegal hunting of endangered animals\n\nCONSERVATION MEASURES:\n1. Wildlife Protection Act 1972 — legal protection for endangered species\n2. Project Tiger (1973) — to protect tiger population\n3. National Parks and Wildlife Sanctuaries (over 600 in India)\n4. Biosphere Reserves — protect whole ecosystems\n5. Joint Forest Management Programme — community participation\n6. Affirmative action for tribal rights and community forests\n7. Sacred groves and traditional conservation practices\n8. Van Panchayats in Uttarakhand\n9. Beej Bachao Andolan in Tehri — saving seed diversity"}
      ],
      passage: [
        {q:"'Sacred groves are found in Meghalaya, Rajasthan, Himachal Pradesh and Karnataka. In Sariska Wildlife Sanctuary, villagers have fought to protect habitat from mining. In Alwar district of Rajasthan, 5 villages declared 1200 hectares of forest as Bhairodev Dakav Sonchuri.'\n\n(a) What are sacred groves?\n(b) What does the Bhairodev Dakav Sonchuri example show?\n(c) Why is community involvement in conservation important?\n(d) Name two wildlife conservation projects in India.",a:"(a) Sacred groves are patches of forest or trees dedicated to gods or spirits by local communities. These are protected for religious reasons. No one is allowed to cut trees or harm wildlife in sacred groves. They represent traditional nature conservation.\n\n(b) The Bhairodev Dakav Sonchuri example shows that local communities can take the initiative to protect forests even without government orders. The villagers themselves declared the forest a protected sanctuary with their own rules — no hunting, no commercial felling — showing the power of community-led conservation.\n\n(c) Community involvement is important because:\n• Local people have traditional knowledge of the ecosystem\n• They have a direct stake in the forest's survival\n• Government alone cannot monitor every area\n• Communities can enforce rules more effectively at local level\n\n(d) Two wildlife conservation projects:\n1. Project Tiger (launched 1973) — to protect the tiger\n2. Project Elephant — to protect elephant corridors and habitats"}
      ]
    },

    "Water Resources": {
      mcq: [
        {q:"What fraction of Earth's surface is covered with water?",opts:["One-fourth","Half","Three-fourth","All"],ans:2},
        {q:"The largest consumer of water in India is:",opts:["Industry","Domestic use","Irrigated agriculture","Drinking"],ans:2},
        {q:"The multipurpose river valley project that became 'the temple of modern India':",opts:["Bhakra-Nangal Dam","Hirakud Dam","Sardar Sarovar","Tungabhadra"],ans:0},
        {q:"The Sardar Sarovar Dam is built on which river?",opts:["Mahanadi","Narmada","Cauvery","Krishna"],ans:1},
        {q:"Ancient Indian system of collecting rainwater in tanks is called:",opts:["Kul","Khadins","Baolis","All of these"],ans:2},
        {q:"Bamboo drip irrigation is a traditional practice in:",opts:["Rajasthan","Meghalaya","Kerala","Punjab"],ans:1},
        {q:"The Inundation channels (irrigation) were used in:",opts:["Punjab","Rajasthan","Bihar","Tamil Nadu"],ans:0},
        {q:"Multipurpose dams are opposed because they:",opts:["Are expensive to build","Displace local communities and damage ecosystems","Produce too much electricity","Waste water"],ans:1},
        {q:"The technique of roof-top rainwater harvesting is popular in:",opts:["Punjab","Rajasthan","Tamil Nadu (especially Chennai)","Assam"],ans:2},
        {q:"The 'Guls' or 'Kuls' are traditional irrigation systems of:",opts:["Western Himalayas","Eastern India","Tamil Nadu","Rajasthan"],ans:0},
        {q:"Water scarcity in India is mainly caused by:",opts:["Less rainfall","Over-exploitation, excessive use and unequal access","Lack of rivers","Only drought"],ans:1},
        {q:"The Narmada Bachao Andolan was a movement against:",opts:["Water pollution","Construction of Sardar Sarovar Dam","Deforestation","Mining"],ans:1},
        {q:"Tankas are underground tanks for storing rainwater found in:",opts:["Meghalaya","Punjab","Western Rajasthan","Maharashtra"],ans:2},
        {q:"The hydrological cycle ensures water is a:",opts:["Non-renewable resource","Renewable resource","Biotic resource","Abiotic resource only"],ans:1},
        {q:"'Khadins' and 'Johads' are traditional water harvesting systems of:",opts:["Meghalaya","Rajasthan","Bihar","Kerala"],ans:1}
      ],
      short: [
        {q:"What are multipurpose river valley projects? What are their advantages and disadvantages?",a:"MULTIPURPOSE PROJECTS: Dams built across rivers for multiple purposes simultaneously.\n\nADVANTAGES:\n1. Irrigation — provide water to dry areas year-round\n2. Flood control — regulate river flow\n3. Hydroelectric power generation\n4. Navigation — reservoirs can be used for navigation\n5. Drinking water supply\n6. Recreation and tourism\n7. Inland fisheries development\n\nDISADVANTAGES (why Nehru's 'temple of modern India' view is questioned):\n1. Displacement of local communities — thousands displaced without proper rehabilitation\n2. Submerge agricultural land and forests\n3. Affect aquatic ecosystems\n4. Cause submergence of habitats and biodiversity\n5. Cause disputes between states over water sharing\n6. Cause earthquake risk (reservoir-induced seismicity)\n7. Increase in social inequalities — benefits not equally distributed\n\nNarmada Bachao Andolan challenged Sardar Sarovar Dam for these reasons."},
        {q:"What is rainwater harvesting? Describe any three traditional methods used in India.",a:"RAINWATER HARVESTING: The technique of collecting and storing rainwater at the point of rainfall or surface runoff to meet water demands.\n\nTRADITIONAL METHODS:\n\n1. TANKAS (Western Rajasthan): Underground cylindrical tanks to store rainwater collected from rooftops. Connected to rooftop by pipes. Water is clean and cool; used in drought. Found in most traditional houses in desert areas.\n\n2. BAMBOO DRIP IRRIGATION (Meghalaya): 200-year-old system. Bamboo pipes divert river/spring water to fields. Precise water delivery to plants. Used to grow black pepper.\n\n3. KULS/GULS (Western Himalayas): Diversion channels built in hilly areas to direct meltwater/stream water to terraced fields.\n\n4. BAOLIS/STEPWELLS: Ancient wells with steps, found in Rajasthan and Delhi. Store water in deep wells accessible year-round.\n\n5. ROOF-TOP HARVESTING (Tamil Nadu): Rainwater from rooftops channeled through pipes into storage tanks or used to recharge groundwater."},
        {q:"Explain water scarcity. What are its main causes in India?",a:"WATER SCARCITY: The shortage of water relative to the demand for it. It occurs when freshwater supply is insufficient to meet needs.\n\nMAIN CAUSES IN INDIA:\n1. LARGE AND GROWING POPULATION: More people require more water for drinking, cooking, sanitation AND food production\n2. OVER-EXPLOITATION: Excessive extraction of groundwater for irrigation → falling water tables\n3. UNEQUAL ACCESS: Water is available but not equally accessible to all social groups\n4. IRRIGATED AGRICULTURE: Largest consumer of water — uses enormous amounts for crops\n5. RAPID URBANISATION: More water needed for cities; paved surfaces reduce groundwater recharge\n6. POLLUTION: Rivers and groundwater polluted, reducing usable water supply\n7. SEASONAL VARIABILITY: Rainfall concentrated in monsoon; dry seasons face scarcity\n8. CLIMATE CHANGE: Changing rainfall patterns, melting glaciers affect water availability"}
      ],
      long: [
        {q:"Why are multipurpose projects controversial in India? Discuss with examples.",a:"Multipurpose projects are called 'Temples of Modern India' by Nehru — symbols of development. However, they are CONTROVERSIAL because:\n\nNEGATIVE IMPACTS:\n1. DISPLACEMENT: Sardar Sarovar Dam displaced 320,000 people (mainly tribal communities). Proper rehabilitation was not provided.\n\n2. FOREST AND HABITAT LOSS: Reservoirs submerge large areas of forest and wildlife habitats.\n\n3. AGRICULTURE LOSS: Fertile agricultural land submerged under water.\n\n4. ECOLOGICAL DAMAGE: Dams regulate natural flow → affect aquatic ecosystem, fish migration, change in flood plains.\n\n5. EARTHQUAKE RISK: Heavy water in reservoirs can trigger earthquakes (reservoir-induced seismicity).\n\n6. INTER-STATE DISPUTES: Kaveri water dispute between Karnataka and Tamil Nadu; Narmada dispute.\n\n7. SOCIAL INEQUALITIES: Benefits (electricity, irrigation) often go to urban areas and richer farmers, while poor displaced communities bear the costs.\n\nNARMADA BACHAO ANDOLAN:\nMedha Patkar led movement against Sardar Sarovar Dam → raised issues of displacement of tribal people and lack of proper rehabilitation.\n\nCONCLUSION: While dams provide benefits (irrigation, power, flood control), they must balance development with environmental and social justice. Greater community participation and proper rehabilitation are needed."}
      ],
      passage: [
        {q:"'In Rajasthan, nearly all the houses traditionally had underground tanks or tankas for storing drinking water. The tanks could be as large as a big room. The tanks were part of well-developed rooftop rainwater harvesting system. The tankas were built inside the main house, underground, to keep the water cool. The opening of the tank was kept covered.'\n\n(a) What are tankas? Where are they found?\n(b) Why was the opening of the tank kept covered?\n(c) Why was rainwater harvesting important in Rajasthan?\n(d) Name any two other traditional water harvesting methods in India.",a:"(a) Tankas are underground cylindrical tanks used to store rainwater collected from rooftops. They are found in the houses of western Rajasthan (desert regions like Barmer, Jaisalmer). They are part of a well-developed rooftop rainwater harvesting system.\n\n(b) The opening of the tank was kept covered to:\n• Prevent contamination of water by dust, insects and animals\n• Keep the water clean and cool (underground stays cooler)\n• Prevent evaporation of stored water\n\n(c) Rainwater harvesting was crucial in Rajasthan because:\n• It is a semi-arid/desert region with very low rainfall\n• Rivers and groundwater sources are scarce\n• During droughts, tankas were the only source of drinking water\n• People could survive months without other water sources\n\n(d) Two other traditional water harvesting methods:\n1. Kuls/Guls — diversion channels in the Western Himalayas\n2. Bamboo drip irrigation — in Meghalaya\n(OR: Baolis/stepwells in Rajasthan and Delhi; Johads in Rajasthan)"}
      ]
    },

    "Agriculture": {
      mcq: [
        {q:"India is primarily a __ country:",opts:["Industrial","Agricultural","Commercial","Service"],ans:1},
        {q:"'Slash and burn' agriculture is also known as in north-eastern India as:",opts:["Rabi","Jhumming","Kharif","Zaid"],ans:1},
        {q:"Crops grown in winter season (October-March) are called:",opts:["Kharif crops","Zaid crops","Rabi crops","Plantation crops"],ans:2},
        {q:"Crops grown in summer (March-June) are called:",opts:["Kharif","Rabi","Zaid","Cash crops"],ans:2},
        {q:"Rice is a __ crop:",opts:["Rabi","Zaid","Kharif","Plantation"],ans:2},
        {q:"Wheat is a __ crop:",opts:["Kharif","Zaid","Rabi","Cash"],ans:2},
        {q:"The Green Revolution in India led to increase in production of:",opts:["Rice and wheat","Cotton and jute","Tea and coffee","Pulses and oilseeds"],ans:0},
        {q:"Which state is the leading producer of jute in India?",opts:["Assam","West Bengal","Bihar","Odisha"],ans:1},
        {q:"India is the largest producer and consumer of __ in the world:",opts:["Rice","Wheat","Pulses","Cotton"],ans:2},
        {q:"The crop that is used both as food and fodder is:",opts:["Rice","Jowar","Wheat","Cotton"],ans:1},
        {q:"Sugarcane is grown as a __ crop:",opts:["Rabi","Kharif","Plantation","Both rabi and kharif"],ans:1},
        {q:"India is the second largest producer of __ in the world:",opts:["Tea","Coffee","Rice","Cotton"],ans:0},
        {q:"Rubber is mainly grown in which states of India?",opts:["Assam and West Bengal","Kerala, Tamil Nadu and Karnataka","Punjab and Haryana","Rajasthan and Gujarat"],ans:1},
        {q:"'White Revolution' refers to increase in production of:",opts:["Rice","Cotton","Milk","Sugar"],ans:2},
        {q:"National Horticulture Mission was launched to promote production of:",opts:["Wheat and rice","Fruits and vegetables","Cotton and jute","Tea and coffee"],ans:1},
        {q:"The Bhoodan-Gramdan movement was associated with:",opts:["Soil conservation","Land reforms and redistribution","Water harvesting","Green Revolution"],ans:1},
        {q:"Commercial farming requires:",opts:["Manual labour only","Higher doses of inputs — seeds, fertilizers, pesticides, machines","Subsistence level inputs","Traditional methods only"],ans:1},
        {q:"Mixed farming involves:",opts:["Growing only cash crops","Cultivation of crops and raising livestock simultaneously","Only food crops","Only plantation crops"],ans:1},
        {q:"India ranks __ in world in terms of total arable land:",opts:["First","Second","Third","Fifth"],ans:1},
        {q:"Which crop is called the 'Golden Fibre'?",opts:["Cotton","Silk","Jute","Flax"],ans:2}
      ],
      short: [
        {q:"What is the difference between subsistence farming and commercial farming?",a:"SUBSISTENCE FARMING:\n• Farming primarily to meet the needs of the farmer's family\n• Uses primitive tools and family/community labour\n• Small land holdings\n• Low capital inputs\n• Examples: Primitive subsistence (jhumming), intensive subsistence farming\n• Output consumed by farmer; little or nothing sold\n\nCOMMERCIAL FARMING:\n• Farming primarily for selling in market\n• Uses modern technology — HYV seeds, chemical fertilisers, pesticides, machinery\n• Large land holdings\n• High capital investment\n• Different regions specialize in different crops based on suitability\n• Output is sold — profit-oriented\n• Examples: Rice and wheat farming in Punjab, cotton in Maharashtra, tea/coffee plantations\n\nKey difference: PURPOSE — subsistence for self-consumption; commercial for market sale."},
        {q:"What are kharif, rabi and zaid crops? Give two examples of each.",a:"KHARIF CROPS:\n• Season: Sown in June-July (beginning of monsoon), harvested September-October\n• Require: Warm climate, good rainfall\n• Examples: Rice, maize, jowar, bajra, cotton, sugarcane, groundnut, jute, soybean\n\nRABI CROPS:\n• Season: Sown in October-November, harvested March-April (winter)\n• Require: Cool growing season, warm and dry climate at ripening\n• Moisture available from winter rains (western disturbances)\n• Examples: Wheat, barley, peas, mustard, gram (chickpea)\n\nZAID CROPS:\n• Season: Short summer season between rabi and kharif (March-June)\n• Require: Irrigation (high temperature, long day length)\n• Examples: Watermelon, musk melon, cucumber, vegetables, fodder crops"},
        {q:"Describe the importance of rice cultivation in India.",a:"RICE — MOST IMPORTANT FOOD CROP:\n• Staple food for majority of Indians, especially in eastern, southern and north-eastern India\n• Kharif crop requiring: High temperature (above 25°C), high humidity, annual rainfall above 100 cm\n• Grown in water-logged conditions (paddy fields)\n\nMAJOR PRODUCING STATES:\nWest Bengal, Uttar Pradesh, Andhra Pradesh, Punjab, Tamil Nadu, Bihar, Odisha\n\nINNOVATIONS:\n• Green Revolution introduced HYV seeds → dramatic increase in production\n• Multiple cropping — 2-3 crops per year in some areas\n\nIMPORTANCE:\n• Provides food security for 1.4 billion people\n• Major employer in rural India\n• India is one of world's top producers and exporters\n• Cultural significance — central to food traditions of South and East India"},
        {q:"What is the Green Revolution? What were its advantages and disadvantages?",a:"GREEN REVOLUTION: Introduction of High Yielding Variety (HYV) seeds of wheat and rice in the 1960s-70s, combined with increased use of chemical fertilisers, pesticides and irrigation.\n\nADVANTAGES:\n1. Dramatic increase in food grain production (especially wheat and rice)\n2. India became self-sufficient in food grains\n3. Reduced dependence on food imports\n4. Increased farmers' income (initially)\n\nDISADVANTAGES:\n1. REGIONAL IMBALANCE: Benefits concentrated mainly in Punjab, Haryana and western UP\n2. ENVIRONMENTAL DAMAGE: Excessive use of chemical fertilisers and pesticides → soil and water pollution\n3. GROUNDWATER DEPLETION: Over-irrigation leading to falling water tables\n4. SOIL DEGRADATION: Continuous monoculture and chemicals reduced soil fertility\n5. SOCIAL INEQUALITY: Small farmers couldn't afford HYV inputs; benefits went to large farmers\n6. NEGLECT OF OTHER CROPS: Focus on wheat and rice; pulses, oilseeds neglected"}
      ],
      long: [
        {q:"Describe the major plantation crops of India — tea, coffee and rubber. Include their growing conditions, major producing states and importance.",a:"1. TEA:\nGrowing conditions:\n• Temperature: 20-30°C with frost-free conditions\n• Rainfall: 150-250 cm, well distributed throughout year\n• Soil: Deep, fertile well-drained soil, rich in humus\n• Slopes preferred (water doesn't stagnate)\n\nMajor producing states: Assam, West Bengal (Darjeeling and Jalpaiguri), Tamil Nadu, Kerala\nIndia is SECOND LARGEST producer in world (China is first) and largest exporter\n\n2. COFFEE:\nGrowing conditions:\n• Temperature: 15-28°C\n• Rainfall: 150-250 cm\n• Shade trees needed\n• Well-drained soil\n\nArabica variety (superior quality) introduced from Yemen\nMajor producing states: Karnataka (Coorg/Baba Budan Hills), Kerala, Tamil Nadu\nIndia mainly produces Arabica coffee\n\n3. RUBBER:\nGrowing conditions:\n• Equatorial climate — hot and wet throughout year\n• Temperature: Above 25°C\n• Rainfall: 200 cm, evenly distributed\n• Deep, well-drained soil\n\nMajor producing states: Kerala (70%), Tamil Nadu, Karnataka, Andaman & Nicobar Islands\nIndia is FIFTH LARGEST producer in world\n\nIMPORTANCE:\n• All are plantation crops with high commercial value\n• Major export earners\n• Provide employment to millions in hilly regions\n• India known globally for quality tea and coffee"}
      ],
      passage: [
        {q:"'Two-thirds of India's population is engaged in agricultural activities. Agriculture is a primary activity which produces most of the food that we consume. Besides food grains, it also produces raw material for various industries.'\n\n(a) Why is agriculture called a 'primary activity'?\n(b) Name two industries that depend on agricultural raw materials.\n(c) What are the main types of farming practised in India?\n(d) What is 'jhumming' and where is it practised?",a:"(a) Agriculture is called a primary activity because it involves direct extraction/collection from nature (land). Primary activities are those that directly use natural resources — farming, fishing, forestry and mining. Agriculture directly produces food from land using natural soil, water and sunlight.\n\n(b) Two industries dependent on agricultural raw materials:\n1. Textile industry — uses cotton, jute and silk from agriculture\n2. Sugar industry — uses sugarcane\n(Other examples: Oil mills use oilseeds; tea/coffee processing industries; rubber industry)\n\n(c) Main types of farming in India:\n1. Primitive subsistence farming (slash and burn)\n2. Intensive subsistence farming\n3. Commercial farming\n4. Plantation farming\n5. Mixed farming\n\n(d) Jhumming is the local name for 'slash and burn' agriculture in north-eastern states of India (Assam, Meghalaya, Mizoram, Nagaland). Farmers clear a patch of forest by cutting and burning trees, cultivate for a few years until soil fertility decreases, then shift to another patch. Also called shifting cultivation. It is known as Pamlou in Manipur and Dipa in Bastar, Chhattisgarh."}
      ]
    },

    "Minerals and Energy Resources": {
      mcq: [
        {q:"Minerals are formed by:",opts:["Human activities","Geological processes over millions of years","Chemical mixing","Biological processes"],ans:1},
        {q:"Minerals found in igneous and metamorphic rocks often occur in:",opts:["Veins and lodes","Alluvial deposits","Sedimentary beds","Ocean beds"],ans:0},
        {q:"Which state is the largest producer of iron ore in India?",opts:["Goa","Jharkhand","Odisha","Karnataka"],ans:2},
        {q:"India has approximately __ of world's total iron ore reserves:",opts:["5%","10%","25%","1%"],ans:2},
        {q:"Bauxite is the ore of which metal?",opts:["Iron","Copper","Aluminium","Zinc"],ans:2},
        {q:"Mica is mainly found in which state?",opts:["Gujarat","Maharashtra","Jharkhand and Rajasthan","Tamil Nadu"],ans:2},
        {q:"Manganese is mainly used in:",opts:["Manufacturing steel and ferro-manganese alloy","Making aeroplanes","Electrical wiring","Fertilisers"],ans:0},
        {q:"The Kolar Gold Fields are located in:",opts:["Rajasthan","Jharkhand","Karnataka","Tamil Nadu"],ans:2},
        {q:"Which is a conventional source of energy?",opts:["Solar energy","Wind energy","Coal","Tidal energy"],ans:2},
        {q:"India's most abundant energy resource is:",opts:["Petroleum","Natural gas","Coal","Uranium"],ans:2},
        {q:"The Mumbai High offshore oilfield is located in:",opts:["Arabian Sea","Bay of Bengal","Indian Ocean","Lakshadweep Sea"],ans:0},
        {q:"Thermal power plants use __ to generate electricity:",opts:["Water","Wind","Coal or petroleum","Nuclear fuel"],ans:2},
        {q:"Biogas is produced from:",opts:["Coal","Organic waste/dung/plant material","Petroleum","Nuclear reactions"],ans:1},
        {q:"India's first nuclear power station was established at:",opts:["Tarapur","Kalpakkam","Narora","Rawatbhata"],ans:0},
        {q:"Tidal energy is generated from:",opts:["Wind over sea","Rise and fall of tides","Ocean waves","Ocean thermal gradient"],ans:1},
        {q:"Jharia in Jharkhand is famous for:",opts:["Iron ore","Bauxite","Coal fields","Petroleum"],ans:2},
        {q:"Solar energy is most important in areas like:",opts:["Assam","Rajasthan and Gujarat (high solar radiation)","Kerala","West Bengal"],ans:1},
        {q:"Which state has the largest reserves of copper?",opts:["Rajasthan","Jharkhand","Madhya Pradesh","Gujarat"],ans:0},
        {q:"Petroleum is found in __ rock structures:",opts:["Igneous","Metamorphic","Sedimentary anticlines","All types"],ans:2},
        {q:"The largest producer of wind energy in India is:",opts:["Gujarat","Rajasthan","Tamil Nadu","Andhra Pradesh"],ans:2}
      ],
      short: [
        {q:"How are minerals classified based on their chemical and physical properties? Give examples.",a:"FERROUS MINERALS (contain iron):\n• Examples: Iron ore, manganese, nickel, cobalt\n• Form the backbone of industrial development\n• India has large reserves; is a major exporter of iron ore\n\nNON-FERROUS MINERALS (don't contain iron):\n• Examples: Copper, bauxite (aluminium ore), gold, silver, lead, zinc\n• Essential for various industries\n\nNON-METALLIC MINERALS (neither metals):\n• Examples: Limestone, mica, gypsum, salt\n• Limestone: Used in cement and chemical industries\n• Mica: Used in electrical and electronic industries\n\nENERGY MINERALS:\n• Coal, petroleum, natural gas, uranium\n• Used as fuel and for generating electricity\n\nBased on MODE OF OCCURRENCE:\n• In veins and lodes (igneous/metamorphic rocks)\n• In sedimentary rocks (coal, gypsum, limestone)\n• In alluvial deposits (gold, tin)"},
        {q:"Describe the importance of coal in India's economy. What are its types?",a:"COAL — MOST ABUNDANT ENERGY RESOURCE OF INDIA:\n• Provides 65% of India's commercial energy\n• Used for: Electricity generation (thermal power plants), industries (steel, cement), railways, domestic use\n\nTYPES (in order of carbon content and quality):\n1. ANTHRACITE: Highest quality, highest carbon content (>80%), very hard, found in small quantities\n2. BITUMINOUS: Most commonly used, used in metallurgy, iron/steel industry, thermal power\n3. LIGNITE: Low carbon, high moisture content, found mainly in Neyveli (Tamil Nadu)\n4. PEAT: Lowest carbon content, poor quality\n\nMAJOR COALFIELDS:\n• Gondwana coal: Damodar Valley (Jharkhand, West Bengal), Jharia, Raniganj, Bokaro\n• Tertiary coal: Assam, Meghalaya, Nagaland, Arunachal Pradesh; Neyveli (Tamil Nadu)\n\nMAJOR PRODUCERS: Jharkhand, Odisha, West Bengal, Chhattisgarh, Madhya Pradesh"},
        {q:"Describe any three non-conventional energy sources in India.",a:"1. SOLAR ENERGY:\n• India — a tropical country with 300+ sunny days per year\n• Rajasthan and Gujarat have highest solar potential\n• Used in: Solar cookers, heaters, photovoltaic cells (electricity)\n• Solar Mission aims to make India world's largest solar energy producer\n• Advantage: Pollution-free, renewable, free fuel\n\n2. WIND ENERGY:\n• India is 5th largest wind power producer in world\n• Wind farms in Tamil Nadu (largest — Muppandal), Rajasthan, Maharashtra, Gujarat, Karnataka, Kerala\n• India has potential of 45,000 MW wind power\n• Advantage: Renewable, no pollution, no fuel cost\n\n3. BIOGAS:\n• Produced from organic waste (plant/animal waste, sewage)\n• Biogas plants (gobar gas plants) in rural areas\n• Used for: Cooking fuel, electricity generation\n• National Biogas and Manure Management Programme promotes its use\n• Advantage: Converts waste to energy; by-product (slurry) is excellent fertiliser"}
      ],
      long: [
        {q:"Distinguish between conventional and non-conventional sources of energy. Why is India promoting non-conventional energy?",a:"CONVENTIONAL SOURCES:\n• Coal, petroleum, natural gas, firewood, nuclear energy\n• Used since long time; familiar technology\n• Mostly NON-RENEWABLE (coal, petroleum, gas)\n• Polluting — produce CO₂, SO₂, greenhouse gases\n• Being rapidly depleted\n• Concentrated in specific regions\n\nNON-CONVENTIONAL SOURCES:\n• Solar, wind, tidal, geothermal, biogas, ocean thermal energy\n• Mostly RENEWABLE and inexhaustible\n• Clean/pollution-free (most)\n• Distributed — available everywhere\n• Newer technology, higher initial costs\n• Lower running costs\n\nWHY INDIA IS PROMOTING NON-CONVENTIONAL:\n1. DEPLETION: Fossil fuels (coal, petroleum) are rapidly being exhausted\n2. ENVIRONMENT: Burning fossil fuels causes air pollution and climate change\n3. ENERGY SECURITY: India imports 80%+ of petroleum — drain on foreign exchange\n4. RURAL NEEDS: Non-conventional energy can serve remote areas without electricity grid\n5. INDIA'S POTENTIAL: India has enormous potential — abundant sunlight, wind, biomass\n6. GLOBAL COMMITMENTS: Climate change agreements require reducing fossil fuel use\n7. EMPLOYMENT: Renewable energy sector creates jobs\n\nGOVERNMENT INITIATIVES: National Solar Mission, National Wind Mission, Biogas plants, targets for renewable energy in National Energy Policy."}
      ],
      passage: [
        {q:"Study the following about energy resources:\n\n'India imports more than 80% of its petroleum requirement. The reserves are limited. At the same time, India has immense potential for solar, wind and tidal energy. The National Solar Mission aims to develop India as a global leader in solar energy.'\n\n(a) Why is India's dependence on petroleum imports a problem?\n(b) What are the major petroleum-producing regions in India?\n(c) Why is solar energy particularly suitable for India?\n(d) What is the significance of the National Solar Mission?",a:"(a) India's dependence on petroleum imports is a problem because:\n• It drains huge amounts of foreign exchange (billions of dollars annually)\n• Makes India vulnerable to global oil price fluctuations\n• Creates energy security risk — any disruption in supply affects the entire economy\n• Increases trade deficit and weakens the economy\n\n(b) Major petroleum-producing regions:\n• Mumbai High (offshore, Arabian Sea) — largest producer\n• Gujarat — Ankeleshwar, Kalol\n• Assam — Digboi (oldest oilfield in Asia, 1867), Naharkatiya, Moran\n• Rajasthan — Barmer (recent discovery)\n• Krishna-Godavari basin\n\n(c) Solar energy is suitable for India because:\n• India is a tropical country with 300+ sunny days per year\n• Receives 5-7 kWh/m² of solar radiation daily\n• Vast arid areas (Rajasthan, Gujarat) with very high solar radiation\n• Can serve rural areas not connected to grid\n• Abundant free 'fuel' — no fuel costs after installation\n\n(d) Significance of National Solar Mission:\n• Part of National Action Plan on Climate Change\n• Aims to make India a global leader in solar energy\n• Target: 100 GW solar by 2022 (later extended)\n• Reduces dependence on imported fossil fuels\n• Creates green jobs and clean energy for millions"}
      ]
    },

    "Manufacturing Industries": {
      mcq: [
        {q:"Manufacturing industries transform __ into products of higher value:",opts:["Services","Raw materials","Finished goods","Machines"],ans:1},
        {q:"The 'Manchester of India' is:",opts:["Mumbai","Ahmedabad","Surat","Chennai"],ans:1},
        {q:"The iron and steel industry is a __ industry:",opts:["Agro-based","Forest-based","Mineral-based","Marine-based"],ans:2},
        {q:"TISCO (Tata Iron and Steel Company) is located at:",opts:["Bhilai","Durgapur","Jamshedpur","Rourkela"],ans:2},
        {q:"The Bhilai Steel Plant was set up with the help of:",opts:["USA","UK","Soviet Union (USSR)","Germany"],ans:2},
        {q:"Which Indian city is known as the Silicon Valley of India?",opts:["Mumbai","Delhi","Bengaluru (Bangalore)","Hyderabad"],ans:2},
        {q:"India ranks __ in world in cotton textile production:",opts:["First","Second","Third","Fifth"],ans:1},
        {q:"The first cotton textile mill was set up in India in which city?",opts:["Ahmedabad","Surat","Mumbai (Bombay) in 1854","Chennai"],ans:2},
        {q:"The chemical industry in India ranks __ in Asia:",opts:["First","Third","Fifth","Second"],ans:1},
        {q:"India is the __ largest producer of cement in the world:",opts:["Largest","Second","Third","Fifth"],ans:1},
        {q:"Which is the largest industry in India in terms of employment?",opts:["Iron and steel","Textile industry","IT industry","Chemical industry"],ans:1},
        {q:"Sugar industry is mainly concentrated in:",opts:["Punjab and Haryana","UP and Maharashtra","Bihar and West Bengal","Gujarat and Rajasthan"],ans:1},
        {q:"Which type of industry is the automobile industry?",opts:["Agro-based","Forest-based","Mineral-based (engineering)","Marine-based"],ans:2},
        {q:"Industrial pollution refers to:",opts:["Noise from factories only","Air, water, land and noise pollution from industries","Only water pollution","Only air pollution"],ans:1},
        {q:"Effluent Treatment Plants (ETPs) are used to:",opts:["Treat factory waste water before discharge","Generate electricity","Produce chemicals","Recycle metals"],ans:0}
      ],
      short: [
        {q:"Explain the importance of manufacturing industries in India's development.",a:"IMPORTANCE OF MANUFACTURING INDUSTRIES:\n\n1. TRANSFORMATION OF ECONOMY: Changes from an agrarian economy to industrial and service economy — essential for development.\n\n2. EMPLOYMENT: Provides employment to millions — both directly in factories and indirectly in supporting services.\n\n3. GDP CONTRIBUTION: Manufacturing contributes significantly to India's GDP — reduces dependence on primary sector.\n\n4. SELF-RELIANCE: Reduces dependence on foreign goods — India makes steel, textiles, chemicals, electronics.\n\n5. RAW MATERIAL UTILISATION: Processes India's abundant natural resources (iron ore, cotton, sugarcane) into valuable products.\n\n6. EXPORTS: Manufactured goods (textiles, software, chemicals, engineering goods) earn foreign exchange.\n\n7. MULTIPLIER EFFECT: Growth of one industry stimulates others (steel industry stimulates automobile, construction).\n\n8. POVERTY REDUCTION: Industrial growth provides jobs and raises living standards."},
        {q:"Why is the iron and steel industry called a 'basic' industry?",a:"IRON AND STEEL — A BASIC/KEY INDUSTRY because:\n\nAll other industries depend on it for their machinery and infrastructure:\n• Machinery for all industries is made of steel\n• Construction (buildings, bridges, railways) uses steel\n• Automobiles, ships, aircraft all use steel\n• Agricultural machinery (tractors, ploughs) uses steel\n\nCHAIN OF DEPENDENCY:\nSteel → Tools/Machines → ALL other industries\n\nLOCATION FACTORS:\n• Raw materials: Iron ore, coal (coking), manganese, limestone — ideally nearby\n• Water: Large quantities needed for cooling\n• Transport: Railways to bring raw materials and ship products\n• Labour: Both skilled and unskilled\n• Capital: Very high initial investment\n\nMAJOR STEEL PLANTS:\n• Jamshedpur (TISCO) — private sector, oldest\n• Bhilai (SAIL) — with Soviet help\n• Durgapur — with UK help\n• Rourkela — with German help\n• Bokaro — with Soviet help"},
        {q:"What is the significance of the IT and software industry in India?",a:"IT AND SOFTWARE INDUSTRY — INDIA'S STRENGTH:\n\n1. EXPORT EARNINGS: India is world's largest software exporter — earns $100+ billion annually in software exports\n\n2. EMPLOYMENT: Employs millions of educated workers — reduced 'brain drain' by providing high-paying jobs in India\n\n3. BENGALURU — 'SILICON VALLEY OF INDIA': Major hub with world-class companies and talent\n\n4. OTHER HUBS: Hyderabad ('Cyberabad'), Mumbai, Chennai, Kolkata, Pune, Ahmedabad\n\n5. ADVANTAGES India has:\n• Large pool of English-speaking, technically qualified professionals\n• Lower labour costs compared to USA/Europe\n• Time zone advantage (24-hour service to USA/Europe)\n• Strong mathematical and scientific tradition\n\n6. SPILLOVER BENEFITS:\n• Growth of infrastructure (airports, roads, housing)\n• Rise of support services (food, transport, retail)\n• Attracted foreign investment\n• Increased tax revenues for government"}
      ],
      long: [
        {q:"Discuss the environmental degradation caused by industries and the measures to control it.",a:"ENVIRONMENTAL DEGRADATION BY INDUSTRIES:\n\nAIR POLLUTION:\n• Smoke and harmful gases (SO₂, CO₂, CO, NO) from factories\n• Suspended particles cause respiratory diseases\n• Thermal power plants, steel plants, chemical industries major culprits\n\nWATER POLLUTION:\n• Industries discharge untreated effluents (waste water) into rivers\n• Contains toxic chemicals, dyes, heavy metals, acids\n• Rivers (Ganga, Yamuna) severely polluted near industrial areas\n• Affects aquatic life and drinking water quality\n\nLAND POLLUTION:\n• Industrial waste (slag, ash, chemicals) dumped on land\n• Mining operations create massive pits and waste dumps\n• Toxic waste leaches into soil\n\nNOISE POLLUTION:\n• Machinery and equipment in factories\n• Affects workers' health — hearing damage, stress\n\nTHERMAL POLLUTION:\n• Hot water discharged from thermal/nuclear power plants into rivers\n• Kills aquatic organisms\n\nCONTROL MEASURES:\n1. Effluent Treatment Plants (ETPs) — treat wastewater before discharge\n2. Use of smokeless fuels and clean technologies\n3. Tall chimneys with electrostatic precipitators\n4. Compulsory Environmental Impact Assessment (EIA) before new industries\n5. Reuse and recycling of industrial waste\n6. ISO 14001 — international environmental management standard\n7. Strict enforcement of pollution control laws\n8. Green belts around industrial areas\n9. Renewable energy use in industries"}
      ],
      passage: [
        {q:"'The textile industry is the only industry in India which is self-reliant and complete in the value chain from raw material to the highest value added products. India is second only to China in production of cotton yarn and fabric.'\n\n(a) What makes India's textile industry 'self-reliant'?\n(b) Why did textile mills in Mumbai shift to other cities?\n(c) What are the two main centres of cotton textile industry in India?\n(d) Name any two problems faced by the cotton textile industry.",a:"(a) India's textile industry is self-reliant because it covers the ENTIRE value chain — from growing raw cotton/fibre, through spinning, weaving, processing, dyeing, finishing, to making ready-made garments. India does not need to import raw materials or semi-processed goods at any stage, unlike many other industries.\n\n(b) Mumbai textile mills have been shifting due to:\n• High land costs in Mumbai — factories relocated to cheaper areas\n• Labour problems and high wages\n• Availability of power and cheaper infrastructure elsewhere\n• Mills found it uneconomical to upgrade old machinery\n• Rise of decentralised power loom sector in smaller towns\n\n(c) Two main centres:\n1. Ahmedabad — 'Manchester of India' — in Gujarat near cotton growing areas\n2. Mumbai — historically largest centre; access to port for export\n\n(d) Two problems faced:\n1. COMPETITION: Competition from synthetic fibre industry and cheaper imports (after liberalisation)\n2. TECHNOLOGY: Old machinery in many mills; need for modernisation\n(Other problems: Power shortage, low productivity, competition from powerlooms and handlooms)"}
      ]
    },

    "Life Lines of National Economy": {
      mcq: [
        {q:"Transport, communication and trade are called 'arteries of national economy' because:",opts:["They are only used by government","They link producers to consumers and connect regions","They only carry goods","They are expensive systems"],ans:1},
        {q:"The Indian Railways network is the __ largest in the world:",opts:["Largest","Second","Third","Fourth"],ans:3},
        {q:"The longest road network in India is the:",opts:["National Highways","State Highways","District Roads","Rural Roads"],ans:2},
        {q:"Border roads in India are maintained by:",opts:["State governments","Indian Railways","Border Roads Organisation (BRO)","NHAI"],ans:2},
        {q:"Pipelines are used to transport:",opts:["Only oil","Water, petroleum, natural gas and slurry","Only gas","Only water"],ans:1},
        {q:"India's first radio broadcast was in:",opts:["1920","1923","1927","1930"],ans:1},
        {q:"The International Trade is important because:",opts:["Countries differ in natural endowments and specialise","It creates unemployment","It is always profitable","It reduces technology"],ans:0},
        {q:"India's largest trading partner is:",opts:["USA","China","Japan","Germany"],ans:0},
        {q:"The Golden Quadrilateral Super Highway connects:",opts:["Delhi-Mumbai-Kolkata-Chennai","Delhi-Mumbai only","Mumbai-Chennai only","North-South and East-West corridors"],ans:0},
        {q:"Roadways in India cover a total length of more than __ km:",opts:["1 million","2.3 million","5 million","0.5 million"],ans:1},
        {q:"The National Waterway No. 1 runs along which river?",opts:["Brahmaputra","Ganga (Allahabad to Haldia)","Mahanadi","Godavari"],ans:1},
        {q:"India's MAJOR port is:",opts:["Mumbai only","Chennai only","Mumbai — handling about 20% of total traffic","Visakhapatnam"],ans:2},
        {q:"The satellite communication network in India is operated by:",opts:["Indian Railways","ISRO (INSAT)","Ministry of Defence","Doordarshan"],ans:1},
        {q:"Tourist industry is important because it:",opts:["Only earns foreign exchange","Creates employment, promotes national integration, earns foreign exchange","Only creates jobs","Only promotes culture"],ans:1},
        {q:"'E-commerce' refers to:",opts:["Electronic manufacturing","Buying and selling products and services over internet","Government e-mail","Electronic communication"],ans:1}
      ],
      short: [
        {q:"Explain the importance of transport in national economy.",a:"TRANSPORT — LIFELINE OF NATIONAL ECONOMY:\n\n1. LINKS PRODUCERS TO CONSUMERS: Moves raw materials to factories and finished goods to markets — essential for trade.\n\n2. CONNECTS REGIONS: Enables specialisation — regions can produce what they are best at and exchange with others.\n\n3. AGRICULTURE: Farmers can sell produce to distant markets; fertilisers and seeds reach remote areas.\n\n4. INDUSTRIES: Raw materials reach factories; finished products distributed nationally and internationally.\n\n5. EMERGENCY AND DEFENCE: Essential for moving troops, supplies, and disaster relief.\n\n6. EMPLOYMENT: Railways, roadways, airways employ millions directly and indirectly.\n\n7. NATIONAL INTEGRATION: Transport connects people across the country — promotes unity.\n\n8. TOURISM: Transport makes tourism possible — significant earner of foreign exchange.\n\nMODES: Railways (most important for goods), Roads (most extensive), Airways (fastest), Waterways (cheapest for heavy goods), Pipelines (for liquids and gases)."},
        {q:"Compare the advantages and disadvantages of roadways and railways in India.",a:"ROADWAYS:\nAdvantages:\n• Door-to-door service — no loading/unloading at terminals\n• Flexible routes — can reach any location\n• Faster for short distances\n• Essential where railways don't reach (hills, remote areas)\n• Lower initial construction cost\n\nDisadvantages:\n• Higher cost per unit for long distances\n• Slower than railways for long hauls\n• Weather dependent\n• More accidents — road safety a major issue\n• More fuel consumption and pollution per unit\n\nRAILWAYS:\nAdvantages:\n• Cheapest for bulk goods over long distances\n• Carry thousands of passengers and huge loads\n• Less traffic congestion\n• More fuel-efficient\n• All-weather transport\n\nDisadvantages:\n• Fixed routes — cannot reach all locations\n• High initial infrastructure cost\n• Requires loading/unloading at stations (not door-to-door)\n• Slower than air transport"},
        {q:"What is the importance of international trade? What are India's major exports and imports?",a:"IMPORTANCE OF INTERNATIONAL TRADE:\n1. Countries differ in natural resources and capabilities — trade allows each to specialise\n2. Earns foreign exchange for imports\n3. Promotes economic growth\n4. Provides access to goods not produced domestically\n5. Technology transfer through trade\n\nINDIA'S MAJOR EXPORTS:\n• Petroleum products (refined)\n• Gems and jewellery\n• Engineering goods (machinery)\n• Software and IT services\n• Textiles and garments\n• Chemicals and pharmaceuticals\n• Agricultural products (rice, spices, tea)\n\nINDIA'S MAJOR IMPORTS:\n• Crude petroleum and petroleum products (biggest import)\n• Electronic goods\n• Gold and silver\n• Machinery\n• Fertilisers\n• Chemicals\n\nMAJOR TRADING PARTNERS: USA (largest), UAE, China, UK, Germany, Japan"}
      ],
      long: [
        {q:"Describe the Indian Railways system. Why is it important for the national economy?",a:"INDIAN RAILWAYS — KEY FACTS:\n• Route length: Over 67,000 km — 4th largest network in world\n• Employees: Over 1.3 million — one of world's largest employers\n• Passengers: Carries about 23 million passengers daily\n• Freight: Largest transporter of bulk goods in India\n\nORGANISATION: Divided into 16 zones\n\nTYPES OF LINES:\n• Broad gauge (1.676 m) — most of network\n• Metre gauge (1 m)\n• Narrow gauge (0.762 m)\n\nIMPORTANCE FOR NATIONAL ECONOMY:\n1. TRADE INTEGRATION: Connects all parts of India — allows goods to flow from production centres to consumption markets\n2. RAW MATERIAL SUPPLY: Moves coal to power plants, iron ore to steel plants, food grains to deficit areas\n3. PASSENGER MOVEMENT: Enables people to travel for work, education, pilgrimage, tourism\n4. EMPLOYMENT: Over 1.3 million direct employees; millions more indirectly\n5. STRATEGIC IMPORTANCE: Essential for defence — moves troops and supplies\n6. SOCIAL INTEGRATION: Connects diverse regions and communities\n7. TOURISM: Makes pilgrimage centres, hill stations, national parks accessible\n8. REDUCES ROAD CONGESTION: Each passenger train takes hundreds of vehicles off roads\n\nCHALLENGES:\n• Old infrastructure needs modernisation\n• Safety issues (accidents)\n• Financial sustainability\n• Speed — needs high-speed rail corridors"}
      ],
      passage: [
        {q:"'Trade is the backbone of a country's economy. International trade enables countries to sell what they produce in excess and buy what they need. The trade balance of a country shows the difference between its exports and imports. India mainly exports petroleum products, gems and jewellery, engineering goods, software services and textiles.'\n\n(a) What is meant by 'trade balance'?\n(b) What is 'favourable trade balance'?\n(c) Why does India import so much petroleum?\n(d) How has India's trade pattern changed after liberalisation?",a:"(a) Trade balance is the difference between the value of a country's exports and imports. It shows whether a country is selling more (exporting) or buying more (importing) from other countries.\n\n(b) Favourable trade balance (trade surplus): When a country's exports are greater than its imports — it earns more foreign exchange than it spends. India mostly has an unfavourable trade balance (trade deficit) because its imports (especially crude oil) exceed exports.\n\n(c) India imports so much petroleum because:\n• India has limited domestic oil reserves\n• India imports 80%+ of its petroleum requirement\n• Rapid economic growth and rising car ownership have massively increased demand\n• Petroleum is used for transport, industry, electricity generation\n• India's own fields (Mumbai High, Assam, Rajasthan) cannot meet domestic demand\n\n(d) India's trade pattern changed after liberalisation (1991) by:\n• Increase in exports — software, engineering goods, pharmaceuticals expanded\n• Increase in imports — capital goods, electronic goods, gold\n• Greater diversification of trading partners\n• Service exports (IT, tourism) became very important\n• Opening of Indian markets to foreign competition"}
      ]
    }
  }
};
