const SOCIAL_ECO_QUESTIONS_DB = {
  "social_eco": {

    "Development": {
      mcq: [
        {q:"Different people have different notions of development because:",opts:["They speak different languages","They have different life situations and goals","They live in different countries","They have different ages"],ans:1},
        {q:"What is 'per capita income'?",opts:["Total income of the country","Average income per person","Income of the richest person","Income of the poorest person"],ans:1},
        {q:"Which country has the highest per capita income?",opts:["India","China","USA (among the highest in world)","Russia"],ans:2},
        {q:"The Human Development Index (HDI) was developed by:",opts:["World Bank","IMF","UNDP (United Nations Development Programme)","WHO"],ans:2},
        {q:"HDI considers which THREE main indicators?",opts:["Income, population, area","Per capita income, education, health/life expectancy","GDP, trade, military","Literacy, agriculture, industry"],ans:1},
        {q:"Infant Mortality Rate measures:",opts:["Deaths of all infants","Number of children who die before age 1 per 1000 live births","Deaths of infants above 5 years","Child population"],ans:1},
        {q:"Life expectancy means:",opts:["The maximum age anyone can live","The average number of years a person is expected to live","The age of the oldest person","The minimum age of survival"],ans:1},
        {q:"Net Attendance Ratio measures:",opts:["Factory attendance","Children attending school as proportion of total children in that age group","Teacher attendance","Voter turnout"],ans:1},
        {q:"Sustainable development means:",opts:["Development that uses all resources now","Development that meets present needs without compromising future generations","Only industrial development","Only agricultural development"],ans:1},
        {q:"Which Indian state has the highest literacy rate?",opts:["Punjab","Tamil Nadu","Kerala","Haryana"],ans:2},
        {q:"Literacy rate measures:",opts:["People with university degrees","Proportion of literate population above 7 years","Children in school","Graduation rate"],ans:1},
        {q:"Bihar has a very low per capita income. This means:",opts:["All people in Bihar are poor","The average income of people in Bihar is low","Bihar has no rich people","Bihar has more poor than rich states"],ans:1},
        {q:"Why is per capita income not a perfect indicator of development?",opts:["It is difficult to calculate","It does not reflect distribution of income or quality of life","It changes every year","It is measured in foreign currency"],ans:1},
        {q:"Which factor does the HDI include that per capita income does NOT?",opts:["Military strength","Trade balance","Education and health","Agricultural production"],ans:2},
        {q:"India's HDI rank compared to its per capita income rank is:",opts:["Higher than per capita income rank","Lower than per capita income rank","Exactly the same","Not comparable"],ans:0}
      ],
      short: [
        {q:"Why do different people have different development goals? Give examples.",a:"DIFFERENT DEVELOPMENT GOALS arise because people have different life situations, needs and aspirations.\n\nEXAMPLES:\n• A LANDLESS LABOURER wants more days of work, higher wages and a house. For them, development means better employment and income security.\n• A RICH FARMER wants higher prices for crops and modern irrigation. Their development goals are about improving agricultural productivity.\n• A GIRL from an educated family may want to study further and have a career — she values education and gender equality.\n• A BUSINESSMAN wants stable government, good infrastructure and easy credit.\n• An ENVIRONMENTALIST wants clean air, forests protected and sustainable use of resources.\n• A TRIBAL PERSON may want their traditional land rights protected.\n\nKEY INSIGHT: What is 'development' for one person may not be for another, or may even HARM others. (e.g. a dam provides water for some but displaces others)\n\nTHEREFORE: We need to look at both INDIVIDUAL goals AND NATIONAL development goals, balancing them."},
        {q:"What is the Human Development Index? How is it different from per capita income?",a:"HUMAN DEVELOPMENT INDEX (HDI):\nDeveloped by UNDP, it measures human development on THREE dimensions:\n1. LONG AND HEALTHY LIFE: Measured by life expectancy at birth\n2. KNOWLEDGE/EDUCATION: Measured by mean years of schooling and expected years of schooling\n3. DECENT STANDARD OF LIVING: Measured by Gross National Income per capita\n\nHDI gives equal weight to all three — a composite index from 0 to 1.\n\nDIFFERENCES FROM PER CAPITA INCOME:\n• Per capita income measures only MONEY; HDI measures money + health + education\n• A country can have high per capita income but poor health/education (Saudi Arabia historically)\n• A country can have good HDI with lower income if it invests in health and education (Kerala, Sri Lanka, Cuba)\n• HDI gives a more complete picture of people's actual well-being\n• Distribution matters in HDI (through health and education outcomes) while per capita income ignores inequality\n\nEXAMPLE: Kerala has lower per capita income than Punjab but higher HDI because of better literacy and life expectancy."},
        {q:"What is sustainable development? Why is it important?",a:"SUSTAINABLE DEVELOPMENT: Development that meets the needs of the present generation without compromising the ability of future generations to meet their own needs.\n\nKEY PRINCIPLES:\n• Use renewable resources at or below their regeneration rate\n• Non-renewable resources should be used sparingly\n• Pollution should not exceed absorptive capacity of environment\n• Diversity (biological and cultural) should be preserved\n\nWHY IMPORTANT:\n1. RESOURCE DEPLETION: Many natural resources (coal, oil, groundwater) are being used faster than they form\n2. ENVIRONMENTAL DAMAGE: Development activities cause pollution, deforestation, climate change\n3. FUTURE GENERATIONS: Today's overuse leaves less for future generations\n4. EQUITY: Poor countries and peoples bear more of the costs of environmental damage\n5. SURVIVAL: Climate change threatens the survival of many species and communities\n\nEXAMPLE: Groundwater extraction in India exceeds natural recharge rate → falling water tables → threatens agriculture and drinking water for future generations."}
      ],
      long: [
        {q:"'Per capita income is an important indicator of development but has several limitations.' Explain. What are better indicators of development?",a:"PER CAPITA INCOME AS INDICATOR:\n• Measures total national income divided by population\n• Countries classified as Low Income (under $1085), Middle Income ($1086-$13205), High Income (above $13205) by World Bank\n• India is in lower-middle income group; USA is high income\n• Useful for basic comparisons across countries\n\nLIMITATIONS OF PER CAPITA INCOME:\n1. IGNORES DISTRIBUTION: High average income can coexist with extreme inequality. Top 1% can inflate average while most people are poor.\n2. IGNORES QUALITY OF LIFE: Money doesn't capture health, education, freedom, security\n3. IGNORES NON-MONETARY ASPECTS: Clean environment, safe roads, good governance not captured\n4. MEASUREMENT PROBLEMS: Informal economy, unpaid household work not counted\n5. DOESN'T REFLECT SUSTAINABILITY: Income from depleting resources not sustainable\n\nBETTER INDICATORS:\n1. HDI: Combines income, health and education\n2. INFANT MORTALITY RATE: How many children survive — reflects health services\n3. LITERACY RATE: Education access and quality\n4. LIFE EXPECTANCY: Reflects overall health and well-being\n5. NET ATTENDANCE RATIO: Children in school\n6. GINI COEFFICIENT: Measures inequality\n7. MATERNAL MORTALITY RATE: Women's health\n\nEXAMPLE: Kerala vs Haryana:\n• Haryana has higher per capita income\n• Kerala has BETTER health and education indicators\n• Kerala shows that investment in health and education gives better human development even with lower income"}
      ],
      passage: [
        {q:"Study the following data:\n\nCountry A: Per capita income $2000, Life expectancy 75 years, Literacy rate 90%\nCountry B: Per capita income $8000, Life expectancy 55 years, Literacy rate 50%\n\n(a) Which country has better HDI? Why?\n(b) What does this tell us about the relationship between income and development?\n(c) How can Country B improve its development?\n(d) What is meant by 'public facilities'? Give two examples.",a:"(a) Country A has BETTER HDI despite lower per capita income because:\n• HDI measures three dimensions: income + health + education\n• Country A has much higher life expectancy (75 vs 55 years)\n• Country A has much higher literacy rate (90% vs 50%)\n• In HDI terms, Country A's people live longer and are better educated — higher human development\n\n(b) This tells us that INCOME ALONE does not determine development:\n• High income can coexist with poor health and education (Country B)\n• Even with moderate income, countries can achieve high human development if they invest wisely in health and education (Country A)\n• Sri Lanka and Kerala are real examples — high human development with relatively lower income\n• Public investment in health and education is more important than raw income levels\n\n(c) Country B can improve development by:\n• Investing more government spending in public health (hospitals, healthcare access)\n• Expanding public education system — building schools, training teachers\n• Reducing inequality so that high income reaches more people\n• Creating public facilities like clean water, sanitation\n• Social programmes targeting literacy among women and marginalised groups\n\n(d) Public facilities are services provided by the government for all citizens, not for profit:\n• Examples: Public schools, public hospitals, public transport, clean water supply, electricity, roads\n• These cannot be provided adequately by private markets alone because poor people cannot afford them\n• They are essential for human development"}
      ]
    },

    "Sectors of the Indian Economy": {
      mcq: [
        {q:"The primary sector includes:",opts:["Manufacturing","Natural activities like agriculture, mining, fishing","Banking and IT","Trade and commerce"],ans:1},
        {q:"The secondary sector includes:",opts:["Agriculture and mining","Manufacturing and processing industries","Services like banking","Trade"],ans:1},
        {q:"The tertiary sector is also called the:",opts:["Primary sector","Secondary sector","Service sector","Agricultural sector"],ans:2},
        {q:"GDP (Gross Domestic Product) is the value of:",opts:["Only exports","All goods and services produced within a country in a year","Only manufactured goods","Only agricultural output"],ans:1},
        {q:"In India, which sector employs the MOST people?",opts:["Secondary","Tertiary","Primary (agriculture)","All sectors equally"],ans:2},
        {q:"Which sector contributes MOST to India's GDP currently?",opts:["Primary","Secondary","Tertiary (services)","All equally"],ans:2},
        {q:"Disguised unemployment occurs when:",opts:["People are openly unemployed","More people work on a task than actually needed — removing some would not reduce output","Unemployment is seasonal","People are underemployed"],ans:1},
        {q:"Seasonal unemployment occurs mainly in:",opts:["Industry","Agriculture — idle in non-growing seasons","Services","Banking"],ans:1},
        {q:"Which is an example of the unorganised sector?",opts:["Government employees","Bank employees","Street vendor, domestic worker, agricultural labourer","Factory worker with regular salary"],ans:2},
        {q:"NREGA (National Rural Employment Guarantee Act) guarantees how many days of work?",opts:["100 days per household per year","200 days","50 days","365 days"],ans:0},
        {q:"The organised sector provides workers:",opts:["No security","Job security, provident fund, paid leave, health benefits","Only wages","Seasonal work"],ans:1},
        {q:"Which is NOT a characteristic of the unorganised sector?",opts:["Low wages","Job insecurity","Formal employment contracts","Small-scale operations"],ans:2},
        {q:"Historical shift in economic development: As economies develop, which sector grows in importance?",opts:["Primary","Secondary (first), then Tertiary","Only primary","They stay equal"],ans:1},
        {q:"Banking, insurance and trade fall under the __ sector:",opts:["Primary","Secondary","Tertiary","Quaternary"],ans:2},
        {q:"A teacher employed in a private school is in the __ sector:",opts:["Primary","Secondary","Tertiary","Unorganised"],ans:2}
      ],
      short: [
        {q:"Distinguish between the primary, secondary and tertiary sectors with examples.",a:"PRIMARY SECTOR:\n• Activities that involve direct use of natural resources\n• 'Primary' because it forms the base of all production\n• Examples: Agriculture, fishing, mining, forestry, animal husbandry\n• Produces raw materials for other sectors\n• In India: Employs most workers but contributes less to GDP now\n\nSECONDARY SECTOR:\n• Transforms raw materials (from primary sector) into finished goods\n• Also called industrial sector or manufacturing sector\n• Examples: Steel making, textile industry, car manufacturing, construction, mining processing\n• Adds value to primary goods\n\nTERTIARY SECTOR:\n• Provides services that help primary and secondary sectors\n• Also called 'service sector'\n• Examples: Banking, insurance, transport, IT, healthcare, education, trade, tourism, government services\n• Does NOT produce goods — provides services\n• Now largest sector in India by GDP contribution\n\nINTERDEPENCY: All three are interconnected — agriculture (primary) needs inputs from industry (secondary) and is transported by transport (tertiary)."},
        {q:"What is disguised unemployment? How is it different from open unemployment?",a:"DISGUISED UNEMPLOYMENT:\n• A situation where MORE workers are engaged in an activity than actually needed\n• Removing some workers would NOT reduce the total output\n• The 'extra' workers appear to be employed but their marginal productivity is zero\n• Common in AGRICULTURE in India — family farms often have more family members working than necessary\n\nOPEN UNEMPLOYMENT:\n• People who are willing and able to work but CANNOT find work\n• Openly jobless — clearly visible\n• Common in urban areas\n\nSEASONAL UNEMPLOYMENT:\n• Work available only during certain seasons\n• Agricultural workers have no work in off-season\n• Construction workers may have seasonal demand\n\nEXAMPLE OF DISGUISED UNEMPLOYMENT:\nA farm needs 3 workers. A family of 5 all work on it. Output = same with 3 or 5 workers. The extra 2 are disguised unemployed.\n\nIMPORTANCE: India has enormous disguised unemployment in agriculture. If these workers could be absorbed in other sectors (manufacturing, services), agricultural productivity would not fall and overall production would rise."},
        {q:"What are the differences between organised and unorganised sectors? Who are unorganised sector workers?",a:"ORGANISED SECTOR:\n• Registered with government, follows official rules and regulations\n• Workers have formal employment contracts\n• Provides job security — cannot be dismissed without reason\n• Benefits: Provident fund, paid leave, health benefits, pension, gratuity\n• Fixed working hours\n• Higher wages\n• Examples: Government employees, bank staff, factory workers with contracts\n\nUNORGANISED SECTOR:\n• Small-scale, not registered or regulated by government\n• No formal employment contracts\n• No job security — can be dismissed any time\n• No benefits — no PF, no paid leave, no insurance\n• Lower wages, irregular income\n• Long or irregular working hours\n• Examples: Street vendors, domestic workers, agricultural labourers, construction workers, small shopkeepers, home-based workers\n\nSCALE OF UNORGANISED SECTOR IN INDIA:\n• About 90% of workers are in unorganised sector\n• They need protection — minimum wage laws, labour rights, social security\n• MGNREGA provides 100 days guaranteed employment in rural areas\n• Social security schemes like ESIC, EPF should be extended to unorganised workers"}
      ],
      long: [
        {q:"Explain how employment and output have changed across the three sectors in India. Why is the service sector growing so fast?",a:"HISTORICAL CHANGES IN SECTORS:\n\n1850s-1950s: PRIMARY SECTOR DOMINATED\n• Most people in agriculture\n• Both employment and GDP mostly from agriculture\n\nPOST-INDEPENDENCE: SECONDARY SECTOR GREW\n• Government investment in industries — Steel, heavy machinery, chemicals\n• Manufacturing employment increased\n• But agriculture still employed most workers\n\nSINGLE 1991-PRESENT: TERTIARY SECTOR DOMINATES GDP\n• Services sector now contributes 55%+ of GDP\n• Manufacturing is second, agriculture third in GDP\n• But agriculture STILL employs majority of workers (about 44%)\n\nTHIS CREATES A MISMATCH:\n• Agriculture: 44% workers but only ~17% of GDP → low productivity, low incomes\n• Services: ~27% workers but ~55% GDP → high productivity, high incomes\n• Manufacturing: ~25% workers, ~28% GDP\n\nWHY SERVICES GREW SO FAST:\n1. IT REVOLUTION: India became major global software/IT hub (Bengaluru, Hyderabad, Pune)\n2. GLOBALISATION: Demand for Indian IT, BPO, financial services from rich countries\n3. EDUCATED WORKERS: English-speaking engineering graduates available at lower cost\n4. LIBERALISATION: 1991 reforms opened India to global services trade\n5. INFRASTRUCTURE: Telecommunications revolution enabled remote services\n6. DOMESTIC DEMAND: Rising middle class demands more services (restaurants, healthcare, education, entertainment)\n\nCHALLENGE: Most people still in low-productivity agriculture. Need to move them to manufacturing (like China did) and services."}
      ],
      passage: [
        {q:"'A large number of people in India are working in the unorganised sector. They are not able to bargain with the employers because in the unorganised sector there is heavy competition for work. NREGA, 2005 guarantees 100 days of wage employment per year to every rural household.'\n\n(a) Who are the unorganised sector workers?\n(b) Why can they not bargain with employers?\n(c) What is the significance of NREGA?\n(d) What else can be done to protect unorganised sector workers?",a:"(a) Unorganised sector workers include:\n• Agricultural labourers (work on others' farms for daily wages)\n• Construction workers and masons\n• Street vendors and hawkers\n• Domestic workers (maids, cooks, security guards)\n• Home-based piece-rate workers\n• Small shop assistants\n• Rickshaw pullers, auto drivers\n• Workers in small workshops and factories not registered with government\nAbout 90% of India's workforce is in the unorganised sector.\n\n(b) They cannot bargain because:\n• There is heavy competition for work — many unemployed or underemployed people ready to take any work\n• They are individually weak and not unionised\n• They have no fallback — cannot afford to be unemployed\n• Employers know workers are desperate and will accept any conditions\n• No legal protection (or enforcement is weak) for minimum wages\n\n(c) Significance of NREGA (National Rural Employment Guarantee Act, 2005):\n• Legally GUARANTEES 100 days of employment per household — first law to guarantee employment\n• Provides income security in lean agricultural seasons\n• Creates productive assets (roads, ponds, afforestation)\n• Sets minimum wage for rural workers\n• Reduces distress migration to cities\n• Empowers rural poor — legal right, not charity\n• Particularly benefits women and SC/ST communities\n\n(d) Other measures to protect unorganised workers:\n• Strict enforcement of minimum wage laws\n• Extension of provident fund, health insurance to all workers\n• Recognition of unions for unorganised workers\n• Skill development programmes\n• Easy access to credit through self-help groups and microfinance"}
      ]
    },

    "Money and Credit": {
      mcq: [
        {q:"Money as a medium of exchange eliminates:",opts:["Trade","Barter system's need for 'double coincidence of wants'","All economic problems","Saving"],ans:1},
        {q:"Currency notes issued in India are authorised by:",opts:["Commercial banks","State governments","Reserve Bank of India (RBI)","Government of India directly"],ans:2},
        {q:"Demand deposits are:",opts:["Fixed deposits that cannot be withdrawn","Deposits in bank accounts that can be withdrawn on demand","Only savings accounts","Only current accounts"],ans:1},
        {q:"A cheque is:",opts:["Currency note","Paper order directing bank to pay a specific amount from the account","A promissory note","Bank guarantee"],ans:1},
        {q:"Credit refers to:",opts:["Money kept in banks","An agreement where lender supplies money/goods to borrower against future payment","Currency circulation","Government bonds"],ans:1},
        {q:"Collateral is:",opts:["Interest rate","An asset the borrower uses as guarantee to the lender","Type of loan","Bank account"],ans:1},
        {q:"Which of the following is NOT a formal source of credit?",opts:["Banks","Cooperative societies","Moneylenders","Post office savings"],ans:2},
        {q:"Moneylenders charge __ compared to banks:",opts:["Lower interest","Same interest","Much higher interest","No interest"],ans:2},
        {q:"Self-Help Groups (SHGs) are important because:",opts:["They replace banks","They provide credit to poor (especially rural women) who cannot access banks","They only save money","They are government organisations"],ans:1},
        {q:"A 'debt trap' occurs when:",opts:["Banks give too many loans","Borrower cannot repay and borrows more — spiralling into more debt","Interest rates fall","Government gives loans"],ans:1},
        {q:"The Reserve Bank of India monitors and regulates:",opts:["Only central government banks","All banking activities, ensures banks maintain proper reserves, fair interest rates","Only private banks","Only cooperative banks"],ans:1},
        {q:"Why is formal credit preferred over informal credit?",opts:["Formal credit has no paperwork","Formal credit is cheaper (lower interest) and regulated","Informal credit is not available","Banks are everywhere"],ans:1},
        {q:"Which of the following activities can credit HELP with?",opts:["Only buying consumer goods","Starting a business, agricultural investment, meeting emergencies","Paying fines","None of these"],ans:1},
        {q:"Modern currency is accepted because:",opts:["It is made of gold","The government authorises it and people trust the banking system","It is rare","It is physically attractive"],ans:1},
        {q:"Grameen Bank of Bangladesh is famous for providing:",opts:["Large industrial loans","Microfinance/small loans to poor rural women","Only agricultural loans","Government contracts"],ans:1}
      ],
      short: [
        {q:"What is money? Why does modern economy need money?",a:"MONEY: Any medium that is generally accepted in exchange for goods and services and for settling debts.\n\nWHY MONEY IS NEEDED:\nIn a barter system (direct exchange), you need 'double coincidence of wants' — both parties must want what the other has. This is very difficult to achieve.\n\nEXAMPLE PROBLEM: A shoemaker wants wheat. He must find a wheat farmer who wants shoes — at the same time, in the right quantities. Very difficult!\n\nMONEY SOLVES THIS:\n• Shoemaker sells shoes for money\n• Then buys wheat with money from any wheat farmer\n• Separates selling and buying — no need for simultaneous double coincidence\n\nMONEY AS MEDIUM OF EXCHANGE:\n• Everyone accepts money → eliminates double coincidence problem\n• Enables specialisation — people can specialise and exchange efficiently\n• Stores value — save now, spend later\n• Standard of value — prices expressed in money for easy comparison\n\nMODERN FORMS OF MONEY:\n• Currency (coins and notes) — authorised by RBI in India\n• Demand deposits in banks — transferred via cheques\n• Digital payments — UPI, credit/debit cards"},
        {q:"What are formal and informal sources of credit in India? Why is it important to expand formal credit?",a:"FORMAL SOURCES:\n• Banks (commercial, cooperative, regional rural banks)\n• Cooperative credit societies\n• Post office savings schemes\n• Microfinance institutions regulated by RBI\n\nFeatures: Lower interest rates, regulated by government, collateral required\n\nINFORMAL SOURCES:\n• Moneylenders\n• Traders and merchants (advance against crops)\n• Employers\n• Relatives and friends\n• Local financiers\n\nFeatures: Higher interest rates, no government regulation, no fixed terms\n\nPROBLEMS WITH INFORMAL CREDIT:\n• Moneylenders charge 36-60% or more interest (banks charge 12-15%)\n• Harsh loan conditions — can lead to debt traps\n• No regulation — borrowers have no legal protection\n• Can seize assets, use coercion for repayment\n\nIMPORTANCE OF EXPANDING FORMAL CREDIT:\n1. CHEAPER: Lower interest rates → less burden on borrowers\n2. REGULATED: Government protects borrowers' rights\n3. INVESTMENT: Enables productive investment for growth\n4. ESCAPE POVERTY: Access to credit helps poor start businesses\n5. REDUCE EXPLOITATION: Less dependence on exploitative moneylenders"},
        {q:"What are Self-Help Groups (SHGs)? How do they help rural women?",a:"SELF-HELP GROUPS (SHGs):\n• Small groups (typically 15-20 members, mostly women)\n• Members regularly save small amounts\n• Group pools savings and members can borrow from the pool at reasonable interest\n• If the group's track record is good, banks give loans to the group\n\nHOW SHGS HELP RURAL WOMEN:\n1. CREDIT ACCESS: Women who have no collateral and cannot access banks individually can borrow through SHG\n2. AFFORDABLE INTEREST: SHG loans at much lower rates than moneylenders\n3. EMPOWERMENT: Women control their own finances, gain confidence\n4. DECISION-MAKING: Women make collective decisions about savings and loans\n5. SOCIAL ISSUES: SHGs also discuss health, nutrition, education, domestic violence\n6. ESCAPE DEBT TRAP: Formal credit at reasonable rates prevents exploitation by moneylenders\n7. SOLIDARITY: Mutual support network\n8. INCOME: Members use loans to start small businesses — earn income\n\nGRAMEEN BANK MODEL: Bangladesh's Grameen Bank pioneered microfinance for poor rural women — now copied worldwide."}
      ],
      long: [
        {q:"Credit can be both helpful and harmful. Explain with examples. What conditions determine whether credit is helpful?",a:"CREDIT CAN BE HELPFUL:\n\n1. AGRICULTURAL INVESTMENT:\nSalim, a small farmer, borrows for seeds, fertilisers, irrigation. After harvest he repays and has surplus income.\nCredit → Investment → Higher output → Repayment + profit ✓\n\n2. BUSINESS STARTUP:\nShyam borrows to buy a sewing machine, starts tailoring business, earns regular income, repays loan.\nCredit → Capital → Business → Income ✓\n\n3. EMERGENCY:\nFamily borrows for medical treatment → member recovers → earns back and repays ✓\n\nCREDIT CAN BE HARMFUL:\n\n1. CROP FAILURE + HIGH INTEREST:\nRamkali borrows from moneylender at 36% for farming. Crop fails. Cannot repay. Borrows more to repay, going deeper into debt.\nCredit → Investment → Failure → Debt trap → Poverty ✗\n\n2. INFORMAL CREDIT WITH HARSH TERMS:\nBorrow against land as collateral. Cannot repay → loses land → becomes landless labourer.\n\nCONDITIONS FOR CREDIT TO BE HELPFUL:\n1. REASONABLE INTEREST RATE: Must not be so high that repayment becomes impossible\n2. PRODUCTIVE USE: Credit for investment (not just consumption) can generate income to repay\n3. ACCESSIBLE FORMAL SOURCES: Banks rather than moneylenders\n4. REPAYMENT FLEXIBILITY: Some flexibility in case of emergencies\n5. NO HARSH COLLATERAL: Loss of land/home due to loan failure can push families into permanent poverty\n\nCONCLUSION: Expanding access to cheap formal credit (through banks, SHGs, microfinance) is essential for development, while protecting people from predatory informal lending."}
      ],
      passage: [
        {q:"'Swapna, a small farmer, took a loan from a moneylender at 36% per annum to purchase seeds and fertilisers. The harvest was poor and she could not repay. Next year she again borrowed more. Over time her debt grew. Eventually she lost her land which was given as collateral.'\n\n(a) What is a debt trap? How did Swapna fall into it?\n(b) What is collateral? Why is it problematic for small farmers?\n(c) What could have prevented Swapna's situation?\n(d) What are Self-Help Groups and how could they have helped Swapna?",a:"(a) A debt trap is a situation where a borrower cannot repay a loan and borrows more to repay the existing debt, leading to an ever-growing cycle of debt that is impossible to escape.\n\nSwapna fell into it because:\n• Borrowed at very high interest (36%) from moneylender\n• Crop failure meant she had no income to repay\n• Had to borrow more — accumulating more debt\n• High interest compounded the problem each year\n• Eventually lost her land — which was her only asset\n\n(b) Collateral is an asset that the borrower provides to the lender as a guarantee. If the borrower cannot repay, the lender can sell the collateral to recover money.\n\nProblematic for small farmers because:\n• Their land is their only asset and main source of livelihood\n• If they lose the collateral (land), they become landless and even more vulnerable\n• Fear of losing land may prevent farmers from taking necessary loans\n• Banks require collateral — those without assets cannot access bank loans\n\n(c) Prevention methods:\n• Access to bank credit or cooperative credit at lower interest (8-12% vs 36%)\n• Crop insurance to protect against harvest failure\n• Government support during crop failure (Kisan Credit Card, relief funds)\n• SHG membership providing access to affordable group credit\n\n(d) Self-Help Groups (SHGs):\n• 15-20 women pool small savings regularly\n• Members borrow from the pool at reasonable interest\n• Banks give group loans once SHG has good track record\n\nHow SHG could have helped Swapna:\n• Access to credit at much lower interest rate (18-20% vs 36% moneylender)\n• Group support and collective decision-making\n• Would not have required individual land as collateral (group guarantee)\n• Would not have fallen into as deep a debt trap"}
      ]
    },

    "Globalisation and the Indian Economy": {
      mcq: [
        {q:"Globalisation refers to:",opts:["Industrialisation of the globe","Integration of economies through trade, foreign investment and technology","Spread of one culture globally","Only trade between countries"],ans:1},
        {q:"Multinational corporations (MNCs) are companies that:",opts:["Operate only in one country","Own or control production in more than one country","Are owned by multiple governments","Only export goods"],ans:1},
        {q:"MNCs set up production in other countries mainly because:",opts:["Other countries have better weather","They want to save costs by using cheaper labour, land and resources","They want to spread culture","They have no choice"],ans:1},
        {q:"Liberalisation means:",opts:["Freeing of business from government controls and excessive regulation","More government control","Only financial liberalisation","Opening borders to culture"],ans:0},
        {q:"Privatisation means:",opts:["Government taking over private companies","Transfer of ownership from government to private sector","Making all companies public","Nationalisation"],ans:1},
        {q:"WTO (World Trade Organisation) aims to:",opts:["Promote wars","Establish rules for international trade and promote free trade","Only help developing countries","Restrict trade"],ans:1},
        {q:"Rapid improvement in __ has been a major factor enabling globalisation:",opts:["Military technology","Transportation and communication technology","Agricultural technology","Medical technology"],ans:1},
        {q:"'Fair globalisation' would mean:",opts:["Free trade for all","Creating opportunities for all and ensuring fair distribution of benefits","MNCs dominating","Rich countries benefiting most"],ans:1},
        {q:"Which of the following is a positive effect of globalisation for India?",opts:["Job losses in manufacturing","New jobs in IT, BPO; lower prices for consumers; better quality goods","Only cultural impact","Only negative effects"],ans:1},
        {q:"Small producers in India are threatened by globalisation because:",opts:["They don't want to work","They cannot compete with cheaper imported goods or MNCs","They have too much money","Government helped them too much"],ans:1},
        {q:"Foreign trade creates __ for domestic producers:",opts:["Less competition only","More competition and also new markets abroad","Only problems","Only opportunities"],ans:1},
        {q:"The process of removing trade barriers is called:",opts:["Protection","Liberalisation of trade","Tariff","Quota"],ans:1},
        {q:"Which industry in India BENEFITED most from globalisation?",opts:["Small-scale industries","IT and software services industry","Handloom industry","Farming"],ans:1},
        {q:"'Race to the bottom' refers to:",opts:["Countries competing for lowest corruption","Countries competing to attract MNCs by lowering labour and environmental standards","Stock market falling","Economic recession"],ans:1},
        {q:"India's economic liberalisation began in:",opts:["1947","1971","1991","2001"],ans:2}
      ],
      short: [
        {q:"What is globalisation? What factors have enabled it?",a:"GLOBALISATION: The process of rapid integration of countries through greater foreign trade and foreign investments by multinational corporations. It connects production and markets across borders.\n\nFACTORS ENABLING GLOBALISATION:\n\n1. TECHNOLOGY:\n• Rapid improvement in transport — cheaper and faster shipping (container revolution)\n• Internet and telecommunications — instant global communication\n• Digital technology — software, data can be transferred instantly globally\n• Allows coordination of production across countries\n\n2. LIBERALISATION OF TRADE:\n• Countries removed barriers to trade (tariffs, quotas)\n• WTO agreements pushed member countries to reduce trade restrictions\n• More goods and services cross borders freely\n\n3. LIBERALISATION OF INVESTMENT:\n• Countries allow foreign companies to invest (Foreign Direct Investment)\n• Less restrictions on capital movement\n\n4. MNCs:\n• Companies spread production globally to reduce costs\n• Connect global markets with global production\n\nRESULT: Today, the world is more interconnected than ever. A phone made in India has parts from China, Korea, USA, Japan — assembled with Indian labour for global markets."},
        {q:"How has globalisation affected Indian workers? Compare the impact on different groups.",a:"IMPACT ON INDIAN WORKERS — MIXED:\n\nWORKERS WHO BENEFITED:\n1. IT/BPO WORKERS: High-paying jobs in software, call centres, data processing for global companies\n2. SKILLED PROFESSIONALS: Engineers, managers in MNCs get higher salaries, international exposure\n3. CONSUMERS: Lower prices, greater variety of goods\n4. EXPORT-ORIENTED SECTORS: Workers in gems/jewellery, textiles get more employment\n\nWORKERS WHO WERE HARMED:\n1. SMALL MANUFACTURERS: Cannot compete with cheaper imports — many small industries closed (toys, plastics, electronics)\n2. AGRICULTURAL WORKERS: Cheap subsidised imports from rich countries compete with Indian farmers\n3. UNORGANISED WORKERS: MNCs often hire through contractors — no job security, no benefits\n4. CASUALISATION OF WORK: Companies prefer short-term contracts instead of permanent employment\n5. LABOUR STANDARD THREATS: To attract FDI, governments may allow lower labour protections\n\nCONCLUSION: Globalisation has created UNEQUAL benefits. Those with education and skills in growing sectors benefited; those in traditional industries and agriculture were often harmed. Need policies to ensure fair distribution."},
        {q:"Why do some people argue against globalisation? What is 'fair globalisation'?",a:"ARGUMENTS AGAINST GLOBALISATION:\n\n1. UNEQUAL BENEFITS: Rich countries and MNCs gain most; poor countries and workers benefit less\n2. JOB LOSSES: Import competition destroys domestic industries and jobs\n3. CULTURAL HOMOGENISATION: Local cultures replaced by global (mainly Western) consumer culture\n4. ENVIRONMENTAL DAMAGE: MNCs move polluting industries to countries with lax regulations\n5. RACE TO THE BOTTOM: Countries compete for investment by lowering wages and labour standards\n6. POWER IMBALANCE: WTO rules often favour rich countries\n7. FARMERS: Cheap subsidised agricultural imports from US/EU destroy farming in developing countries\n\nFAIR GLOBALISATION:\n• Benefits should reach ALL people, not just wealthy in rich countries\n• Rules of WTO should be fair to developing countries\n• MNCs should follow same labour and environmental standards globally\n• Governments of poor countries should have flexibility to protect infant industries\n• Workers everywhere should get fair wages and safe conditions\n• Technology transfer should help developing countries grow\n• India's government, trade unions and many others have argued for fair globalisation"}
      ],
      long: [
        {q:"Describe the role of Multinational Corporations in the globalisation process. How do they integrate production across countries?",a:"MNCs IN GLOBALISATION:\n\nWHAT MNCs DO:\nMNCs own or control production in more than one country. They spread activities across the world to maximise profit by using:\n• Cheap labour in developing countries\n• Near natural resources\n• Close to major markets\n\nHOW THEY INTEGRATE PRODUCTION:\n\nEXAMPLE — A GARMENT MNC:\n• Design: Headquarters in USA/Europe\n• Fabric: From China or India\n• Cutting and stitching: Bangladesh or Vietnam (cheapest labour)\n• Quality check: Regional hub in Singapore\n• Marketing and retail: Globally in developed countries\n\nEXAMPLE — FORD CARS:\n• Engine from Germany\n• Electronics from Japan/Korea\n• Assembly in India or China\n• Sold globally\n\nMETHODS MNCs USE:\n1. Set up own factories abroad\n2. Buy local companies (acquisitions — Corus by TATA, Jaguar by TATA)\n3. Joint ventures with local companies\n4. Outsourcing — giving work to local companies (Nike to Asian factories)\n\nIMPACT ON HOST COUNTRIES (like India):\nPositive:\n• Employment and income\n• Technology and management skills transfer\n• Tax revenue\n• Better quality products\nNegative:\n• Profits repatriated abroad\n• Competition damages local companies\n• Environmental concerns\n• Low wages, poor conditions in some cases\n\nIMPACT ON HOME COUNTRIES:\n• Jobs may move to cheap labour countries ('outsourcing')\n• Cheaper goods for consumers\n\nCONCLUSION: MNCs are central to globalisation — they are the main mechanism by which production, capital and technology flow across borders."}
      ],
      passage: [
        {q:"'MNCs are looking for locations where they can get cheap manufacturing labour. For large multinationals, even a small difference in wages across countries can mean large differences in overall costs.'\n\n(a) What is a Multinational Corporation?\n(b) Why do MNCs prefer countries with cheaper labour?\n(c) What can Indian workers gain and lose from MNC investment?\n(d) What is outsourcing? Give an example.",a:"(a) A Multinational Corporation (MNC) is a company that owns or controls production in more than one country. It has its headquarters in one country but factories, offices and operations in many countries. Examples: Apple, Samsung, Coca-Cola, Unilever, Toyota.\n\n(b) MNCs prefer countries with cheaper labour because:\n• Labour is often the largest cost in manufacturing\n• Even small differences in wages translate to huge savings at large scales\n• A company making millions of products can save enormous amounts\n• Developing countries like India, China, Bangladesh, Vietnam have labour costs far below USA/Europe\n• This allows MNCs to be more competitive on global markets with lower production costs\n\n(c) Indian workers — gains and losses:\nGAINS:\n• New employment opportunities in factories, IT, BPO\n• Higher wages than in unorganised sector\n• Exposure to modern technology and management\n• Ancillary industries also develop, creating more jobs\n\nLOSSES:\n• Often hired on short-term contracts through contractors — no job security\n• May not get labour law protections (PF, health insurance)\n• Work may be repetitive, low-skill assembly\n• If MNC leaves, workers lose jobs (footloose capital)\n• May suppress wages by threatening to move elsewhere\n\n(d) Outsourcing: When a company gives its work to an outside firm rather than doing it in-house, especially in another country.\n\nExample: American companies outsource customer service call centres to India. Indian workers answer calls from American customers for companies like Amazon, Dell, AT&T. India benefits from IT/BPO jobs; American companies save costs."}
      ]
    },

    "Consumer Rights": {
      mcq: [
        {q:"The Consumer Protection Act in India was passed in:",opts:["1947","1975","1986","2000"],ans:2},
        {q:"Which day is observed as World Consumer Rights Day?",opts:["January 26","March 15","April 5","October 24"],ans:1},
        {q:"The 'Right to Safety' as a consumer right means:",opts:["Right to drive safely","Protection against marketing of goods harmful to life and property","Right to be safe from other consumers","Right to safe roads"],ans:1},
        {q:"ISI mark on products indicates:",opts:["Indian Standard Institute approval","The product meets quality standards set by Bureau of Indian Standards","Only Indian-made goods","Government guarantee"],ans:1},
        {q:"Agmark is a quality certification for:",opts:["Electronics","Agricultural products","Medicines","Textiles"],ans:1},
        {q:"Which logo ensures the quality of jewellery in India?",opts:["ISI","Agmark","Hallmark","FPO"],ans:2},
        {q:"Consumer courts in India are structured as:",opts:["Only national court","Only state court","Three-tier: District, State and National forums","Only civil courts"],ans:2},
        {q:"'Right to Information' as a consumer right includes:",opts:["Right to any information from anyone","Right to be informed about quality, quantity, potency, purity, standard and price of goods","Right to government secrets","Right to others' personal information"],ans:1},
        {q:"Which of the following is NOT a consumer right?",opts:["Right to choose","Right to be heard","Right to manufacture goods","Right to seek redressal"],ans:2},
        {q:"A consumer can file a complaint in District Consumer Forum if the value of goods/services is up to:",opts:["₹1 lakh","₹20 lakh","₹1 crore","₹50 lakh"],ans:2},
        {q:"RTI Act (Right to Information) was passed in:",opts:["2000","2005","2010","1986"],ans:1},
        {q:"The 'Jago Grahak Jago' campaign was launched by:",opts:["Private companies","Government of India","Consumer courts","Banks"],ans:1},
        {q:"When a seller does not give the bill/receipt, the consumer loses the right to:",opts:["Use the product","Seek redressal/complain about the product","Speak about the product","Purchase again"],ans:1},
        {q:"Consumer exploitation occurs because of:",opts:["Good governance","Lack of information, less competition, inadequate consumer awareness","Too many consumer courts","Strong consumer movements"],ans:1},
        {q:"COPRA (Consumer Protection Act) gives consumers the right to seek redressal against:",opts:["Only physical products","Unfair trade practices and exploitation","Only services","Only medicines"],ans:1}
      ],
      short: [
        {q:"What are consumer rights? List and explain any four rights of consumers in India.",a:"CONSUMER RIGHTS IN INDIA (under COPRA 1986):\n\n1. RIGHT TO SAFETY:\n• Protection against products and services that are hazardous to health and property\n• Example: Medicines must meet safety standards; electrical appliances must not cause shock\n• Enforced by: Bureau of Indian Standards, Drug Control Authority\n\n2. RIGHT TO INFORMATION:\n• Consumer has right to know about quality, quantity, potency, purity, standard and price\n• Example: Food packaging must show ingredients, manufacturing date, MRP\n• Enforced by: Labelling laws, RTI Act\n\n3. RIGHT TO CHOOSE:\n• Consumer must have access to variety of goods and services at competitive prices\n• No monopoly should force consumer to buy only one product\n• Example: Telecom sector — consumers choose from multiple operators\n\n4. RIGHT TO BE HEARD:\n• Consumer's interests must be given due consideration\n• Consumer forums where complaints are heard\n• Example: Consumer can file complaint in District Consumer Forum\n\n5. RIGHT TO SEEK REDRESSAL:\n• Compensation for unfair trade practices or exploitation\n• Three-tier consumer court system\n\n6. RIGHT TO CONSUMER EDUCATION:\n• Consumer should have knowledge of all rights\n• 'Jago Grahak Jago' campaign"},
        {q:"How can consumers protect themselves? Describe the three-tier consumer dispute redressal system.",a:"HOW CONSUMERS CAN PROTECT THEMSELVES:\n1. Check quality certifications (ISI, Agmark, Hallmark, FPO)\n2. Always demand a bill/receipt\n3. Check expiry dates on food and medicine\n4. Read labels carefully\n5. Complain if cheated — don't accept exploitation\n6. Join consumer awareness groups\n\nTHREE-TIER CONSUMER DISPUTE REDRESSAL SYSTEM:\n\n1. DISTRICT CONSUMER FORUM:\n• For claims up to ₹1 crore (current limit)\n• Complaints can be filed locally\n• Accessible to common people\n\n2. STATE CONSUMER COMMISSION:\n• For claims between ₹1 crore and ₹10 crore\n• Located at state capital\n• Appeals from District Forum also heard here\n\n3. NATIONAL CONSUMER COMMISSION (NCDRC):\n• For claims above ₹10 crore\n• Located in New Delhi\n• Highest consumer court; appeals from State Commission\n• Final appeal can go to Supreme Court\n\nPROCESS: Consumer files complaint → Forum examines → Company must respond → Redressal ordered (refund, replacement, compensation)"},
        {q:"Why is consumer awareness important in India? What are the factors that lead to consumer exploitation?",a:"CONSUMER EXPLOITATION OCCURS BECAUSE OF:\n\n1. LACK OF INFORMATION: Consumers don't know the right price, quality standards, ingredients\n2. ILLITERACY: Cannot read labels, contracts, instructions\n3. LESS COMPETITION: Monopoly or oligopoly allows sellers to exploit\n4. COMPLICATED PRODUCTS/SERVICES: Financial products, medicines — consumers can't evaluate quality\n5. UNORGANISED CONSUMERS: Sellers are organised; individual consumers are not\n6. WEAK ENFORCEMENT: Consumer protection laws exist but enforcement is weak\n7. REMOTE AREAS: Less competition, less choice for rural consumers\n8. CULTURAL ATTITUDES: 'Customer is always wrong' mentality\n\nIMPORTANCE OF CONSUMER AWARENESS:\n1. Informed consumers can demand value for money\n2. Can identify and report fraud\n3. Can seek redressal when exploited\n4. Creates competition — sellers improve quality\n5. Reduces exploitation of vulnerable groups\n6. Strengthens consumer protection system\n\nGOVERNMENT STEPS:\n• 'Jago Grahak Jago' campaign\n• Consumer courts easily accessible\n• Quality certification marks (ISI, Agmark)\n• RTI Act for information access\n• National Consumer Helpline"}
      ],
      long: [
        {q:"Describe the evolution of consumer rights and the consumer movement in India. How effective is the consumer protection system?",a:"EVOLUTION OF CONSUMER MOVEMENT:\n\nHISTORY:\n• In earlier times: 'caveat emptor' (let the buyer beware) — seller had no responsibility\n• Industrial Revolution: Mass production created distance between producer and consumer\n• USA: Consumer movement started in 1960s — Ralph Nader's campaign against unsafe cars\n• International: March 15 declared World Consumer Rights Day (1962 Kennedy's Consumer Bill of Rights)\n\nINDIA:\n• 1960s-70s: Consumer organisations raised awareness, published reports on adulteration\n• 1986: CONSUMER PROTECTION ACT (COPRA) — landmark legislation\n  - Created consumer courts at district, state, national levels\n  - Gave consumers legal rights and quick redressal\n• 1991: Economic liberalisation brought more choices but also new risks\n• 2005: RTI Act — consumers can access government information\n• 2019: COPRA amended — stronger provisions, product liability, e-commerce\n\nCONSUMER RIGHTS UNDER COPRA:\nSafety, Information, Choice, Heard, Redressal, Consumer Education\n\nEFFECTIVENESS:\nPositive:\n• Consumer courts have given redressal in lakhs of cases\n• Quality certification (ISI, Agmark) improved product standards\n• Greater consumer awareness\nNegative:\n• Courts overwhelmed — long delays\n• Most consumers still unaware of rights\n• Rural consumers face more exploitation\n• Enforcement of labelling and quality standards weak\n• Digital marketplace creates new challenges\n\nCONCLUSION: Progress has been made but much more needed. Consumer awareness, effective enforcement and accessible courts are key needs."}
      ],
      passage: [
        {q:"'The movement began as a VoiCe against profiteering and shortage of food grains. The Consumer Protection Act (COPRA) was passed in India in 1986. Under COPRA, a three-tier quasi-judicial machinery at the district, state and national levels was set up for redressal of consumer disputes.'\n\n(a) Why was COPRA passed?\n(b) What is a 'quasi-judicial' body?\n(c) What can a consumer do if cheated by a shopkeeper?\n(d) Give one example of a quality mark and explain its significance.",a:"(a) COPRA (Consumer Protection Act) was passed in 1986 because:\n• Consumers were being exploited through adulteration, short weights, overcharging, selling defective goods\n• Existing laws (IPC etc.) were not sufficient or accessible for consumer complaints\n• Growing consumer movement demanded specific legislation\n• Need to create accessible, quick and inexpensive dispute resolution for consumers\n• India joined international consumer protection movement (post Kennedy's consumer rights declaration)\n\n(b) Quasi-judicial body: A body that has characteristics of both a government department and a court. It:\n• Is NOT a formal court but has judicial powers\n• Can examine cases, hear evidence, call witnesses\n• Give decisions that are legally binding\n• Consumer forums are quasi-judicial — they act like courts but are more accessible and less formal\n• Their decisions can be appealed to higher consumer forums\n\n(c) If cheated by a shopkeeper, a consumer can:\n1. First demand replacement, refund or apology from shopkeeper\n2. If not satisfied, collect proof (bill, product, photos)\n3. File a complaint at District Consumer Forum (for amounts up to ₹1 crore)\n4. The forum examines the complaint and the shopkeeper must respond\n5. Forum can order refund, compensation, and impose penalty\n6. The process is relatively quick and inexpensive compared to regular courts\n\n(d) ISI (Indian Standards Institute/Bureau of Indian Standards) mark:\n• Printed on electrical goods, cement, packaged food etc.\n• Indicates the product has been tested and meets quality and safety standards set by Bureau of Indian Standards\n• Significance: Consumer can trust the product is safe, not adulterated, meets specifications\n• Other marks: Agmark (agricultural products), Hallmark (gold jewellery), FPO (food products)"}
      ]
    }
  }
};
