const SOCIAL_DP_QUESTIONS_DB = {
  "social_dp": {

    "Power Sharing": {
      mcq: [
        {q:"Belgium is a small country in:",opts:["Asia","Africa","Europe","South America"],ans:2},
        {q:"What percentage of Belgium's population lives in the Flemish region and speaks Dutch?",opts:["40%","59%","80%","20%"],ans:1},
        {q:"In Belgium, what percentage of Brussels population speaks French?",opts:["20%","40%","59%","80%"],ans:3},
        {q:"Sri Lanka became independent in:",opts:["1947","1948","1950","1952"],ans:1},
        {q:"The Sinhalese account for what percentage of Sri Lanka's population?",opts:["18%","74%","50%","60%"],ans:1},
        {q:"Which Sri Lankan Act made Sinhala the only official language?",opts:["Language Act 1948","Sinhala Only Act 1956","Official Language Act 1960","Ceylon Act 1972"],ans:1},
        {q:"Power sharing in Belgium led to:",opts:["Civil war","Successful accommodation of diversity","Military rule","Division of the country"],ans:1},
        {q:"The Belgium model gave equal representation to French and Dutch speakers in the:",opts:["Parliament","Army","Central cabinet","President's office"],ans:2},
        {q:"Horizontal distribution of power shares power among:",opts:["Different levels of government","Different organs at the same level (legislature, executive, judiciary)","Different communities","Centre and states"],ans:1},
        {q:"Vertical distribution of power shares power among:",opts:["Legislature, executive and judiciary","Different levels — central, state, local","Different communities","Political parties"],ans:1},
        {q:"Community government in Belgium is elected by:",opts:["All citizens","People belonging to one language community","Parliament","President"],ans:1},
        {q:"Which of these is a prudential reason for power sharing?",opts:["Power sharing is morally good","Power sharing reduces conflict and ensures stability","Power sharing is constitutionally required","Power sharing increases efficiency"],ans:1},
        {q:"Which of these is a moral reason for power sharing?",opts:["Power sharing reduces violence","Power sharing ensures stability","Power sharing is the very spirit of democracy — citizens have a right to participate","Power sharing is economically beneficial"],ans:2},
        {q:"The civil war in Sri Lanka caused:",opts:["Economic prosperity","Forced displacement and thousands of deaths","International support","Peace and harmony"],ans:1},
        {q:"Power sharing among different social groups is an example of:",opts:["Horizontal sharing","Vertical sharing","Sharing among different organs","Sharing among political parties"],ans:0}
      ],
      short: [
        {q:"Describe the ethnic composition of Belgium and the problems it created.",a:"ETHNIC COMPOSITION OF BELGIUM:\n• Total population: slightly over 1 crore\n• 59% in Flemish region — speak Dutch\n• 40% in Wallonia region — speak French\n• 1% speak German\n• In Brussels (capital): 80% French, 20% Dutch-speaking\n\nPROBLEMS CREATED:\n• Minority French-speaking community was relatively rich and powerful\n• Dutch-speaking majority resented this and demanded equal representation\n• Tension arose between the two communities\n• Both communities had strong feelings and this could have led to conflict\n\nSOLUTION:\nBelgium adopted a power-sharing model:\n• Equal representation in central cabinet regardless of majority\n• Community governments for each language group\n• Separate governments for regions\nThis accommodation maintained national unity and helped Belgium become a part of EU."},
        {q:"Why did Sri Lanka fail where Belgium succeeded? Compare the two cases.",a:"BELGIUM — SUCCEEDED:\n• Recognised that cultural diversity was a strength\n• Gave equal representation to both communities\n• Created community governments for each language group\n• Amended constitution multiple times (1970, 1993) to accommodate diversity\n• Result: Peaceful, united country; member of EU\n\nSRI LANKA — FAILED:\n• Adopted majoritarian approach — 'Sinhala Only' Act (1956)\n• Sinhala majority ignored Tamil minority's legitimate concerns\n• Tamils felt alienated, discriminated against in government jobs, universities\n• Tamil parties demanded autonomy → escalated to demand for separate state (Eelam)\n• Led to CIVIL WAR — thousands killed, millions displaced\n• Country deeply divided\n\nKEY LESSON: Power sharing and accommodation of minorities creates unity; majoritarianism creates division and conflict."},
        {q:"What are the different forms of power sharing in modern democracies?",a:"FORMS OF POWER SHARING:\n\n1. HORIZONTAL POWER SHARING:\nPower shared among different organs of government at the same level.\n• Legislature makes laws\n• Executive implements laws\n• Judiciary interprets laws and checks both\n• No single organ has unlimited power\n\n2. VERTICAL POWER SHARING:\nPower shared among different levels of government.\n• Central government\n• State governments\n• Local governments (panchayats, municipalities)\n\n3. SHARING AMONG SOCIAL GROUPS:\nPower given to different communities, linguistic groups:\n• Community government in Belgium\n• Reservations for SC, ST, OBC in India\n\n4. SHARING AMONG POLITICAL PARTIES:\n• Different political parties share power through coalition governments\n• Opposition parties check ruling party\n• Interest groups and pressure groups influence policies"}
      ],
      long: [
        {q:"'Power sharing is the very spirit of democracy.' Explain this statement with reference to the prudential and moral reasons for power sharing.",a:"POWER SHARING IS THE SPIRIT OF DEMOCRACY:\n\nMORAL REASONS (Why it is RIGHT):\n1. Democracy means rule of the people, by the people, for the people. If power is shared, it means citizens participate in governance — this IS democracy.\n2. In a diverse society, no single community has the right to dominate others.\n3. Each group has legitimate interests that deserve representation.\n4. Power sharing respects human dignity and autonomy.\n5. It upholds the value of political equality.\n\nPRUDENTIAL REASONS (Why it is WISE/PRACTICAL):\n1. REDUCES CONFLICT: When all groups have share in power, they have less reason to feel alienated and resort to violence. Sri Lanka's civil war shows what happens when minorities are excluded.\n2. ENSURES STABILITY: Countries with power sharing tend to be more politically stable.\n3. PREVENTS TYRANNY: Checks and balances prevent concentration of power and abuse.\n4. LONG-TERM BENEFITS: Even if sharing seems to reduce efficiency short-term, it ensures long-term stability.\n\nBELGIUM EXAMPLE: Belgium's power sharing model maintained unity in a diverse country and made it a strong EU member — showing that sharing power is both morally right AND practically wise.\n\nCONCLUSION: Democracy cannot function without power sharing. It is not just a compromise but the very principle that makes democracy legitimate and stable."}
      ],
      passage: [
        {q:"Read the following:\n\n'Sri Lanka adopted a majoritarian policy. The Sinhala Only Act was passed in 1956. The government followed preferential policies favouring Sinhala applicants for university positions and government jobs. The constitution stipulated that the state shall protect and foster Buddhism.'\n\n(a) What is majoritarianism?\n(b) How did this policy affect the Tamil community?\n(c) What was the consequence for Sri Lanka?\n(d) What lesson does this hold for democratic countries?",a:"(a) Majoritarianism is the belief that the majority community should rule the country in whatever way it wants, without considering the needs and wishes of minority communities. It ignores minority rights and interests.\n\n(b) Impact on Tamil community:\n• Tamil language was removed as official language → Tamils couldn't get government jobs\n• Preference given to Sinhalese in universities and government → Tamils discriminated against\n• Buddhism made state religion → non-Buddhists (mostly Tamils who are Hindu/Christian) felt excluded\n• Tamils felt like second-class citizens in their own country\n\n(c) Consequences for Sri Lanka:\n• Tamils demanded equal rights and autonomy\n• When demands were ignored, Tamil groups demanded a separate state (Eelam)\n• Civil war broke out, lasting decades\n• Thousands killed, millions displaced\n• Country suffered economically and socially\n• The civil war ended in 2009 with great violence\n\n(d) Lesson: In diverse societies, majoritarian policies create alienation, resentment and conflict. True democracy requires protecting minority rights and sharing power with all communities. Accommodation and power sharing are essential for national unity."}
      ]
    },

    "Federalism": {
      mcq: [
        {q:"Federalism is a system in which power is divided between:",opts:["Legislature and executive","Central and state governments","Government and citizens","Judiciary and executive"],ans:1},
        {q:"Which is NOT a feature of a federal government?",opts:["Two or more levels of government","Written constitution","Supremacy of one level over others","Independent judiciary"],ans:2},
        {q:"India is described in the Constitution as:",opts:["A federation","A confederation","A Union of States","A unitary state"],ans:2},
        {q:"The Union List contains subjects:",opts:["State governments control","Both centre and states share","Only the central government controls","Local governments handle"],ans:2},
        {q:"The Concurrent List contains subjects:",opts:["Only Central government controls","Both Centre and State can make laws","Only states control","Local bodies manage"],ans:1},
        {q:"If there is a conflict between central and state laws on Concurrent List subjects:",opts:["State law prevails","Central law prevails","Supreme Court decides","Both laws apply"],ans:1},
        {q:"The Residuary subjects (not in any list) are handled by:",opts:["State governments","Local governments","Central government","Courts"],ans:2},
        {q:"The policy of Decentralisation in India was strengthened by the Constitutional Amendment in:",opts:["1952","1972","1992","2002"],ans:2},
        {q:"The 73rd Constitutional Amendment made Panchayati Raj institutions:",opts:["Optional","Constitutionally mandatory","Advisory","Abolished"],ans:1},
        {q:"Which of the following is a coming-together federation?",opts:["India","Belgium","Spain","USA, Switzerland, Australia"],ans:3},
        {q:"Which of the following is a holding-together federation?",opts:["USA","Australia","Switzerland","India, Belgium, Spain"],ans:3},
        {q:"Language policy of India made __ as the official language:",opts:["Hindi only","English only","Hindi + English + 21 regional languages (22 scheduled languages)","Sanskrit"],ans:2},
        {q:"Coalition government means:",opts:["Single party majority","No party has majority — parties join together to form government","Military government","Presidential government"],ans:1},
        {q:"The Gram Sabha consists of:",opts:["Elected Panchayat members only","All adult members of the village","Only the Sarpanch","State government representatives"],ans:1},
        {q:"Which subject is in the State List?",opts:["Defence","Railways","Agriculture","Currency"],ans:2}
      ],
      short: [
        {q:"What is federalism? What are its key features?",a:"FEDERALISM: A system of government in which power is divided between a central government and various constituent units of the country (states/provinces).\n\nKEY FEATURES:\n1. TWO LEVELS OF GOVERNMENT: Central and state governments (in India, also local governments — third tier)\n2. EACH HAS JURISDICTION: Each level has its own area of authority — not subject to the other\n3. CONSTITUTIONALLY GUARANTEED: Division of power written in constitution; cannot be changed unilaterally\n4. INDEPENDENT JUDICIARY: Supreme Court/High Courts to resolve disputes between levels\n5. FINANCIAL INDEPENDENCE: Each level has its own revenue sources\n6. DUAL CITIZENSHIP: Citizens have both national and state identity\n7. CONSTITUTIONAL AMENDMENT: Special procedure required to change power division — usually needs approval of both levels"},
        {q:"Distinguish between 'coming together' and 'holding together' federations. Which type is India?",a:"COMING-TOGETHER FEDERATIONS:\n• Independent states voluntarily join to form a larger unit\n• States want to pool sovereignty while retaining identity\n• States have more powers (stronger states)\n• Examples: USA, Switzerland, Australia\n• States agreed to give some powers to centre for common benefit\n\nHOLDING-TOGETHER FEDERATIONS:\n• A large country decides to divide power to accommodate diversity\n• Central government often stronger than states\n• States may have unequal powers\n• Examples: INDIA, Belgium, Spain\n• Centre divided power among states to hold together diverse nation\n\nINDIA'S TYPE:\nIndia is a HOLDING-TOGETHER federation because:\n• India was one country and power was devolved to states\n• Centre is stronger than states in India\n• States have unequal powers (some have special provisions)\n• Created to accommodate linguistic, cultural and regional diversity"},
        {q:"How has decentralisation strengthened democracy in India? What are the functions of Panchayati Raj?",a:"DECENTRALISATION IN INDIA:\nThe 73rd and 74th Constitutional Amendments (1992) made the third tier (local governments) constitutionally mandatory.\n\nPANCHAYATI RAJ (Rural):\n• Three-level structure: Village Panchayat, Block Samiti, Zila Parishad\n• Gram Sabha: All adult members of village — foundation of democracy\n• Elections mandatory every 5 years\n• 1/3 seats RESERVED for women (many states 1/2)\n• Reserved seats for SC and ST\n\nFUNCTIONS:\n1. Village development — roads, drainage, housing\n2. Primary education and health care\n3. Implementation of government schemes\n4. Collection of local taxes\n5. Maintenance of local records\n6. Agriculture and minor irrigation\n\nIMPORTANCE:\n• Brings democracy to grassroots level\n• People directly participate in local governance\n• Women and marginalised communities get representation\n• Local problems solved locally\n• About 30 lakh elected representatives in panchayats — world's largest democratic experiment"}
      ],
      long: [
        {q:"Describe the three-fold distribution of legislative powers in India. How does it maintain federal balance?",a:"THREE LISTS IN THE CONSTITUTION:\n\n1. UNION LIST (97 subjects):\n• Subjects of national importance\n• Only Parliament can make laws\n• Examples: Defence, foreign affairs, banking, communications, currency, railways, atomic energy\n\n2. STATE LIST (66 subjects):\n• Subjects of local and regional importance\n• Only State legislatures can make laws (normally)\n• Examples: Police, trade, commerce, agriculture, irrigation, education (before 1976)\n\n3. CONCURRENT LIST (47 subjects):\n• Both Parliament and State can make laws\n• In case of conflict: Central law prevails\n• Examples: Education, forests, trade unions, marriage, adoption, succession\n\nRESIDUARY POWERS:\n• Any subject not in any list → Central government has power\n• Shows India's tilt towards central authority\n\nFEDERAL BALANCE:\n• Each level has clear jurisdiction — reduces conflicts\n• Concurrent List allows both levels to legislate — flexible\n• Centre's supremacy on Concurrent List resolves conflicts\n• Special courts (Supreme Court) resolve centre-state disputes\n• Amendment to redistribute powers requires special procedure\n\nCRITIQUE: India is more centralised than typical federations — governors appointed by centre, states financially dependent on centre, President's Rule can dismiss state governments."}
      ],
      passage: [
        {q:"'India's Constitution originally provided for a two-tier system of government — the Union Government representing the Indian Union, and the States. Later, a third tier of federalism was added in the form of Panchayats and Municipalities.'\n\n(a) What is the significance of the third tier of government?\n(b) What was the 73rd Constitutional Amendment about?\n(c) What is a Gram Sabha?\n(d) How has decentralisation helped women?",a:"(a) The third tier (Panchayats and Municipalities) brings government closest to the people at the grassroots level. It enables local self-governance, allows people to directly participate in decisions affecting their lives, and ensures that local problems are solved locally by elected representatives from the community itself.\n\n(b) The 73rd Constitutional Amendment (1992) made Panchayati Raj institutions constitutionally mandatory. It required:\n• Elections to panchayats every 5 years\n• Reservation of 1/3 seats for women\n• Reservation for SC and ST\n• State Election Commissions to conduct elections\n• State Finance Commissions for allocation of funds\nThis gave constitutional status to local bodies.\n\n(c) Gram Sabha is the body of ALL adult members of a village. It is the foundation of Panchayati Raj. The Gram Sabha:\n• Meets periodically to discuss village issues\n• Approves the plans and budget of the Gram Panchayat\n• Reviews the work done by the Panchayat\n• It is the primary democratic forum at village level\n\n(d) Decentralisation has helped women by:\n• Constitutional reservation of 1/3 (or 1/2 in some states) of all seats for women\n• About 10 lakh women are elected representatives in Panchayats\n• Women have gained political experience and confidence\n• Issues affecting women (health, water, education) get more attention\n• Challenged patriarchal attitudes at grassroots level"}
      ]
    },

    "Gender, Religion and Caste": {
      mcq: [
        {q:"The sexual division of labour means:",opts:["Equal division of work","Women do domestic work; men work outside","Both genders do all work equally","Men do more work than women"],ans:1},
        {q:"Feminist movements demanded:",opts:["More housework for women","Equal rights for women — political, social, economic","Separate state for women","Only voting rights"],ans:1},
        {q:"In India, what percentage of elected MPs are women (approximately)?",opts:["50%","30%","Under 15%","25%"],ans:2},
        {q:"Which Nordic countries have very high female political representation?",opts:["UK and France","Sweden and Norway","Germany and Italy","Russia and China"],ans:1},
        {q:"'Communalism' in politics refers to:",opts:["Community development","Using religion for narrow political goals that may harm others","Religious harmony","Community service"],ans:1},
        {q:"A secular state means:",opts:["A state with one official religion","A state that establishes and practices religion","A state that has no official religion and treats all religions equally","A state that bans religion"],ans:2},
        {q:"Caste in politics refers to:",opts:["Caste discrimination only","Caste identities being used in political mobilisation and voting","Abolition of caste","Caste-based reservations only"],ans:1},
        {q:"The Indian Constitution prohibited any discrimination based on caste in:",opts:["1950 only","Article 15 and 16","Only in rural areas","Only in government jobs"],ans:1},
        {q:"When only men work outside and women only do household work, this creates:",opts:["Economic equality","Unequal power relations","Social harmony","Better development"],ans:1},
        {q:"The practice of untouchability was officially abolished by:",opts:["Independence Act 1947","Constitution of India 1950","Caste Act 1955","Both B and C"],ans:3},
        {q:"Which of the following is a form of communalism?",opts:["Following one's religion","Religious tolerance","Belief that one's own religion is superior and others should be dominated","Inter-religious dialogue"],ans:2},
        {q:"In India, women still earn how much less than men for similar work?",opts:["10% less","Same as men","Significantly less — gender pay gap exists","More than men"],ans:2},
        {q:"Reservation policy for OBC was recommended by:",opts:["Constituent Assembly","Mandal Commission","Nehru Committee","Planning Commission"],ans:1},
        {q:"Which statement about caste and politics is CORRECT?",opts:["Caste and politics don't interact","Political parties never appeal to caste sentiments","Universal suffrage has reduced dominance of upper castes","Caste has completely disappeared from politics"],ans:2},
        {q:"When more than one caste is brought together for political purposes, it is called:",opts:["Casteism","Caste consolidation","Political mobilisation","Social reform"],ans:1}
      ],
      short: [
        {q:"What is meant by sexual division of labour? How does it affect women's status?",a:"SEXUAL DIVISION OF LABOUR: A social arrangement where all work inside the home (cooking, cleaning, child-rearing) is done by women, and work outside (earning income) is done by men.\n\nThis division:\n• Is not natural — it is based on social expectations and stereotypes\n• Is not absolute — women DO work outside too (in fields, as domestic workers, in offices)\n• But women's work is NOT valued equally\n\nEFFECTS ON WOMEN'S STATUS:\n1. ECONOMIC DEPENDENCE: Women doing unpaid household work = no income = financial dependence on men\n2. POWER IMBALANCE: Economic dependence leads to less decision-making power in family\n3. DOUBLE BURDEN: Working women do both office work AND all household work\n4. UNDERVALUATION: Women's domestic labour contributes to economy but is not counted in GDP\n5. LIMITED POLITICAL PARTICIPATION: Women have less time and resources for public life\n6. LOWER STATUS: Society values paid work more than domestic work → women get lower social status\n\nNEED: Equal sharing of domestic responsibilities between men and women is essential for true gender equality."},
        {q:"What is communalism? How does it manifest in politics?",a:"COMMUNALISM: A belief that people of the same religion have similar political interests and these are different from and opposed to the interests of people of other religions.\n\nFORMS OF COMMUNALISM:\n1. Belief that one's religion is superior to others\n2. Belief that people of different religions cannot live as equal citizens\n3. Using religion for narrow political purposes that harm other communities\n4. Religious identity being used to mobilise votes\n\nHOW IT MANIFESTS IN POLITICS:\n• Politicians make appeals in the name of religion during elections\n• Communal violence is sometimes used to polarise voters\n• Policies framed to benefit one religious community at the expense of others\n• Stereotypes and prejudices about other religions spread for political gain\n• Extreme form: Communal riots and targeted violence\n\nSECULAR RESPONSE:\nIndia is a secular state — the Constitution prohibits discrimination based on religion. The state:\n• Has no official religion\n• Gives equal status to all religions\n• Does not interfere in religious affairs\n• But also does not allow religion to be used against others"},
        {q:"How has caste influenced politics in India? Give examples of positive and negative aspects.",a:"CASTE IN POLITICS — NEGATIVE ASPECTS:\n1. VOTE BANK POLITICS: Politicians appeal to caste sentiments — ask people to vote for candidates of their caste\n2. DISCRIMINATION: Upper castes dominated governance; lower castes excluded\n3. CASTE VIOLENCE: Conflicts between castes over land, water, social status\n4. NEPOTISM: Caste-based favouritism in appointments\n5. DIVISIVE: Caste identity can override national interest\n\nCASTE IN POLITICS — POSITIVE ASPECTS:\n1. MOBILISATION FOR RIGHTS: Dalits, OBCs used political mobilisation to demand equal rights and representation\n2. RESERVATIONS: Political pressure from lower castes led to reservations in education and government jobs\n3. EXPANDED DEMOCRACY: Universal adult franchise reduced dominance of upper castes\n4. ASSERTION: Lower castes gaining political power has helped reduce discrimination\n5. SOCIAL REFORM: Political movements challenged caste hierarchy (Ambedkar, Periyar)\n\nCURRENT SITUATION:\n• No state where caste is the SOLE factor in electoral outcomes\n• Other factors (development, corruption, leadership) also matter\n• Caste and politics interact in complex ways\n• Both reinforce and challenge each other"}
      ],
      long: [
        {q:"Discuss the status of women in Indian politics. What measures are needed to improve women's political participation?",a:"STATUS OF WOMEN IN INDIAN POLITICS:\n\nLEGAL RIGHTS: Women have equal voting rights since 1947. Can contest elections, hold any position.\n\nACTUAL SITUATION:\n• Women constitute less than 15% of Lok Sabha members — far below gender parity\n• Even lower in state assemblies\n• Very few women Chief Ministers, Cabinet Ministers\n• Contrast: Nordic countries (Sweden, Norway) have 40-50% women in parliaments\n\nFACTORS LIMITING PARTICIPATION:\n1. DOMESTIC BURDEN: Women responsible for household work — less time for politics\n2. ECONOMIC DEPENDENCE: Less financial resources for election campaigns\n3. SOCIAL ATTITUDES: Many families/societies don't encourage women in public life\n4. VIOLENCE AND THREATS: Women face intimidation in political arena\n5. PATRIARCHAL PARTIES: Political parties give fewer tickets to women candidates\n\nMEASURES NEEDED:\n1. WOMEN'S RESERVATION BILL: Reserve 33% seats in Parliament and state legislatures for women (like in panchayats)\n2. EDUCATION: Educate girls equally → more qualified women leaders\n3. ECONOMIC EMPOWERMENT: Women with economic independence can participate more\n4. CHANGE IN SOCIAL ATTITUDES: Men must share domestic responsibilities\n5. PARTY COMMITMENT: Political parties should give more tickets to women\n6. ROLE MODELS: More women leaders inspire others\n\nPOSITIVE DEVELOPMENT: Panchayati Raj reservation has created 10 lakh+ women elected representatives — building a pipeline of women leaders."}
      ],
      passage: [
        {q:"'In India, caste can take various forms in politics. When voters and political parties pay attention only to caste of a candidate or voter, that is an unhealthy tendency. But when political mobilisation takes place along caste lines to challenge caste discrimination and demand justice, it can be a positive development.'\n\n(a) Give an example of caste being used in a negative way in politics.\n(b) Give an example of caste mobilisation being used positively.\n(c) What is the role of reservations in addressing caste inequality?\n(d) Is caste the only factor that determines electoral outcomes in India?",a:"(a) Negative use of caste in politics:\n• Political parties distributing election tickets based on caste of candidates rather than their ability\n• Politicians making speeches that appeal to caste pride or prejudice to get votes\n• Using caste violence/discrimination to polarise communities before elections\n• Forming governments based on caste arithmetic rather than governance ability\n\n(b) Positive use of caste mobilisation:\n• Dalit and OBC leaders using caste identity to organise politically and demand reservation, anti-discrimination laws and social justice\n• Ambedkar's movement used Dalit identity to fight untouchability\n• OBC movements demanding Mandal Commission recommendations implementation\n• These movements reduced dominance of upper castes and expanded democracy\n\n(c) Role of reservations:\n• Reservations in education and government jobs for SC, ST and OBC give opportunities to historically disadvantaged groups\n• Political reservations (in panchayats) ensure representation of marginalised communities\n• However, reservations alone cannot end caste discrimination — social attitudes must also change\n\n(d) No, caste is NOT the only factor:\n• Development track record of the government\n• Personal image and integrity of the candidate\n• National issues and leadership\n• Economic conditions\n• Multiple caste groups need to be combined — no single caste is a majority anywhere\n• Other identities (language, religion, class) also matter"}
      ]
    },

    "Political Parties": {
      mcq: [
        {q:"A political party is:",opts:["A group that contests elections only","A group of people who come together to contest elections and hold power to implement certain policies","Only the ruling party","A group that opposes government"],ans:1},
        {q:"Which of these is NOT a function of political parties?",opts:["Contest elections","Form and run governments","Spread literacy","Shape public opinion"],ans:2},
        {q:"In India, how many 'National Parties' are recognised by the Election Commission (approximately)?",opts:["2","4","6 (currently)","10"],ans:2},
        {q:"A party is recognised as a 'National Party' if it:",opts:["Has the most seats","Gets at least 6% votes in at least 4 states and wins 4 Lok Sabha seats","Is the ruling party","Has offices in all states"],ans:1},
        {q:"The Indian National Congress was founded in:",opts:["1885","1905","1920","1947"],ans:0},
        {q:"The Bharatiya Janata Party (BJP) was founded in:",opts:["1947","1964","1980","1984"],ans:2},
        {q:"Which of the following is a regional party?",opts:["BJP","INC","Bahujan Samaj Party — actually national; Telegu Desam Party is regional","CPI"],ans:2},
        {q:"The party system in India is best described as:",opts:["One-party system","Two-party system","Multi-party system","Federal party system"],ans:2},
        {q:"The role of opposition parties in a democracy is to:",opts:["Oppose everything","Check and control the ruling party","Destabilise the government","Only win the next election"],ans:1},
        {q:"Political parties in India face which challenge?",opts:["Too much transparency","Lack of internal democracy — power concentrated in top leaders","Too many candidates","Excessive party membership"],ans:1},
        {q:"Which reform has been introduced to make political parties more transparent?",opts:["Parties publish all accounts","Parties submit accounts to Election Commission","No reform yet","Compulsory internal elections"],ans:1},
        {q:"What is 'party ideology'?",opts:["The uniform parties wear","A set of beliefs and values that guide the party's policies","The party's flag and symbol","The party's election promises only"],ans:1},
        {q:"Defection means:",opts:["Winning an election","Changing one's party — joining another party after being elected","Losing an election","Supporting the opposition"],ans:1},
        {q:"The anti-defection law was passed to:",opts:["Encourage party changes","Prevent elected representatives from changing parties for personal gains","Ban all party changes","Allow free movement between parties"],ans:1},
        {q:"Alliance or coalition governments become necessary when:",opts:["One party wins majority","No single party wins clear majority","President wants coalition","Elections are held frequently"],ans:1}
      ],
      short: [
        {q:"Why do we need political parties? What are their functions?",a:"WHY WE NEED POLITICAL PARTIES:\nWithout parties, all candidates would be independent. Voters would have no way to know what policies a candidate supports. No one would be responsible for running the government. Coordination would be impossible in large democracies.\n\nFUNCTIONS OF POLITICAL PARTIES:\n1. CONTEST ELECTIONS: Put up candidates for elections\n2. FORM GOVERNMENTS: Winning parties form governments and implement their policies\n3. MAKE POLICIES: Parties put forward alternative policies for voters to choose\n4. MAKE LAWS: Parties with majority make laws in legislatures\n5. FORM OPPOSITION: Losing parties form opposition — check ruling party\n6. SHAPE PUBLIC OPINION: Parties raise issues, debate policies, inform citizens\n7. PROVIDE ACCESS: Help citizens access government and its policies/welfare schemes\n8. POLITICAL SOCIALISATION: Parties help form political views and educate citizens"},
        {q:"What are the major challenges faced by political parties in India?",a:"MAJOR CHALLENGES:\n\n1. LACK OF INTERNAL DEMOCRACY:\n• Power concentrated in top leaders (usually a family)\n• Ordinary members have little say in party decisions\n• No transparent internal elections in most parties\n• Leader's personal choice determines candidates\n\n2. DYNASTY (DYNASTIC SUCCESSION):\n• Leaders' children/relatives inherit party leadership\n• Prevents capable but non-connected leaders from rising\n• Affects BJP, Congress, SP, DMK, NCP etc.\n\n3. MONEY AND MUSCLE POWER:\n• Elections are expensive — parties rely on wealthy donors\n• This creates obligations to fund donors\n• Criminalisation — parties give tickets to candidates with criminal records if they can win\n\n4. CORRUPTION:\n• Parties accused of corruption in power\n• 'Quid pro quo' — money for votes, policies for donations\n\n5. LACK OF MEANINGFUL CHOICE:\n• Parties have become very similar in ideology\n• Citizens feel their vote doesn't change fundamental policies\n\nREFORMS NEEDED:\n• Transparent party funding and accounts\n• Mandatory internal elections\n• State funding of elections\n• Stricter enforcement of anti-defection law"},
        {q:"Describe the multi-party system in India. What are its advantages and disadvantages?",a:"MULTI-PARTY SYSTEM IN INDIA:\n• India has many national, state and local parties\n• Currently 6 national parties and hundreds of regional parties\n• No single party has consistently won majority in Lok Sabha since 1989\n• Coalitions have become the norm\n\nADVANTAGES:\n1. Represents India's incredible diversity — caste, language, religion, region\n2. No single ideology dominates\n3. More choices for voters\n4. Minorities and regions get representation through regional parties\n5. Coalition politics forces parties to negotiate and compromise — reduces extremism\n\nDISADVANTAGES:\n1. Government instability — coalitions can collapse\n2. Difficult to implement bold reforms when many parties have different interests\n3. Regional parties can hold national government 'hostage'\n4. Confusing for voters — too many choices\n5. Horse-trading and political opportunism\n\nEXAMPLE: After 1989, India has had mostly coalition governments (UPA, NDA) where regional parties play key roles. This reflects India's diversity but also creates governance challenges."}
      ],
      long: [
        {q:"What are the functions of a political party? How does the party system strengthen democracy?",a:"POLITICAL PARTIES AND DEMOCRACY:\n\nFUNCTIONS:\n1. ELECTORAL FUNCTION: Recruit candidates, campaign for them, help citizens choose\n2. LEGISLATIVE FUNCTION: Party members in legislature debate and vote on laws as a bloc\n3. EXECUTIVE FUNCTION: Winning party forms government, selects ministers\n4. POLICY FORMATION: Develop detailed policies and programmes\n5. OPPOSITION: Losing parties check, criticise and propose alternatives to government\n6. REPRESENTATION: Channel diverse demands and interests of different groups\n7. COMMUNICATION: Inform citizens about policies and gather feedback\n\nHOW PARTIES STRENGTHEN DEMOCRACY:\n1. ACCOUNTABILITY: Makes government accountable — opposition exposes failures\n2. CHOICE: Citizens choose between different visions of governance\n3. STABILITY: Provides organised, stable government rather than chaotic individual rule\n4. REPRESENTATION: Different parties represent different social groups and regions\n5. POLITICAL PARTICIPATION: Parties are channels for citizens to participate in politics\n6. PEACEFUL TRANSFER: Enables democratic alternation of power between parties\n\nWITHOUT PARTIES:\n• No coordination in legislature\n• No clear accountability\n• Citizens would have to evaluate thousands of individual candidates\n• Government could not function effectively\n\nCONCLUSION: Parties are indispensable for democracy, despite their flaws. They make democracy functional and representative."}
      ],
      passage: [
        {q:"'We need parties because we need governments. We need governments to make laws, policies and implement them. We need parties to form governments, make laws and implement policies. We also need parties to check on governments, debate policies and offer alternatives.'\n\n(a) What is the minimum requirement for a political party?\n(b) What would happen if there were no political parties?\n(c) How do parties make democracy more representative?\n(d) Name any two national political parties in India and their ideology.",a:"(a) Minimum requirements for a political party:\n• A party must have at least THREE components: leaders, active members, and followers\n• It must agree on some policies and programmes for society\n• It must seek to implement these by winning governmental power\n• Must contest elections to have a role in governance\n\n(b) Without political parties:\n• All candidates would be independents with no coordinated policies\n• Voters would have no way to know what policies a government would follow\n• Government formation would be chaotic and unstable\n• No organised opposition to check the government\n• The legislature would be unable to function effectively as there would be no coordination\n• Democracy would be dysfunctional\n\n(c) How parties make democracy representative:\n• Different parties represent different social groups, communities, regions and interests\n• Parties bring together people from diverse backgrounds under one platform\n• Regional parties represent specific regional interests in national governance\n• Coalition politics forces even dominant parties to accommodate diverse interests\n• Multiple parties ensure that no single group's interests are ignored\n\n(d) Two national parties:\n1. INDIAN NATIONAL CONGRESS (INC): Founded 1885, secular and centrist ideology, led independence movement, advocates mixed economy and social welfare\n2. BHARATIYA JANATA PARTY (BJP): Founded 1980, Hindu nationalist ideology (Hindutva), advocates cultural nationalism, free market economy"}
      ]
    },

    "Outcomes of Democracy": {
      mcq: [
        {q:"Democracy is better than other forms of government because it:",opts:["Is always more efficient","Promotes equality and dignity of citizens","Guarantees economic development","Never makes mistakes"],ans:1},
        {q:"Which of the following is NOT an expected outcome of democracy?",opts:["Political equality","Resolution of conflicts peacefully","Guaranteed economic prosperity","Minority rights"],ans:2},
        {q:"Democracies have been more successful in:",opts:["Preventing famines","Rapid economic growth","Eliminating poverty","Creating equality of wealth"],ans:0},
        {q:"The notion of 'accountable government' means:",opts:["Government that keeps accounts","Government that can be questioned and must justify its actions","Government that is fast","Government that is always right"],ans:1},
        {q:"Which country is a democracy with less economic development than some non-democracies?",opts:["USA","India (compared to China's growth rate at times)","UK","France"],ans:1},
        {q:"Democracy helps in managing social diversity because it:",opts:["Eliminates differences","Provides mechanisms for peaceful resolution of conflicts","Suppresses minorities","Makes everyone equal in wealth"],ans:1},
        {q:"'Transparency' in democracy means:",opts:["Clear glass buildings","Citizens' right to know about government decisions","Secret ballot","Media censorship"],ans:1},
        {q:"Majority decision-making in democracy should:",opts:["Ignore minorities completely","Be combined with respect for minority rights","Always override minority views","Be decided by the strongest group"],ans:1},
        {q:"Which of these is a feature that makes democracies better?",opts:["Quick decision making","Military discipline","Regular elections allowing people to change rulers","Single leader making decisions"],ans:2},
        {q:"The quality of democratic decision-making is better because:",opts:["Decisions are made faster","Decisions are based on wider consultation and deliberation","One expert makes decisions","Military controls quality"],ans:1},
        {q:"Democratic governments are more likely to respond to citizens' needs because:",opts:["Leaders are always good people","They need public support to win elections","They are selected by the army","They have more knowledge"],ans:1},
        {q:"Dignity and freedom of citizens is best protected in:",opts:["Military dictatorship","Monarchy","Democracy","Oligarchy"],ans:2},
        {q:"Democracies have NOT been very successful in:",opts:["Preventing concentration of power","Reducing economic inequality","Protecting minority rights","Allowing change of rulers"],ans:1},
        {q:"Which outcome shows democracy's failure?",opts:["Free elections","Free press","Persistent corruption","Freedom of speech"],ans:2},
        {q:"Democratic government is legitimate because:",opts:["It has military power","It is elected by the people","It has economic power","It has historical continuity"],ans:1}
      ],
      short: [
        {q:"How does democracy promote the dignity and freedom of citizens?",a:"DEMOCRACY AND DIGNITY/FREEDOM:\n\n1. EQUAL RIGHTS: All citizens are equal before law — regardless of birth, caste, gender, religion\n\n2. FREEDOM OF EXPRESSION: Citizens can criticise the government, express opinions freely\n\n3. NO ARBITRARY POWER: Government cannot punish citizens without due process — rule of law protects citizens\n\n4. WOMEN'S DIGNITY: Democracy formally recognises equal rights of women — challenged historic subordination\n\n5. DIGNITY OF LOWER CASTES: Democratic politics gave Dalits and lower castes political rights and voice — challenged caste discrimination\n\n6. MINORITY PROTECTION: Constitutions protect minority rights against majority domination\n\n7. CHANGE WITHOUT VIOLENCE: Citizens can change rulers through elections — no need for violent revolution\n\n8. TRANSPARENCY: Citizens have right to information about government decisions\n\nCOMPARISON:\nIn non-democracies, rulers can imprison citizens without trial, deny freedoms, and discriminate. Democracy provides institutional protections for human dignity."},
        {q:"Why is democracy considered a better form of government even when it is slow and makes mistakes?",a:"DEMOCRACY IS BETTER DESPITE LIMITATIONS because:\n\n1. ACCOUNTABLE: Government can be questioned, removed, and must justify its actions. Non-democratic governments have no accountability.\n\n2. LEGITIMATE: People accept democratic decisions more readily — even when they disagree — because they had a part in the process.\n\n3. SELF-CORRECTING: Mistakes can be corrected through elections, courts, media, civil society. Dictatorships have no correction mechanism.\n\n4. PEACEFUL CONFLICT RESOLUTION: Democracy provides channels to express grievances (courts, elections, protests) without violence.\n\n5. PREVENTS DISASTERS: Democracies rarely have famines because government is accountable to people — Sen's argument.\n\n6. RESPECTS DIGNITY: Even slow processes involve consultation and respect for all citizens.\n\n7. PARTICIPATION: Citizens are active participants, not passive subjects.\n\n8. CHECKS POWER: Multiple institutions prevent one person from becoming too powerful.\n\nDICTATORSHIP may be faster but:\n• No accountability if decisions are wrong\n• Citizens have no recourse\n• Can lead to catastrophic mistakes with no way to correct them"},
        {q:"What are the outcomes of democracy that we should evaluate it on?",a:"OUTCOMES TO EVALUATE DEMOCRACY:\n\n1. ACCOUNTABLE AND RESPONSIVE GOVERNMENT:\n• Does government respond to citizens' needs?\n• Can citizens question government decisions?\n• Is information available to citizens?\n\n2. LEGITIMATE GOVERNMENT:\n• Do people accept the government as legitimate?\n• Was it chosen through fair elections?\n\n3. ECONOMIC GROWTH AND DEVELOPMENT:\n• Does democracy deliver economic development?\n• Reducing poverty and inequality?\n• (Mixed record globally)\n\n4. REDUCTION OF INEQUALITY:\n• Does democracy reduce economic and social inequality?\n• (Not always — economic inequality persists in democracies)\n\n5. ACCOMMODATION OF DIVERSITY:\n• Does democracy manage social diversity peacefully?\n• Are minority rights protected?\n\n6. DIGNITY AND FREEDOM:\n• Are citizens treated with equal dignity?\n• Are fundamental freedoms protected?\n\n7. PEACEFUL CONFLICT RESOLUTION:\n• Are social conflicts resolved through negotiations rather than violence?\n\nCONCLUSION: Democracy performs well on political/social outcomes but has a mixed record on economic outcomes. It is still preferred because the alternatives are worse."}
      ],
      long: [
        {q:"'Democracy is a better form of government when compared to any other alternative.' Justify this statement.",a:"DEMOCRACY IS BETTER — JUSTIFICATION:\n\nPOLITICAL ADVANTAGES:\n1. ACCOUNTABILITY: Government can be questioned, voted out, and must justify decisions. No other system offers this.\n2. RULE OF LAW: All — including rulers — are subject to law. Prevents arbitrary use of power.\n3. RIGHTS AND FREEDOMS: Democracies protect fundamental rights — speech, assembly, press.\n4. PEACEFUL CHANGE: Transfer of power through elections, not violence.\n\nSOCIAL ADVANTAGES:\n1. DIGNITY: All citizens are equal — challenges caste, gender, racial discrimination.\n2. MINORITY PROTECTION: Constitution protects minority rights from majority domination.\n3. CONFLICT RESOLUTION: Provides peaceful mechanisms (elections, courts, negotiations) for resolving disputes.\n4. FAMINE PREVENTION: Sen argued democracies don't have famines — government is accountable.\n\nCOMPARED TO ALTERNATIVES:\n• Dictatorship: No accountability, no rights, no peaceful change possible\n• Monarchy: Rule by birth, not merit or consent\n• Oligarchy: Rule by few elites — ignores majority\n\nDEMOCRACY'S SHORTCOMINGS:\n• Slower decision-making\n• Economic inequality not automatically reduced\n• Can be corrupt\n• Politicians may prioritise short-term over long-term\n\nWHY STILL BETTER:\n• Democracies can correct their mistakes through elections and institutions\n• Citizens have agency and dignity\n• People's participation makes decisions legitimate\n• Has better long-term stability\n\nCONCLUSION: Democracy is not perfect, but as Churchill said, 'Democracy is the worst form of government, except for all the others that have been tried.'"}
      ],
      passage: [
        {q:"'Democracies are based on political equality. All individuals have equal weight in electing representatives. Parallel to the process of bringing individuals into political arena on an equal footing, we see a process of growing economic inequalities.'\n\n(a) What is political equality in democracy?\n(b) Despite political equality, why does economic inequality persist?\n(c) How can democracy address economic inequality?\n(d) Does economic growth happen faster in democracy or dictatorship?",a:"(a) Political equality in democracy means:\n• Every citizen has ONE vote — regardless of wealth, caste, gender, education\n• All votes have equal value\n• All citizens have equal rights to contest elections and hold office\n• Equal protection under law for all citizens\n\n(b) Economic inequality persists despite political equality because:\n• Democracy gives equal POLITICAL rights but does not automatically redistribute wealth\n• Rich people and corporations have more influence on policy through donations, media ownership\n• Economic systems create inequalities which political equality alone cannot fix\n• Implementation of redistributive policies is slow due to political compromises\n• Corruption siphons resources meant for the poor\n\n(c) Democracy can address economic inequality through:\n• Progressive taxation (higher taxes on wealthy)\n• Welfare programmes (MGNREGA, PDS, healthcare)\n• Reservations and affirmative action for disadvantaged groups\n• Regulation of industries to protect workers\n• Citizens can vote for parties that promise redistribution\n• RTI Act allows citizens to demand accountability in welfare delivery\n\n(d) Economic growth:\n• Neither democracy nor dictatorship consistently delivers faster growth\n• Some non-democracies (China) have had high growth; some democracies too\n• India (democracy) has had relatively high growth\n• Democracies tend to have more stable, sustainable long-term growth\n• Dictatorships may grow fast initially but lack correction mechanisms for policy mistakes"}
      ]
    }
  }
};
